### ISSUE TITLE
PlainClone breaking change for returned error in v4.8

### ISSUE THREAD

**Issue by jstangroome** [src-d/go-git#1027]
In v4.7.1, `git.PlainClone(path, ...)` would error with `git.ErrRepositoryAlreadyExists` if the `path` directory was already populated with a git repository.

In v4.8.0 the same call now returns an arbitrary `fmt.Errorf("directory is not empty: %s", path)` and breaks code which was checking for `err == git.ErrRepositoryAlreadyExists`.

Responsible code change appears to be: https://github.com/src-d/go-git/commit/3332e8d67dbe810d1607285d43fcd79470cf9961

**Comment by smola** [comment]
@jstangroome Thanks for reporting. I'm taking care of this ASAP.

**Comment by smola** [comment]
Fix proposed in https://github.com/src-d/go-git/pull/1028/files
For go-git v5, I propose to change this behavior and refuse upfront to clone on a non-empty dir, without even contacting remote server. Checking if a remote exists without creating a repository should be accomplished by a `git remote-ls`-like API.
