### ISSUE TITLE
Get Hash of latest commit

### ISSUE THREAD

**Issue by SchulteMK** [src-d/go-git#1034]
Thanks for the great work!

I am trying to receive the hash of the latest commit from a remote repository without cloning it. I already found out that this method exists: `func (r *Remote) List(o *ListOptions) (rfs []*plumbing.Reference, err error)`. But my problem is that I am not able to create an `*Remote` object because its fields are "hidden".

Can someone help me out please?

**Comment by SchulteMK** [comment]
The "normal" git cli implementation provides `git ls-remote`, which can be used to receive my desired information. `git ls-remote repo_url master` gets me the hash of the latest commit on the master branch without downloading the code base.
Is it possible to implement the same mechanism with the help of this package in go?

**Comment by SchulteMK** [comment]
I tried to do something like this as an workaround, but it failed...
```
func getLatestHash(url string, signer ssh.Signer) (string, error) {
	repository, err := git.Init(memory.NewStorage(), nil)
	if err != nil {
		return "", err
	}
	remote, err := repository.CreateRemote(&config.RemoteConfig{
		Name:  "origin",
		URLs:  []string{url},
	})
	if err != nil {
		return "", nil
	}
	rfs, err := remote.List(&git.ListOptions{
		Auth: &gitssh.PublicKeys{
			User:   "git",
			Signer: signer,
		},
	})
	fmt.Println("len(rfs)=", len(rfs))
	for _, r := range rfs {
		fmt.Println(r.Name(), r.Hash())
	}

	return "...", nil
}
```

**Comment by SchulteMK** [comment]
I got it working now. I had to include RefSpec when creating a new Remote.

```
func getLatestHash(url string, signer ssh.Signer) (string, error) {
	repository, err := git.Init(memory.NewStorage(), nil)
	if err != nil {
		return "", err
	}
	remote, err := repository.CreateRemote(&config.RemoteConfig{
		Name:  "origin",
		URLs:  []string{url},
		Fetch: []config.RefSpec{"+refs/heads/*:refs/remotes/origin/*"},
	})
	if err != nil {
		return "", err
	}
	rfs, err := remote.List(&git.ListOptions{
		Auth: &gitssh.PublicKeys{
			User:   "git",
			Signer: signer,
		},
	})

	var target plumbing.ReferenceName
	m := make(map[plumbing.ReferenceName]plumbing.Hash)
	for _, r := range rfs {
		switch r.Type() {
		case plumbing.SymbolicReference:
			if r.Name() == "HEAD" {
				target = r.Target()
			}
		case plumbing.HashReference:
			m[r.Name()] = r.Hash()
		}
	}

	if target == "" {
		return "", errors.New("detached HEAD")
	}
	hash, ok := m[target]
	if !ok {
		return "", git.ErrInvalidReference
	}
	return hash.String(), nil
}
```

Can I achieve the same result without creating an in-memory repository?

**Comment by smola** [comment]
@SchulteMK What you did https://github.com/src-d/go-git/issues/1034#issuecomment-446166558 is how it's meant to be done currently with the high-level API.

If you want something leaner, you would need to use the underlying transport API. You can look at `List` source code for more. All of its code is actually callable directly without Repository or Remote instances.

https://github.com/src-d/go-git/blob/3dbfb89e0f5bce0008724e547b999fe3af9f60db/remote.go#L929-L958

Related:
- https://github.com/src-d/go-git/issues/601
- https://github.com/src-d/go-git/pull/609
