### ISSUE TITLE
Suspicious duplicated branch bodies

### ISSUE THREAD

**Issue by Quasilyte** [src-d/go-git#1035]
https://github.com/src-d/go-git/blob/443abf89696c62d46e0c3e567c8ba380ff974d0d/plumbing/transport/test/receive_pack.go#L265-L269

It looks like something different should be here.
I could send a PR, but it's safer for maintainers to make a change there.

Found that spot using gocritic linter, `dupBranchBody` checker.

**Comment by smola** [comment]
This was introduced in https://github.com/src-d/go-git/commit/6a24b4c1f0cb9e5daf30fa7979f2643a967af1ad
It used to be:
```go
return r.ReceivePack(context.Background(), req)
```

It looks like a debug leftover. cc @erizocosmico

**Comment by erizocosmico** [comment]
Yup @smola. It's probably that

**Comment by smola** [comment]
@Quasilyte Feel free to send that PR!
