### ISSUE TITLE
[help] is it possible to set the `no-pushing` for specific remote?

### ISSUE THREAD

**Issue by fuweid** [src-d/go-git#1048]
Hi all, 

I checked the doc and found that it is no way to set `no-push` like `git remote set-url --push upstream no-pushing`. It seems that the `go-git` doesn't contains the `pushurl` field in the `config.RemoteConfig`, IIUC.

is there any schedule for this functionality?

Thanks!

**Comment by fuweid** [comment]
any update?

**Comment by fuweid** [comment]
ping @mcuadros

**Comment by jfontan** [comment]
If you only want to change the configuration file you can use `Config.SetConfig` (https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/format/config#Config.SetOption):

```
cfg, _ := repo.Config()
cfg.Raw.SetOption("remote", "origin", "pushurl", "no-pushing")
repo.Storer.SetConfig(cfg)
```

Note that go-git does not understand `pushurl` and will use the first url in the list.

**Comment by fuweid** [comment]
@jfontan Thanks for the suggestion! It works for me! Thank you.

**Comment by fuweid** [comment]
problem solved.
