### ISSUE TITLE
Pack file errors

### ISSUE THREAD

**Issue by sttts** [src-d/go-git#1053]
I often get error when accessing a commit object like:
```
failed to get 0dd9bbb598f56242180756a7f248637659aca18b: open /go-workspace/src/k8s.io/kube-proxy/.git/objects/pack/pack-8178a3fbc7dfa1521d8d18867bd9bd5490b33f1c.pack: no such file or directory
```

The commit object exists and `git show 0dd9bbb598f56242180756a7f248637659aca18b` is able to load it.

**Comment by jfontan** [comment]
Is it  possible that another process is changing your git repository? Maybe there's a git gc running while you execute that command. Does the file pointed by the error exist?

**Comment by sttts** [comment]
I will check next time it happens. I don't think there is another parallel git command though.

**Comment by jfontan** [comment]
If you find the problem again can you get a list of packfiles and update the issue? Thanks!
