### ISSUE TITLE
Question/Feature request - Getting object.Signature from git configuration files?

### ISSUE THREAD

**Issue by ulyssessouza** [src-d/go-git#1055]
Having a look at the code, I didn't find any part that reads the git configuration files to find  the `user.name` nor `user.email` for using to commit.
Is that available or I have to search and parse the git configuration myself?

**Comment by dexafree** [comment]
For functions not yet supported in `go-git` (such as stash management or reading the config) I've resorted to code like this:

```go
func performDirectGitCommand(repoPath string, command string) (string, error) {
	repoPath := repo.Path

	absoluteRoute, _ := filepath.Abs(repoPath)
	fullCommand := fmt.Sprintf("cd %s; git %s", absoluteRoute, command)

	cmd := exec.Command("/bin/sh", "-c", fullCommand)
	result, err := cmd.CombinedOutput()

	return string(result), err
}

func getGitUsername(repo Repo) (string, error) {
	name, err := performDirectGitCommand(repo, "config --get user.name")
	nameWithoutNewLine := strings.Replace(name, "\n", "", -1)
	return nameWithoutNewLine, err
}

func getGitEmail(repo Repo) (string, error) {
	name, err := performDirectGitCommand(repo, "config --get user.email")
	nameWithoutNewLine := strings.Replace(name, "\n", "", -1)
	return nameWithoutNewLine, err
}
```

**Comment by ulyssessouza** [comment]
@dexafree Thank you for the answer! But unfortunately, the introduction of `go-git` in my project is to avoid shelling out. :disappointed:

**Comment by jfontan** [comment]
@ulyssessouza you can use go-git to parse the global config file and extract any data that you want. Use `plumbing/format/config` package:

https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/format/config
