### ISSUE TITLE
`defer` missing in test code

### ISSUE THREAD

**Issue by object88** [src-d/go-git#1063]
Looking through the test code, I noticed that where the `context.WithCancel` func was used, the returned `cancel` func was immediately called.  I'm wondering if this was deliberate, and if so, why, and what purpose does it serve?

(Unfortunately, I wasn't able to get all of the tests to run, due to problems I am having with the `go-git-fixtures` package; any advice on getting that working w/ go 1.11.5 would be appreciated.)

**Comment by object88** [comment]
As a concrete example, the following:

``` go
func (s *RepositorySuite) TestCloneContext(c *C) {
  ctx, cancel := context.WithCancel(context.Background())
  cancel()

  // etc.
}
```

(From https://github.com/src-d/go-git/blob/master/repository_test.go#L178)

**Comment by mcuadros** [comment]
As you can see in this concrete example, what is being tested is that the clone doesn't work when a canceled context is given. So, at least in this case, is intentional.

**Comment by mcuadros** [comment]
I

**Comment by object88** [comment]
You are absolutely correct, figures that I would miss that.  Thank you.
