### ISSUE TITLE
is there a equivalent to git rm and git rm --recursive

### ISSUE THREAD

**Issue by ReK2Fernandez** [src-d/go-git#1068]
Hello I was looking at all the examples and was not able to see this. I need to remove/push changes to  the content of a folder before I add files and add/commit/push the new ones. just wondering. thanks

**Comment by jfontan** [comment]
`Worktree.Remove` is recursive if the target is a directory:

* https://godoc.org/gopkg.in/src-d/go-git.v4#Worktree.Remove
* https://github.com/src-d/go-git/blob/v4.10.0/worktree_status.go#L498-L518:

```go
	fi, err := w.Filesystem.Lstat(path)
	if err != nil || !fi.IsDir() {
		h, err = w.doRemoveFile(idx, path)
	} else {
		_, err = w.doRemoveDirectory(idx, path)
	}
```

**Comment by ReK2Fernandez** [comment]
@jfontan thank you, will try this.. I totally missed it.

**Comment by jfontan** [comment]
I'm closing this. If it didn't work comment again here.
