### ISSUE TITLE
problems install v4

### ISSUE THREAD

**Issue by sbenthall** [src-d/go-git#107]
Trying to install go-git.v4, I get this error:

```
$ go get -u gopkg.in/src-d/go-git.v4/...
# gopkg.in/src-d/go-git.v4/formats/packfile
../../../gopkg.in/src-d/go-git.v4/formats/packfile/scanner.go:168: undefined: io.SeekCurrent
../../../gopkg.in/src-d/go-git.v4/formats/packfile/scanner.go:311: undefined: io.SeekCurrent
../../../gopkg.in/src-d/go-git.v4/formats/packfile/scanner.go:316: undefined: io.SeekStart
../../../gopkg.in/src-d/go-git.v4/formats/packfile/scanner.go:434: undefined: io.SeekCurrent
../../../gopkg.in/src-d/go-git.v4/formats/packfile/scanner.go:454: undefined: io.SeekCurrent

```

**Comment by sbenthall** [comment]
Looks like the methods SeekCurrent and SeekStart really don't exist.

Rather, the golang io package defines a Seeker interface, with a Seek method, that takes it's Current/Start/End parameter as an integer argument:

https://golang.org/src/io/io.go?s=4702:4774#L102

https://golang.org/src/io/io.go?s=4702:4774#L20

**Comment by sbenthall** [comment]
> Looks like the methods SeekCurrent and SeekStart really don't exist.

Whoops. I see now this is precisely what this code is trying to do; access these constants. 

https://github.com/src-d/go-git/blob/master/formats/packfile/scanner.go#L158

**Comment by sbenthall** [comment]
Apparently this is a Go 1.6 vs. 1.7 thing. Sorry to bother you with this issue. Thanks for making such a great library!

**Comment by mcuadros** [comment]
Hahaha, yes, we only support 1.7, sorry about the outdated documentation. We plan to release the v4 soon, and update all the examples and documentation. Thanks
