### ISSUE TITLE
Try to improve performance for `git log --all` algorithm

### ISSUE THREAD

**Issue by kuba--** [src-d/go-git#1087]
`git log --all` memorizes all commits to make a correct flatten list. It's used in `src-d/gitbase` for queries like `select ... from commits`. 
Because of memorization step (in constructor), it has a bad impact on performance for big repos and simple queries e.g.: `select commit_author_name from commits limit 1`
Related to https://github.com/src-d/gitbase/issues/725

**Comment by stanvarlamov** [comment]
Would this help resolving performance problems with something like 
```
r.Log(&git.LogOptions{FileName: &fileNameInGit, Order: git.LogOrderCommitterTime,})
```
compare to `git log -n 1 "file_name"` with the purpose of getting the "last updated (committed)" on an individual file?
Currently in my tests on a simple Git repo it takes 3-4 hundred ms to execute the above `Log` followed by one `Next` on its result, running over in-memory clone. File System-based clone takes about 5 times longer. `git log "file_name"` over the same FS clone comes back immediately, with or without `-n 1`

**Comment by kuba--** [comment]
@stanvarlamov - It's not generally `Log` problem, but particularly `All: true` option. This option memorizes all graph to make a flat list, so the constructor is takes some time.

**Comment by stanvarlamov** [comment]
Thank you, @kuba-- 
On my issue finding the Last Modified for each/most files in the repo, it just looks like the current implementation of `Log` may not be the most efficient / or I should be using a different approach vs. running it for individual files. I see that `Log` does quite an extensive Commit analysis, starting from the 1st one available in the repo. It evaluates the "actions" of each commit by comparing the trees and then it checks whether the file specified in the Option is in the "delta". Running this for each file sounds like a lot of scanning of all commits over and over again.
I'm wondering if there is a more efficient way of determining the files affected by a commit than the one currently coded in `merkletrie`? If the answer is No - I'd need to change my flow to gather all commits info once and then go from the latest one back, till I check off every file I'm interested in. What bothers me is that, somehow, `git log` is very fast compare to `Log`, as well as github provides latest commit affecting each object as the basic info. So, I kind of tend to think that the `merkletrie`-centered approach used to determine the files affected may NOT be the most efficient for the task

**Comment by stanvarlamov** [comment]
It seems like there should be a way to code `DiffTree(currentTree, parentTree)` used in the `getNextFileCommit()` process to only look at the changes for the specific file passed in as an additional parameter vs. building a list of all changes in the commit and then checking whether the file is in the list
