### ISSUE TITLE
[FR] Add method PGPPayload() for tag and commit

### ISSUE THREAD

**Issue by sapk** [src-d/go-git#1116]
Before doing a PR I would like to know your if it would be accepted and what it should look like to be accepted.

Currently only the full Encode method of a commit/tag is exposed publicly. In the goal of being able to verify the payload directly from a keyring and not a armored key string like the Verify method of tag and commit, I would suggest to add another method like `PGPPayload() string` that export the result of `t.encode(o, false)`. This method could also be re-use in the Verify of commit and tag.

I mainly ask because it doesn't follow the contributing rule: `You should be able to run the same query using git. We don't accept features that are not implemented in the official git implementation.` as I don't think we can export without the sig with the git cli. But this method would be very useful and limit the duplication of code in and outside go-git to do the same.

**Comment by filipnavara** [comment]
Notably it's something we run into in Gitea. The GitHub API exposes the PGP payload to the users (https://developer.github.com/v3/git/commits/) and libgit2 has an API to get it (https://libgit2.org/libgit2/#HEAD/group/commit/git_commit_extract_signature).

**Comment by sapk** [comment]
Close by  #1127
