### ISSUE TITLE
user manual ?

### ISSUE THREAD

**Issue by catastrop** [src-d/go-git#1167]

**Comment by mcuadros** [comment]
All the documentation can be found at: https://godoc.org/gopkg.in/src-d/go-git.v4/
Also you can take a look to our example folder: https://github.com/src-d/go-git/tree/master/_examples

**Comment by catastrop** [comment]
For the software, not the source code.

Is command line operation for go-git is fully similar to git?

**Comment by mcuadros** [comment]
We don't provide any `cli` this is a library

**Comment by catastrop** [comment]
Can you tell me about some `cli`?
