### ISSUE TITLE
Get lightweight tags with func (*Repository) TagObject

### ISSUE THREAD

**Issue by MaxAst** [src-d/go-git#1169]
Running: 
```
ref, err := r.Head()
tag, _ := r.TagObject(ref.Hash())
fmt.Println(tag)
```
I'd like to get lightweight tags, not just annotated tags. Ideally, this would be done via options, similar to Clone etc.

**Comment by mcuadros** [comment]
Sorry as you can see the functions is retrieving `Tag` objects, not Tags in general, as a very different thing.

**Comment by MaxAst** [comment]
@mcuadros I get that, but I'm asking if it's possible for a Tag object to be a lightweight tag rather than just an annotated tag. In my example, I'd like to get the lightweight tag from my latest commit.
