### ISSUE TITLE
Support skipping TLS cert validation for individual repositories

### ISSUE THREAD

**Issue by alexmt** [src-d/go-git#1177]
As demonstrated [here](https://github.com/src-d/go-git/blob/master/_examples/custom_http/main.go) custom http client allows disabling cert validation.  However, this way only allow to disable cert validation globally. Is there any way to disable cert validation for one repo?

**Comment by mcuadros** [comment]
Based on this example, you can implement your own client, that avoid the cert verification for only one repository based on the request.
