### ISSUE TITLE
client http, support SSL insecure connections

### ISSUE THREAD

**Issue by mcuadros** [src-d/go-git#120]
As did @StupidHod we need to have optional support for insecure SSL connections:
https://github.com/StupidHod/go-git/commit/ed219250e2a3be58f8b75a47fc97ef7996924be6#diff-8c989aecb091aec747030aaddeaee67aR29

**Comment by mcuadros** [comment]
@ferhatelmas maybe you are interested on this

**Comment by ferhatelmas** [comment]
@mcuadros Sure, I am interested and thanks for letting me know about it.
