### ISSUE TITLE
repo.Reference(HEAD) return "reference not found" error in brand new repo

### ISSUE THREAD

**Issue by easonyq** [src-d/go-git#1209]
I've just init a normal repo by `PlainInit` and then check its current branch. I called:

```go
// same as "git symbolic-ref HEAD"
ref, err := repo.Reference(plumbing.HEAD, true)
```

and get an error said "reference not found".

But when I use Git CLI tools and "refs/heads/master" is the result.

![image](https://user-images.githubusercontent.com/6800839/62671421-6c6a9480-b9c9-11e9-90fd-cb4993ef67c1.png)

**Comment by saguywalker** [comment]
I also have the same problem. But it worked when I used:
`
ref, err := repo.Reference(plumbing.HEAD, false)
`

**Comment by jfontan** [comment]
The second parameter means that you want a hash reference. In a newly created repo `master` does not point to any commit because no commits exist. When false it returns a symbolic ref, the same as your git example.
