### ISSUE TITLE
Clone private, ssh based repo

### ISSUE THREAD

**Issue by skyflyer** [src-d/go-git#184]
I'm having issues establishing a connection to a private ssh-based git repo, on a non-standard port. I'm using URL in the form of `ssh://git@hostname:522/repositoryname.git` and I'm getting this as the output:

```
2016/12/13 22:40:28 Process exited with status 128
exit status 1
```

I've put a debug statement after the ssh.Dial method call and this apparently succeeds. Not really sure how to troubleshoot further, but I've verified that:

* ssh link to access github works (`err := r.Clone(&git.CloneOptions{URL: "ssh://git@github.com/src-d/go-siva"})`)
* ssh link with port specified works too (`err := r.Clone(&git.CloneOptions{URL: "ssh://git@github.com:22/src-d/go-siva"})`)

On the server, I see that the ssh session has been established:
```
Dec 13 22:53:08 linux sshd[21974]: Accepted publickey for git from [redacted] port 47324 ssh2: RSA [redacted]
Dec 13 22:53:08 linux sshd[21974]: pam_unix(sshd:session): session opened for user git by (uid=0)
Dec 13 22:53:08 linux systemd-logind[499]: Removed session 218.
Dec 13 22:53:08 linux systemd-logind[499]: New session 220 of user git.
Dec 13 22:53:09 linux sshd[21974]: pam_unix(sshd:session): session closed for user git
```

The `git ls-remote` with that URL returns:
```
$ git ls-remote ssh://git@hostname:522/repository
a8092e8bd7e46bb5152af0a2b0035e7e53682c31	HEAD
a8092e8bd7e46bb5152af0a2b0035e7e53682c31	refs/heads/master
```

I tried with MemoryRepository and FileRepository. With the FileRepository, I get a `config` file in the specified directory (not in the `.git` subdirectory!) with the following contents:

```
[remote "origin"]
	url = ssh://git@hostname:522/repository.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

So it is obviously doing something right, but trips somewhere... just don't know where exactly.

**Comment by mcuadros** [comment]
Can you print, the error or panic returned and also the code you are running?

**Comment by skyflyer** [comment]
@mcuadros, here it is:

Output:
```
$ ./main
2016/12/14 06:56:29 Process exited with status 128
```

Program:
```go
func main() {
	r, err := git.NewFilesystemRepository("testing")
	checkErr(err)

	err = r.Clone(&git.CloneOptions{URL: "ssh://git@git.domain.com:65022/yantra.git"})
	checkErr(err)

	ref, err := r.Head()
	checkErr(err)
	log.Printf("Head: %v\n", ref)
}
```

The only thing redacted here is the domain name. I'm running this on OS X 10.12.1 with `go version go1.7 darwin/amd64`. I'll try to setup delve (debugger) to see inside, but it is broken somehow on 10.12.1.

**Comment by mcuadros** [comment]
But checkErr is not printing the error right?

**Comment by skyflyer** [comment]
Sorry. The checkErr is below and yes, it is printing the mentioned error.

```go
func checkErr(err error) {
	if err == nil {
		return
	}
	log.Fatal(err)
}
```

**Comment by mcuadros** [comment]
Sorry, and the last thing I need is the server version you are running to try to replicate the error. And also if you can try the same code with the code from the master branch, because is not exactly the same code from v4.

**Comment by skyflyer** [comment]
I tested with two servers:
* gitolite3 v3.5.3.1-16-g2893b14 on git 1.9.1
* Gitlab 8.13.5

Also checked out the master branch and tested with commit `7fb250fa3a74c3f38056b59fd29663af093658bd`. Same results as before.

I can give you access to one of the git repos privately, if you think that will help you troubleshoot this easier.

**Comment by skyflyer** [comment]
N.B.: I can perform clone operation without problems if I use an http endpoint (tested with gitlab, can't test it with gitolite, as I don't have an http endpoint available there)

**Comment by mcuadros** [comment]
I just tested the go-git against bare git 1.9.1 and works (I found a small issue but related with the path, but returned error is "Repository not found") 

Can you provide access to your ssh server? https://github.com/mcuadros.keys (Thanks a lot)

**Comment by skyflyer** [comment]
As we've discussed privately, the `master` branch works, so I'm closing this ticket (and awaiting the change comes to `gopkg.in/src-d/go-git.vnext`. 

Thanks!

**Comment by mcuadros** [comment]
We will try to release a new tag the next week, thanks!

**Comment by mcuadros** [comment]
@skyflyer https://github.com/src-d/go-git/releases/tag/v4.0.0-rc5
