### ISSUE TITLE
Add support for file-based object storage

### ISSUE THREAD

**Issue by JoshuaSjoding** [src-d/go-git#19]
The go-git library currently relies on in-memory storage of objects. I am interested in adding support for file-based object storage. My long term goal is to use this as a lightweight library for cloning and pulling repositories to local disk.

Right now RAWObjectStorage is the only implementation of the ObjectStorage interface. I would like to contribute by adding a FileObjectStorage implementation that reads and writes objects to the file system.

Is this something that the developers are amenable to?

To meet my goal there would of course be a number of other required features, such as index file support, but those can be tracked as separate issues.

**Comment by JoshuaSjoding** [comment]
The current implementation of the Repository [directly includes RAWObjectStorage](https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/repository.go#L22). I suggest that the Repository be changed to work through the [ObjectStorage interface](https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/core/object.go#L20) instead. This way a FileObjectStorage implementation could take advantage of it.

To do this and still support the needs of the Repository, the ObjectStorage interface will need to provide some means of iterating over objects. This means an API change is necessary.

As an experiment last week I familiarized myself with the code by making such a change. You can see the result of the experiment [here](https://github.com/scjalliance/go-git/commit/855517cb6c6796c8893c0d9191e88ccf6e1b5c7a). You'll notice that I messed with the Iter implementations pretty heavily.

**Comment by alcortesm** [comment]
Dear Joshua,

We are already working on that, index and everything.

We will contact you again again with more details in a few days, when we
come back from FOSDEM (Brussels) to our offices in Madrid.

On Saturday, January 30, 2016, Joshua Sjoding <notifications@github.com>
wrote:

> The current implementation of the Repository directly includes
> RAWObjectStorage
> <https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/repository.go#L22>.
> I suggest that the Repository be changed to work through the ObjectStorage
> interface
> <https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/core/object.go#L20>
> instead. This way a FileObjectStorage implementation could take advantage
> of it.
>
> To do this and still support the needs of the Repository, the
> ObjectStorage interface will need to provide some means of iterating over
> objects. This means an API change is necessary.
>
> As an experiment last week I familiarized myself with the code by making
> such a change. You can see the result of the experiment here
> <https://github.com/scjalliance/go-git/commit/855517cb6c6796c8893c0d9191e88ccf6e1b5c7a>.
> You'll notice that I messed with the Iter implementations pretty heavily.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/src-d/go-git/issues/19#issuecomment-177043665>.
>


-- 
*Alberto Cortés*
Backend Software Engineer *||* source{d} <http://sourced.tech/>
GitHub <https://github.com/alcortesm> *|* LinkedIn
<https://www.linkedin.com/in/alcortesm> *|* Google+
<https://plus.google.com/112745437569579542152/posts>

*Claudio Coello 16, 2º Izq.*
*28003 Madrid, Spain*

**Comment by JoshuaSjoding** [comment]
Sounds good!

**Comment by alcortesm** [comment]
Awesome!

I'm eager to take a look to your work!

Thanks for your patience.

On Saturday, January 30, 2016, Joshua Sjoding <notifications@github.com>
wrote:

> Sounds good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/src-d/go-git/issues/19#issuecomment-177045618>.
>


-- 
*Alberto Cortés*
Backend Software Engineer *||* source{d} <http://sourced.tech/>
GitHub <https://github.com/alcortesm> *|* LinkedIn
<https://www.linkedin.com/in/alcortesm> *|* Google+
<https://plus.google.com/112745437569579542152/posts>

*Claudio Coello 16, 2º Izq.*
*28003 Madrid, Spain*

**Comment by mcuadros** [comment]
@JoshuaSjoding is great to see that you are interested on contribute on go-git. 

Our first implementation of ObjectStorage was for memory because our main objetive is be able to analyse a git repository very fast, but we are working on now days on a FileObjectStorage and all the required changes. Actually here it the first version of the [idx support](https://github.com/mcuadros/go-git/commit/bef437a3a8deea4ab2ae7549c6420521eedbb8ee) from some weeks ago.

Anyways any PR related about this or any other topic is more than welcome.

**Comment by mcuadros** [comment]
About the `FileObjectStorage` our idea was make the implementation based on .idx files (here is basic implementation of [idx reader](https://github.com/src-d/go-git/pull/13/files)), something more close to how works git internally when you make a clone than just plain files.

**Comment by JoshuaSjoding** [comment]
@mcuadros My primary use case is to be able to do the equivalent of a `git pull` over an existing local repository on disk. That local repository could either be in packed or loose format. In the long term I think that our `filesystem.Storage` should be able to support both in a single implementation.

Aside from the [idx reader](https://github.com/src-d/go-git/pull/13/files), have you guys started the implementation yet or would you like me to go ahead and take a shot at it?

**Comment by mcuadros** [comment]
@JoshuaSjoding this is perfect, our initial goals was make only base on the idx and pack file from a pulled repository. But make it work with both formats is the final goal.

The only work done was the idx reader (and is a naive implementation), so go ahead, now we are busy with other stuff so will be great if you can handle this task.
