### ISSUE TITLE
Need a way to delete a repository

### ISSUE THREAD

**Issue by sbenthall** [src-d/go-git#193]
Is there a way to delete a Repository?

When a Repository is loaded into memory, it would be nice if there was a way to remove it from memory without waiting first for garbage collection.

When a Repository is loaded into the filesystem, it would be nice if there was a way to remove it from the filesystem programmatically.

If there is a way to do this, I haven't been able to find it in the documentation.

**Comment by mcuadros** [comment]
No, this is not supported.

I am tagging this as "enhancement", if you want to contribute, could be a nice PR

**Comment by sbenthall** [comment]
Cool. I will look into it!

**Comment by smola** [comment]
I'm not sure it is a good idea to provide this.

Standard git itself doesn't do it, and in our case, the semantics of "delete repository" are not very clear. In fact, when using a filesystem go-billy, it is not possible to remove the filesystem itself unless we do `RemoveAll(".")`, which feels pretty unsafe.

Removing a repository is an operation that is better handled by the one instantiating the repository and its storage backend.

**Comment by thefallentree** [comment]
@smola  I think you misundertsood, he means to "unload" the repository from memory, not delete content from disk.

**Comment by smola** [comment]
@thefallentree Nope. We're talking about a generic way of deleting a repository, whether it's on memory, filesystem or another storage backend:

<blockquote>
When a Repository is loaded into memory, it would be nice if there was a way to remove it from memory without waiting first for garbage collection.

When a Repository is loaded into the filesystem, it would be nice if there was a way to remove it from the filesystem programmatically.
</blockquote>

Providing it on the filesystem doesn't look right to me.

Trying to provide it for memory is just trying to work against Go garbage collector. I'm not really an expert in Go, but as far as I know, there are only two ways of doing this:

* Make a memory storage backend in C doing our own memory management. This is not going to happen in the go-git main project (as not requiring cgo is one of the design principles of the project), but anyone is welcome to write a third-party storage backend providing this.

* Provide an `Unload` or `Delete` function that sets the internals of the memory storage to nil and then call to `runtime.GC`. IMHO, that's promoting an antipattern. If users want to do it, they can do it without relying on go-git. Just set your Storer / Repository to nil and call `runtime.GC`.

**Comment by smola** [comment]
Closing this.
Users should remove from filesystem using the underlying billy filesystem (or any other means).
Memory repositories should just be set to nil and Go GC should free the memory.

If the need of free'ing memory repositories is arising because of a memory leak or an excess of allocations, please, file a separate bug and we'll do our best to optimize memory usage.
