### ISSUE TITLE
Error: unknown channel ACK

### ISSUE THREAD

**Issue by jinroh** [src-d/go-git#194]
I sometime get a `unknown channel ACK` error while pulling from a repo with the `git://` protocol.

I did not find a way to reproduce this case every time, but I work on a unstable connection (which may be the reason).

I guess it is from this part of the code: https://github.com/src-d/go-git/blob/592b5385f41bc0cc433dde4975ca99f86a075556/plumbing/protocol/packp/sideband/demux.go#L134

Tell me if I can help.

**Comment by mcuadros** [comment]
I just tried the example: https://github.com/src-d/go-git/blob/master/examples/progress/main.go 

With "git://github.com/src-d/go-siva" and works, can you provide, your code and if public the Git repository?

**Comment by mcuadros** [comment]
ping @jinroh

**Comment by jinroh** [comment]
Sorry I can not reproduce the issue.

I'll close the issue and reopen it if I am able to find a reproducable way to hilight the problem.

**Comment by mcuadros** [comment]
thx
