### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by icambridge** [src-d/go-git#195]
Hi,

I've tried using this library to clone and analysis some git repositories. I've tried using both Filesystem and Memory repositories. And with both I appear to have memory leaks. I took two profiles while using the memory repositories two minutes apart. (See below) With an increase in memory of over 1GB while the repositories were less than 100MB. I've tried turning the repositories to nil (including everything the repository was passed to) and running garbage collection manually. This hasn't really helped. I've had a look through your code quickly and I've not seen anything. Do you guys think this is an issue on my side or your side?

![Memory Heap ](https://s3.amazonaws.com/s3.icambridge.me/random/heap3.gif)
![Memory Heap ](https://s3.amazonaws.com/s3.icambridge.me/random/heap4.gif)

**Comment by mcuadros** [comment]
Memory or filesystem uses `plumbing.MemoryObject` a representation in memory of the object, since usually you don't need all the objects at the same time, this is not a problem, the GC collects the old ones and free your memory. In your case, looks like your are keeping references to all your objects (or al least big ones), so ends having repository in Memory. Maybe this is the case?

**Comment by icambridge** [comment]
@mcuadros Thanks for your reply. I hacked together (seriously hacked and slashed it) a semi reproduction of what my application does to try and reproduce it. It seems once you call the commit iterator it loads the entire commit history into memory? So using symfony/symfony as an example of a large repository with an 87MB git repository it causes go to use ~1GB of RAM. Which I think seems a bit excessive.

Example code : https://github.com/icambridge/go-git-example
output : https://gist.github.com/icambridge/f0b27c74223bf67869b453d21b779c5c

**Comment by icambridge** [comment]
I've been working on solving the memory issue. Turns out it was my issue, I was reusing the same SQL prepared statements, changed it so I just created new ones constantly and my leak is solved.
