### ISSUE TITLE
Pull after Fetch does not update HEAD

### ISSUE THREAD

**Issue by skyflyer** [src-d/go-git#198]
When running `Pull` or `Fetch` on a FileSystemRepository, they both return an error when there is nothing new to fetch. (should this be a separate issue?)

Also, when doing `Fetch` to update repository and then `Pull`, I would expect to update my references, but the `HEAD` does not get updated.

In other words, I see that `Pull` is also performing a `Fetch` operation, but `Fetch` is not updating my head. And it is strange that `Fetch` and `Pull` return errors when nothing is to be pulled/fetched.

Steps to reproduce:

1. Clone a repo using go-git
1. Print Head: (i.e.: `3897b83b17306309fa8bb570c0404e1403d503bf`)
1. Using the `git` tool, push a new commit to the repo
1. Perform `Fetch` followed by `Pull`
1. Print Head (the result will be the same as in step 2)

If I don't perform a fetch, the head gets updated to the latest commit. I am calling `Fetch` and `Pull` methods on a `*Repository` instance.

After playing with it for some time, I managed to get it into a state, where it would not update the HEAD ref anymore: `2017/01/03 15:37:57 unknown channel ACK a0b3bee218aefd7f10ea45b12efd169edd128cab`

Now, even though I perform just a `Pull` operation, the HEAD stays at some earlier commit. If I list the commits, I don't see all of them (the newer ones are missing). Note that the current HEAD is at the value in the error above (`a0b3bee218aefd7f10ea45b12efd169edd128cab`).

I was testing this on a `master` branch.

**Comment by smola** [comment]
@skyflyer Thank you for the report. We'll look into this.

With respect to the errors when there is no update, that is the current behavior. `NoErrAlreadyUpToDate` is returned if there is nothing to update (see: https://godoc.org/gopkg.in/src-d/go-git.v4#pkg-variables). This was not documented in the `Pull` and `Fetch` methods, so I'm updating the docs.

**Comment by skyflyer** [comment]
Thanks for the heads up on that error, that's very useful.

**Comment by skyflyer** [comment]
@smola, I started getting another error from `Pull`: `ErrEmptyUploadPackRequest`

I'm calling it like this: `err = r.Pull(&git.PullOptions{RemoteName: remotes[0].Config().Name})` where `remotes, err := r.Remotes()` and `r` is `*git.Repository`;

I'm testing this with a master branch (commit `92d3de7255e3c92673c7e3f0298c26450d09dd98`). Should I be adding something to the `PullOptions` struct?

**Comment by mcuadros** [comment]
@skyflyer I just made a PR #207, fixing the main issue of this ticket. 

Can you create another issue, with the second problem? And you provide a repository or something more detailed? 

Thanks for your bug report is highly appreciated

**Comment by skyflyer** [comment]
Maximo, sure. I'll create another issue in an hour or so.

**Comment by skyflyer** [comment]
Created #208 to track no upload pack error.
