### ISSUE TITLE
No examples mention NewFilesystemRepository(".git")

### ISSUE THREAD

**Issue by mvdan** [src-d/go-git#220]
I was doing `NewFilesystemRepository(".")` with a cloned repo, assuming that was the thing to do. Only later did I find I should actually point it at the git dir.

I realise this should be obvious and it's in the godoc, but I think at least one example somewhere should show this kind of use. The only example that uses `NewFilesystemRepository` uses `"<path>"`, which isn't particularly useful.

**Comment by mvdan** [comment]
Okay, now after the whole import and constructor changes, I have to do `PlainOpen(".")` instead of `PlainOpen(".git")` otherwise I get `worktree should be provided`.

I realise this isn't stable, but I don't understand what's going on.

**Comment by mcuadros** [comment]
We changed the constructors, everything should be enough explained now in the constructors. If you want to open a repository use the folder where is, you never should target a .git folder in a non bare repository.

The v4 is not a stable version, so changes likes this can happen again.
