### ISSUE TITLE
object.WalkCommitHistory should walk parents in reverse order

### ISSUE THREAD

**Issue by mvdan** [src-d/go-git#223]
When you do `git log` and there has been a merge, you see something like:

* merge commit
* merged commit
* rest of history

But the way `WalkCommitHistory` is implemented, the first parent is walked first. This means that the history is traversed as:

* merge commit
* rest of history
* merged commit

I see no advantage in doing it this way. Using it the other way is more intuitive, and should also use less memory as merged histories are often much shorter (e.g. PRs) than the main ones.

**Comment by mvdan** [comment]
I've implemented it here, for example:

https://github.com/mvdan/git-picked/blob/1a5a800c92b4ccc6478d9a9e85bde39b670732df/main.go#L114

**Comment by mcuadros** [comment]
@smola

**Comment by smola** [comment]
@mvdan Thank you for taking the time to open the issue.

`git log` by default uses only one of the many ways that there is to walk the commit history. There are many others supported by options. So we'll be happy to accept a PR adding the behavior you propose, but as an option, since we do have use cases that require walking parents in their original order.

**Comment by mvdan** [comment]
Assuming the API is frozen and that you'd prefer a separate func, I propose my implementation above with a name like `WalkCommitHistoryReverse`, explaining what is special about it in its godoc.

**Comment by mvdan** [comment]
Also, cheers for doing nice Go work from Spain :) I moved away from Barcelona recently.

**Comment by smola** [comment]
@mvdan The API for v4 is not frozen yet, it will be frozen only once we release v4.0.0.

@mcuadros Any thoughts about the API for this?

WRT working in Spain, note that [we're hiring](http://sourced.tech/careers/) ;)

**Comment by mvdan** [comment]
Ah, sounds exciting, but not planning to move to Madrid anytime soon :)

> The API for v4 is not frozen yet, it will be frozen only once we release v4.0.0.

This is surprising. The docs suggest using v4, so I was assuming it was already stable.

**Comment by mvdan** [comment]
Status of this? Should I open a pull request?

**Comment by mcuadros** [comment]
The docs suggest use v4, because the v3 is very limited in terms of functionality. I could thing in the API, but of course a pull request can be open and we can discuss about it.

**Comment by mvdan** [comment]
Sorry for the confusion, I indeed meant the patch, not the version in the docs.

I'll open a pull request.
