### ISSUE TITLE
Clone repo with worktree

### ISSUE THREAD

**Issue by biancalana** [src-d/go-git#225]
Is it possible to clone a remote repo with worktree ? 

Doing a regular clone like examples:

```golang
       r, err := git.NewFilesystemRepository(directory)
        CheckIfError(err)

        // Clone the given repository to the given directory
        Info("git clone %s %s", url, directory)

        err = r.Clone(&git.CloneOptions{
                URL:   url,
                Depth: 1,
        })

```
Materialize a bare repo

**Comment by mcuadros** [comment]
this feature is still not implemente, is planned and will be released in the v4 version.

**Comment by biancalana** [comment]
I could try to implement that, can you elaborate a little on how to implement that ?

**Comment by mcuadros** [comment]
Your help is highly appreciated but in this case we already started the implementation. We are just waiting to have the new final difftree implementation https://github.com/src-d/go-git/issues/82
