### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by jinroh** [src-d/go-git#247]
I have a projet depending on `srcd.works/go-billy.v1` which is now in conflict with the current release of `srcd.works/go-git.v4` which still points to `gopkg.in/src-d/go-git.v4`.

I guess you are already planning to have a release of `srcd.works/go-git.v4` to fix this issue but I just wanted to open an issue to point out the problem.

-- pierre

**Comment by mcuadros** [comment]
This is because you are using master, hehehe. But yes we are releasing a new RC this morning

**Comment by mcuadros** [comment]
@jinroh can you try now?

**Comment by jinroh** [comment]
@mcuadros the dependency issue seems to be fixed. Thanks!

However I got compilation error:
```
../../../srcd.works/go-git.v4/worktree.go:93: os.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
```

Seems like the `os` package is not the right package.

**Comment by mcuadros** [comment]
Can you provide us the OS (I guess darwin) and the Go version?

**Comment by jinroh** [comment]
OS: darwin
Go version: 1.7.5

**Comment by jinroh** [comment]
```
$ go env                                                                                                                    [12:05:17]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pierre/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by mcuadros** [comment]
@jinroh can you try now?

**Comment by jinroh** [comment]
@mcuadros it's fixed. Thanks !
