### ISSUE TITLE
Question about push, is it always or never 'force'?

### ISSUE THREAD

**Issue by hartzell** [src-d/go-git#253]
Thanks for the library!

I'm looking at push.  I see the comment and the code [in remote.go @ line 57](https://github.com/src-d/go-git/blob/master/remote.go#L57) and I *think* that it's saying that the current implementation *always* force pushes (`git push -f`).

Can you make a definite statement about the current behavior?  Is anyone currently working on making the behavior controllable?

**Comment by smola** [comment]
@hartzell Yes. Right now it is always force push. We would like push to handle `+` in refspecs, and maybe also a `Force` boolean option in `PushOptions` to just force all references. Currently, nobody is working on this, but PRs are welcome.

**Comment by hartzell** [comment]
Thanks for the followup.  I don't think that I have the git-savvy to contribute at that level, but I'll keep it on the list.
