### ISSUE TITLE
add and commit support

### ISSUE THREAD

**Issue by dtmistry** [src-d/go-git#256]
Thank you for this awesome library!! I apologize if this question is already answered. 

I see there is support for push using go-git. Is it in the roadmap to support other porcelain commands like 'add' or 'push'?

Also, is there current support to update index or write tree? 

I'm trying to use go-git with the memory storer in a tool that updates an existing repository.

**Comment by thefallentree** [comment]
+1 ,  to do what git add/commit does it pretty heavy-lifting,  I think we can start with a simple CreateCommitWithBlob() sort of thing on Repository struct first.

**Comment by nobuhito** [comment]
👍

**Comment by Skilgarriff** [comment]
I would really love this feature as it would allow me to bundle my application with no external dependencies. Anything I can do to help here? I have some time this weekend, and would love to crank some of this out.

**Comment by mcuadros** [comment]
@Skilgarriff I invite you to take a look to the internals, but is not one weekend task.

The main thing required to start, is implement `Worktree.Status` (`git status`) based on [merkletrie](https://github.com/src-d/go-git/tree/master/utils/merkletrie) to compare the file system tree, staging area and HEAD

Having a proper status, will be easy implement `git add` and `git commit`, those methods aren't more than wiring between other components

**Comment by mcuadros** [comment]
@Skilgarriff I am doing myself the implementation of status. I hope you didn't started

**Comment by Skilgarriff** [comment]
@mcuadros I have not started yet, I was planning on checking it out today. Can I help at all? Or will you ping here when that is completed and we could begin looking at commit and add

**Comment by mcuadros** [comment]
I am opening a PR a soon as I have something, to let you see what is being implemented

You can work in the `add` now if you want, take a look how create objects, is not very evolved and maybe you will need to do some PRs
