### ISSUE TITLE
Dropped git ref is breaking builds

### ISSUE THREAD

**Issue by goosemo** [src-d/go-git#260]
Looks like you moved things, and/or removed some commits?

```
$ gb build all
fatal: reference is not a tree: d0ea76c141cb2fab330b769234046afad615c299
FATAL: command "restore" failed: could not retrieve dependency: exit status 128
FATAL: command "vendor" failed: exit status 1
make: *** [vendor] Error 1

$ grep -R d0ea76c141cb2fab330b769234046afad615c299 -B2 ./vendor
./vendor/manifest-            "importpath": "gopkg.in/src-d/go-git.v4",
./vendor/manifest-            "repository": "https://gopkg.in/src-d/go-git.v4",
./vendor/manifest:            "revision":"d0ea76c141cb2fab330b769234046afad615c299",
```

Should one not expect that paths and versions of this library will not change out from under them?

**Comment by mcuadros** [comment]
Yes we made a filter branch to remove the fixture files to have a more light repository sorry for that.

**Comment by goosemo** [comment]
ok, looks like you also moved caches? from `gopkg.in/src-d/` to `srcd.works`? Should I just skip these and pull straight from Github? I'm not seeing what these indirect hosts give me?

**Comment by mcuadros** [comment]
We made several changes, you should use srcd.works, we were having some issues, all this problem will be solve with the stable release. Sorry

**Comment by goosemo** [comment]
You realize that changing your repo source breaks library imports in code right? This isn't something to do lightly in Go. 

When you retire that location, none of your old released code will work. See this for an example:
https://github.com/src-d/go-git/blob/02c228585e543413479ea36d3a2bbc80a070eb93/common_test.go#L10

Pretty much the only good way around it is to use `gb` and not `go get` because at least then I can set the import path to something other than the repository path. For future googlers, I used the below commit and aliasing to address my build failures:

```
               {
                       "importpath": "gopkg.in/src-d/go-git.v4",
                       "repository": "https://srcd.works/go-git.v4",
                       "revision": "0ff9ef2b44c53e557c78bde0fd9c29847e5f0e23",
                       "branch": "HEAD"
                }
```
