### ISSUE TITLE
Is there any common.Auth example?

### ISSUE THREAD

**Issue by themihai** [src-d/go-git#29]
I'm trying to find out how the authentication works. It looks to be a common.Auth interface but I'm wondering, how can `Name()` and `String()` authenticate a request?

``` 
    type AuthMethod interface {
    Name() string
    String() string
}

```

Digging through the source code I've found that actually `clients/http.HTTPAuthMethod` is required which defeats the purpose of interface based design. Even so  `setAuth(r *http.Request)` is private so I still can't figure out how I'm supposed to construct a http.HTTPAuthMethod.

 Is there any reason why the auth type is not a http.RoundTripper? I think it became a standard method to proxy client requests just like ServeHTTP does on the server server-side. E.g.  NewAuthRemote(url string, auth http.RoundTripper) (*Remote, error).  

 I would also complain about the lack of a context.Context but might be a bit too much.

**Comment by mcuadros** [comment]
`common.AuthMethod` is a interface used by any `common.GitUploadPackService` like SSH or HTTP, so we cannot add more restrictions to the interface. `common.AuthMethod` is a parameter received by a method in the interface `common.GitUploadPackService`:

```go
type GitUploadPackService interface {
	Connect(url Endpoint) error
	ConnectWithAuth(url Endpoint, auth AuthMethod) error
	Info() (*GitUploadPackInfo, error)
	Fetch(r *GitUploadPackRequest) (io.ReadCloser, error)
}

type AuthMethod interface {
	Name() string
	String() string
}
```

What is true is that the specific interface for HTTP cannot be implemented by an external package: 
```go
type HTTPAuthMethod interface {
	common.AuthMethod
	setAuth(r *http.Request)
}
```

Are you trying to implement alternative HTTPAuthMethod? If yes a PR will be more than welcome to make `setAuth` public. Also is welcome a PR make it the authentication work with a `RoundTripper` that is obviously a better pattern than the current one signing the requests.

**Comment by themihai** [comment]
Yes, I was trying to implement HTTPAuthMethod. There is no standard git http authentication method so it seems the options are currently limited to whatever http.HTTPAuthMethod currently implements (basic auth?) which doesn't seem right. 
 I must recognise that I still didn't get how to acquire a HTTPAuthMethod. Below is my naive attempt:

```
package main
import (
        "github.com/src-d/go-git/clients/http"
        "fmt"
        git "gopkg.in/src-d/go-git.v2"
)

func main() {
        au :=  http.NewBasicAuth("user-build", ";msxasdsdFJ,4Cg]")
        r, err := git.NewAuthenticatedRemote("https://bitbucket.org/myuser/tools", au)
        if err != nil {
                panic(err)
        }
        if err = r.Connect(); err != nil {
                panic(err)
        }
        refs := r.Refs()
        for k, v := range refs {
                fmt.Printf("ref %s, sha %s\n", k, v)
        }
}

```
Errors out ``invalid http auth method: a http.HTTPAuthMethod should be provided.``. Isn't BasicAuth supposed to implement http.HTTPAuthMethod?


PR: To make it work with ``http.RoundTripper`` I think we only need to replace ``setAuth(r *http.Request)`` from HTTPAuthMethod with RoundTripper signature ``RoundTrip(*http.Request) (*http.Response, error) `` . Let me know if this sounds reasonable or if there is anything else that I should be aware of.

  Perhaps on V3 a context.Context param should be considered. Google seems to use this approach on its libraries(i.e. the cloud stuff and oauth2). This is a breaking change because nearly all the methods/functions should require a context parameter. To set the authentication and retrieve it we can have FromContext/WithValue like functions . e.g. `http.WithAuth(context.Context, r http.RoundTripper)context.Context`, `http.FromContext(context.Context)http.RoundTripper`,  `ssh.WithAuth(contenxt.Context, ssh.Keys?)context.Context`, ` `ssh.FromContext(context.Context)ssh.Keys?`,

**Comment by mcuadros** [comment]
I just tried your code and works like a charm with my bitbucket repositories:

```
^^>>> go run test.go                                                                                                                                                   
ref refs/pull/11/head, sha e0f69995e7900b05d6729e0c29aebeb53b1d289c
ref refs/pull/18/head, sha 6a9eb0101114a002788f553e1c7a6ef3f2e92c33
ref refs/pull/22/head, sha bdbd42bc59552d62cd595153f4b7f2af39209e43
```

Can you paste the panic? 

If the password is wrong, you will get 
```
^^>>> go run test.go                                                                                                                                                       
panic: permanent client error: repository not found

goroutine 1 [running]:
...
```

**Comment by themihai** [comment]
It's strange that my example works on your side. 
Anyway I've found the issue: I mixed the github.com imports with gopkg.in so the type assertion didn't work. 
  I will try to send a PR with the RoundTripper proposal sometimes this month.
