### ISSUE TITLE
Walking through tree of non `gitignore`d files

### ISSUE THREAD

**Issue by cirocosta** [src-d/go-git#307]
Hey,
first i'd like to say that `go-git` is amazing; nice work! Discovered this week and still playing around with it :)

Now to the question, is it possible to walk through the tree of objects and gather only those that are not ignored by a `.gitignore` file? What i'd like to do is clone a repository, apply some changes (which might produce some files that would be ignored) and then walk through this tree.

Thx!

**Comment by smola** [comment]
@cirocosta go-git has no `.gitignore` support yet, so you'd have to read .gitignore first, and then filter the tree yourself.

We are not planning to work on this in the short term, but PRs are welcome.

**Comment by osklyar** [comment]
PR enclosed

**Comment by cirocosta** [comment]
Great! Thx @osklyar  :D

**Comment by osklyar** [comment]
Closed the original PR, but am working on a new fix for this issue.

**Comment by osklyar** [comment]
New PR #429 wit a complete implementation
