### ISSUE TITLE
rename "internal" to "lib" so this library plays nicely with vendoring

### ISSUE THREAD

**Issue by thebeefcake** [src-d/go-git#308]
`go get srcd.works/go-git.v4/...
package srcd.works/go-git.v4
	imports gopkg.in/src-d/go-git.v4/internal/revision: use of internal package not allowed
`

**Comment by smola** [comment]
@thebeefcake I think you're hit by the import path change.

We changed from `srcd.works/go-git.v4` back to `gopkg.in/src-d/go-git.v4` (and that's the import path that will be used for the upcoming stable release). Changing your imports should solve the problem.

Feel free to reopen this issue if you think this is not the right solution.
