### ISSUE TITLE
Reference hashes not preserved in memory storage

### ISSUE THREAD

**Issue by sbenthall** [src-d/go-git#309]
Thanks so much for this library.

I'm running into an issue using references on a Clone using memory storage.

Here is my code:

```
package main

import (
	"fmt"
	"gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing"
	"gopkg.in/src-d/go-git.v4/storage/memory"
)

func main() {

	r, _ := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
		URL: "github.com/ion-channel/glide-test-2",
	})

	refs, _ := r.References()

	refs.ForEach(func(ref *plumbing.Reference) error {
		fmt.Println(ref.Type())
		fmt.Println(ref.Hash())

		return nil
	})
}
```

The output is:

```
2
0000000000000000000000000000000000000000
```

The actual hash of the reference being iterated over is e79bcde

The repository being used for this test is:

https://github.com/ion-channel/glide-test-2

The functionality I expect is for the hash returned for the reference to correspond to the hash of the commit referenced.

**Comment by mcuadros** [comment]
You will laugh, I was expending also half hour to guest what was happening.  

The URL that you are using, is missing any protocol, and since your are ommiting the error `permanent client error: invalid endpoint: github.com/ion-channel/glide-test-2`

**Comment by sbenthall** [comment]
Thank you!
