### ISSUE TITLE
Annotated Tags support

### ISSUE THREAD

**Issue by themihai** [src-d/go-git#31]
This is a request to support annotated tags in a similar way Commits are supported. Currently there doesn't seem to be a straightforward way to pull the tag annotations(unless I'm wrong). Below are my attempts. The first one hangs (it seems there is a leak/channel blocking indefinitely) before I can do anything useful. The second one errors out with ``unexpected client error: EOF``

```
package main

import (
	"flag"
	"fmt"
	log "github.com/golang/glog"
	git "gopkg.in/src-d/go-git.v2"
	"gopkg.in/src-d/go-git.v2/clients/http"
	"io"
)

func main() {
	flag.Parse()
	defer log.Flush()
	auth := http.NewBasicAuth("myuser", ";xag]")
	r, err := git.NewRepository("https://bitbucket.org/myuser/tools", auth)
	if err != nil {
		log.Error(err)
		return
	}

	if err := r.Pull("origin", "refs/tags/0.0.1^{}"); err != nil {
		log.Error(err)
		return
	}
	triter := git.NewTreeIter(r)
	defer triter.Close()
	for {
		tree, err := triter.Next()
		if err != nil {
			if err == io.EOF {
				break
			}

			log.Error(err)
			return
		}
		log.Errorf("new tree %v", tree)
		return
	}

}
```

```
...
              
		req := &common.GitUploadPackRequest{}
		req.Have(previousTagSHA)
		req.Want(latestTagSHA)
 
		rc, err := repo.Fetch(req)
		if err != nil {
			log.Error(cx, err) 
			return nil, err
		}
```

**Comment by themihai** [comment]
I ended-up using GitUploadPackRequest and set only ``req.Want(TagSHA)`` . Still there doesn't seem to be a way to fetch the annotation message alone. After reading the protocol specs it seems to be a shortfall of the git protocol rather than go-git so I'm closing this.

**Comment by JoshuaSjoding** [comment]
While you can't pull just the annotated tags via the protocol, it should be possible to [clone an entire repository and then work with the tags](http://stackoverflow.com/questions/791959/download-a-specific-tag-with-git). `go-git` is currently lacking that feature.

I'll work on a PR to add annotated `Tag` support. I intend to add a `Repository.Tags()` function similar to `Repository.Commits()` that returns a `TagIter`. I'll add a `Repository.Tag()` function that retrieves a particular tag as well.

I recommend reopening this issue until the PR is accepted.

**Comment by themihai** [comment]
Sounds awesome!

**Comment by mcuadros** [comment]
@themihai the feature just landed on the master branch. Thanks @JoshuaSjoding
