### ISSUE TITLE
Workaround for git reset --hard $SHA

### ISSUE THREAD

**Issue by kimh** [src-d/go-git#311]
Hi, I want to do the following by using go-git v4.

```
git fetch
git reset --hard $SOME_SHA
```

but I see `git reset` is not implemented. Are there any workarounds?

**Comment by mcuadros** [comment]
Sadly the `Worktree` is in a very primitive state, so nope. Anyways should not be hard to implement it.

**Comment by kimh** [comment]
Understood. I'm satisfied with your answer, so closing the issue.

**Comment by mumblez** [comment]
Sorry to open this up again, just wondering along the same lines if it's now possible?
specifically how would I go about:

git fetch; git reset --hard origin/master

?

Any advice is much appreciated, thanks.

**Comment by kimh** [comment]
@mumblez 

I ended up doing something like this (no error checking):

```
r, _ = git.PlainOpen(checkoutDir)
w, _ := r.Worktree()
commit := plumbing.NewHash(sha)
w.Reset(&git.ResetOptions{
	Mode:   git.HardReset,
  Commit: commit,
})
```

**Comment by mumblez** [comment]
@kimh thanks, I managed to come up with a solution - https://github.com/mumblez/gwg/blob/21bc1ec25274e5e6e355d54f96da1a2811e89734/main.go#L95 - though quite involved and lots of checking!
