### ISSUE TITLE
Issue new release on https://github.com/src-d/gcfg

### ISSUE THREAD

**Issue by calvn** [src-d/go-git#312]
I am using `go dep` to resolve dependencies for `go-git.v4`, and I am encountering a dependency error with `gcfg`. 

```
vendor/gopkg.in/src-d/go-git.v4/plumbing/format/config/decoder.go:36: undefined: gcfg.ReadWithCallback
```

`dep` uses the latest release by default, which is "v1.2.0" for `gcfg`. That release, however, does not include the two commits from Oct. 2016 which includes the addition of `ReadWithCallback()`.

I tried pinning to v1, but unfortunately `dep` prefers tags over branches, so it pins to the v1.0.0 tag (which is actually two steps backwards). I am currently pinning the repo against master, but that's non-ideal for consistent dependency resolution. It'd be great if a new release, v1.3.0, could be issued to resolve this dependency problem. Thanks!

P.S. I couldn't find a way to open an issue on that repo, so doing it here instead.

**Comment by smola** [comment]
@calvn Thank you for taking the time to report this issue!
I have just pushed a v1.3.0 tag on src-d/gcfg: https://github.com/src-d/gcfg/releases/tag/v1.3.0

If you think this issue is still not fixed, feel free to reopen it.
