### ISSUE TITLE
Golang bug breaks timezone parsing in Signature.Decode 

### ISSUE THREAD

**Issue by lupine** [src-d/go-git#318]
I just opened https://github.com/golang/go/issues/19750 as I've found a bug in `time.Parse()` when parsing *just* timezones on some machines.

Unfortunately, this affects go-git and it's where I spotted the bug in the first place: https://github.com/src-d/go-git/blob/v4/plumbing/object/object.go#L141

On my machine, when the time to be parsed is "+0000", this line leads to a `time.Time` object being created where `Location() == time.Local`. Unfortunately, `time.Local` is a +0100 offset, not a +0000, so the timezone changes when decoding.

Hopefully the bug will be fixed in Go, but since that could take months to be released, would you consider a patch to change that line to:

 ```go
tl, err := time.Parse("2006 -0700", string("1970 " + b[tzStart:tzStart+timeZoneLength]))
```

?

**Comment by smola** [comment]
@lupine Thank you!

Yes. We'll gladly accept a patch for this. Be sure to include a comment referencing the Go issue so that nobody undoes this in the future.

**Comment by smola** [comment]
Wait. @lupine: I've checked your test case (https://play.golang.org/p/ND8CEYOKcT) and the output seems correct:

```
// Running locally (mac, on a machine whose local timezone is BST: +0100), I see:
//
// UTC: 0x1113a20 UTC
// Local: 0x1115860 Local
// tl1: Format: "+0000" Location: 0x1115860 Local
// tl2: Format: "+0000" Location: 0xc42006a0c0
```

The formatted offset looks good to me. Do you have a correct date and timezone conf in your system?

**Comment by lupine** [comment]
@smola the formatted offset looks fine, but `Location()` returns `time.Local`, which is actually a +0100 offset. I have no idea how that happens, but it results in the timezone of the parsed commit being different to the timezone in the packfile.

I can replicate this on multiple Go versions, on multiple machines with sane date and timezone configurations.  One is Mac OSX, one is Debian Jessie, their local times are BST because I live in the UK ^^.

Running `date` gives output like:

```
gitlab-mbp:es-git-go lupine$ date
Wed 29 Mar 2017 13:43:41 BST

lupine@home:~$ date
Wed 29 Mar 13:43:36 BST 2017
```

**Comment by smola** [comment]
@lupine What does `time.Now().Format("-0700")` give you there?

**Comment by lupine** [comment]
```go
package main

import "fmt"
import "time"

func main() {
	fmt.Println(time.Now().Format("-0700"))
}
```

Results in "+0100".

A week ago, it would have resulted in "+0000", of course :D - daylight savings time.

**Comment by mcuadros** [comment]
@lupine a PR is welcome
