### ISSUE TITLE
Export raw config

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#321]
Would it be reasonable to export the raw config for cases where a client needs to look at specific items? The other tool I'm working with stores custom metadata in the config file and I need to be compatible with it.

**Comment by smola** [comment]
@taralx We do keep the raw config as long as it is in the right git-config format. You can call [https://godoc.org/gopkg.in/src-d/go-git.v4/config#Config.Marshal](Marshal) to get a `[]byte` with the contents of the git config file. You can get the config itself from `Repository.Storer.Config()`.

**Comment by taralx** [comment]
Thanks for your response. I'm actually looking to get the "gopkg.in/src-d/go-git.v4/plumbing/format/config".Config object, which allows me to do lookups without doing the parsing myself. Right now I'm using this code to bypass the export restriction:

```go
func rawConfig(c *config.Config) *rconfig.Config {
        raw := reflect.ValueOf(c).Elem().FieldByName("raw")
        return (*rconfig.Config)(unsafe.Pointer(raw.Pointer()))
}
```

**Comment by taralx** [comment]
FYI: I do not have permissions to reopen this issue, but would like it fixed.
