### ISSUE TITLE
PlainClone non-existent repo returns misleading error

### ISSUE THREAD

**Issue by chrisdostert** [src-d/go-git#322]
Scenario:
I pass a non-existent repo url ('github.com/go-git/xxxxx' for example) to PlainClone

Expected:
I get back a "Repository Not found" error

Actual:
I get back an "authorization required" error

For comparison, calling `git clone github.com/go-git/xxxxx` returns:
`
Cloning into 'xxxxx'...
remote: Repository not found.
fatal: repository 'https://github.com/go-git/xxxxx/' not found
`

**Comment by chrisdostert** [comment]
Tracked down where the error is comming from: [plumbing/transport/http/upload_pack.go#L65](https://github.com/src-d/go-git/blob/master/plumbing/transport/http/upload_pack.go#L65)

I'd like to submit a PR but would like some guidance about desired behavior; should we be performing a call to test if the repo exists somewhere before we ever reach this call?

**Comment by mcuadros** [comment]
If the server ask for auth, then makes sense [return](https://github.com/src-d/go-git/blob/master/plumbing/transport/http/upload_pack.go#L64-L66) ErrAuthRequired.

I just tested and cgit return `not found`, but used to do the same of go-git, return `Auth Required`  

/cc @smola

**Comment by smola** [comment]
Current behavior is correct for your case, but not complete for others.

GitHub and most other Git providers do not make distinctions between non-existing repositories and existing repositories you have no access to. This is done to not disclose private information (i.e. repository existence itself). This is GitHub behaviour on HTTP:

* If you use no credentials, uses `401 UNAUTHORIZED` both for private and non-existent repositories.
* If you're authenticated, then `404 NOT FOUND` is used (for private repositories you have no access too).

Git [spec for HTTP protocol](https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt#L99) says:

```
General Request Processing
--------------------------

Except where noted, all standard HTTP behavior SHOULD be assumed
by both client and server.  This includes (but is not necessarily
limited to):

If there is no repository at `$GIT_URL`, or the resource pointed to by a
location matching `$GIT_URL` does not exist, the server MUST NOT respond
with `200 OK` response.  A server SHOULD respond with
`404 Not Found`, `410 Gone`, or any other suitable HTTP status code
which does not imply the resource exists as requested.

If there is a repository at `$GIT_URL`, but access is not currently
permitted, the server MUST respond with the `403 Forbidden` HTTP
status code.
``` 

On the other hand, git doesn't seem to care about `403 Forbidden` at all, and just looks for `200`, `301`, `404` and `401`. See source code: [https://github.com/git/git/blob/e0ef7fe78c46e6919d249b9547948a3bb7321dea/remote-curl.c#L307](remote-curl.c:307) and [https://github.com/git/git/blob/625568cd8813bf32b2172eaf59e45e9da5978ce3/http.c#L1350](http.c:1350). As far as I can see, if you're not using any credentials, and you get a `401`, you'll be asked to enter credentials.

Currently we're not treating every error code. I think the behavior should be:

* `404 -> transport.ErrRepositoryNotFound`
* `401 -> transport.ErrAuthenticationRequired` (renamed from `transport.ErrAuthorizationRequired`)
* `403 -> transport.ErrAuthorizationFailed` (new error)
* `not 200 -> error`

PRs are welcome for this, but keep in mind that it will not change for your use case.

**Comment by chrisdostert** [comment]
@smola thanks for the explanation! I hadn't considered the behavior might differ based on creds being passed; makes perfect sense based on your explanation. 

Also thanks for the awesome project; i'm using it in [opctl](https://github.com/opctl/opctl) for package resolution
