### ISSUE TITLE
Examples: Checkout Commit

### ISSUE THREAD

**Issue by marwan-at-work** [src-d/go-git#323]
I think it would be great to add as many examples to the repo as possible, given that workflows are different. i.e.:

git cli: `git checkout ae200dcc6592716c757372cf01825f21a6b6xxxx`
go-git, sudo, : `repo.Worktree().Checkout(plumbing.NewHash("ae200dcc6592716c757372cf01825f21a6b6xxxx")`

Although this might be trivial to git-pros, I think it's really good to include common scenarios like this one. I'd love to submit a quick pr for it. Here's a simple example:

```golang
repo, err := git.PlainClone("/tmp/foo", false, &git.CloneOptions{
  URL: "https://github.com/src-d/go-git.git",
  Progress: os.Stdout,
})
CheckIfError(err)

wt, err := repo.Worktree()
CheckIfError(err)

commitRef := plumbing.NewHash("ae200dcc6592716c757372cf01825f21a6b6xxxx")
err = wt.Checkout(commitRef)
CheckIfError(err)
```

**Comment by smola** [comment]
@marwan-at-work We'll be glad to accept a PR adding a checkout example.

**Comment by marwan-at-work** [comment]
https://github.com/src-d/go-git/pull/331 
cc: @smola
