### ISSUE TITLE
add support for git alternates

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#325]
Simple test to retrieve an object from a lightweight clone results in "object not found" errors.

**Comment by taralx** [comment]
Steps to reproduce:

```go
package main

import git "gopkg.in/src-d/go-git.v4"

func main() {
        r, _ := git.PlainOpen("test2")
        h, _ := r.Head()
        _, err := r.CommitObject(h.Hash())
        if err != nil {
                panic(err)
        }
}
```

```sh
mkdir test; cd test
git init
git commit -m "test" --allow-empty
cd ..
git clone -s test test2
cd test2
git cat-file -p HEAD
cd ..
go run t.go
```

Expected result: Successful run.
Actual result: panic: object not found

**Comment by smola** [comment]
@taralx Thank you for taking the time to report this issue.

We have no immediate plans to implement alternates, but we'll be very happy to accept PRs adding support.
