### ISSUE TITLE
V3 is not a valid version

### ISSUE THREAD

**Issue by themihai** [src-d/go-git#33]
The master branch has v3 imports but gopkg complains that there is no such version. Can someone point me to the correct way to fetch the latest version (v3)?

 go get -u -v gopkg.in/src-d/go-git.v3/core
``Fetching https://gopkg.in/src-d/go-git.v3/core?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v3/core?go-get=1 (status code 404)
package gopkg.in/src-d/go-git.v3/core: unrecognized import path "gopkg.in/src-d/go-git.v3/core" (parse https://gopkg.in/src-d/go-git.v3/core?go-get=1: no go-import meta tags)``

**Comment by mcuadros** [comment]
Since is being under development I suggest make

```sh
cd $GOPATH/gopkg.in/src-d/
git clone https://github.com/src-d/go-git.git go-git.v3
cd go-git.v3
go get -v -t ./...
go install -v ./...
```

We are tagging a new 3.x version shortly.
