### ISSUE TITLE
ssh/upload_pack_test.go accesses real repositories

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#332]
I don't have access to github.com:git-fixtures/*, so the test fails for me.

If you want this test to pass in all environments, it cannot access real repositories. It will need to spin up an ssh server and fake git server behind it. (Consider the case of developing on a disconnected machine.)

**Comment by smola** [comment]
@taralx We do plan to spin up a local SSH and Git server. Until we do, you can workaround this by setting `SSH_AUTH_SOCK=""`. SSH tests will be skipped this way.
