### ISSUE TITLE
v4: pull with rebase, create branches and tags

### ISSUE THREAD

**Issue by NaurisSadovskis** [src-d/go-git#338]
Hi guys, 

thanks for writing this! I'd like to ask if there is a way to:
* Pull it with '-r' option 
* Create branches and/or tags

Thanks again!

**Comment by smola** [comment]
* pull --rebase is currently not supported, but PRs are welcome. We might add support for it in the mid-term.
* Creating branches and lightweight tags is supported. For go-git they're just `references`. `Repository` has a `Storer`, which has `SetReference` (see: https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/storer#ReferenceStorer )

**Comment by NaurisSadovskis** [comment]
@smola thanks, got it.
