### ISSUE TITLE
Review the rationale and naming of the validate methods in options.go

### ISSUE THREAD

**Issue by alcortesm** [src-d/go-git#341]
see comments about this in https://github.com/src-d/go-git/pull/178 and https://github.com/src-d/go-git/pull/339.

**Comment by smola** [comment]
@alcortesm Feel free to explain the problem and propose any alternative API.

**Comment by mcuadros** [comment]
After [search](https://github.com/search?l=Go&p=2&q=%22Validate%28%29+error%22&type=Code&utf8=%E2%9C%93) about this, looks like is not that weird having a `Validate` function returning an error. Also I can't image other alternative better than `Validate`
