### ISSUE TITLE
SSH PublicKeys authentication requires importing two `ssh` packages

### ISSUE THREAD

**Issue by jediorange** [src-d/go-git#342]
In order to authenticate to a repo via ssh using public/private keys, one must import both the `golang.org/x/crypto/ssh` and the `gopkg.in/src-d/go-git.v4/plumbing/transport/ssh`, which are both named `ssh` by default.

```go
package main

import (
	"os"

	"golang.org/x/crypto/ssh"
	git "gopkg.in/src-d/go-git.v4"
	gitssh "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
)

func main() {
	sshPrivateKey := os.Getenv("SSH_KEY")
	signer, _ := ssh.ParsePrivateKey([]byte(sshPrivateKey))
	git.PlainClone("example", false, &git.CloneOptions{
		URL:      "ssh://github.com/example/example.git",
		Auth:     &gitssh.PublicKeys{User: "git", Signer: signer},
		Progress: os.Stdout,
	})
}
```

This necessitates renaming one of the imports, and is a bit confusing.  A more ideal situation would be to provide a function within the `git` package to create a new auth from a name/private key, such as:

```go
func NewSSHPublicKeyAuth(user string, pemPrivateKey []byte) (*PublicKeys, error)
```

An even better solution would be to include "New" auth functions (HTTP, SSH) in the main `git` package, so that sub-packages (`plumbing`) do not need to be imported for basic authentication functionality.

**Comment by icco** [comment]
This really confused me. I was really surprised 

```
	git.PlainClone("example", false, &git.CloneOptions{
		URL:      "ssh://github.com/example/example.git",
	})
```

didn't just work.

**Comment by jdoklovic** [comment]
Why not:
`Auth: ssh.NewSSHAgentAuth("git")`

**Comment by jediorange** [comment]
@jdoklovic I can't rely on a good key being installed on my server. 

That may work while running on somebody's personal machine, or on a persistent server, but when deployed to an ephemeral container, or following 12factor best practices, I can't rely on the ssh key being installed on the server.

**Comment by amendgit** [comment]
what I found in https://github.com/golang/crypto/blob/master/ssh/example_test.go
I'm not quite sure, does this need to consider the decryption.
```
        // A public key may be used to authenticate against the remote
	// server by using an unencrypted PEM-encoded private key file.
	//
	// If you have an encrypted private key, the crypto/x509 package
	// can be used to decrypt it.
	key, err := ioutil.ReadFile("/home/user/.ssh/id_rsa")
	if err != nil {
		log.Fatalf("unable to read private key: %v", err)
	}

	// Create the Signer for this private key.
	signer, err := ssh.ParsePrivateKey(key)
	if err != nil {
		log.Fatalf("unable to parse private key: %v", err)
        }
```
