### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by mcuadros** [src-d/go-git#345]
based on appveyor, many tests are falling, will be good fix this issues:
https://ci.appveyor.com/project/mcuadros/go-git

**Comment by mcarmonaa** [comment]
About those failed tests with this kind of messages:

```
*net.OpError = &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc042009e00), Addr:(*net.TCPAddr)(0xc042009e30), Err:(*os.SyscallError)(0xc0424559c0)} ("read tcp [::1]:1084->[::1]:1082: wsarecv: An existing connection was forcibly closed by the remote host.")
```

```
*net.OpError = &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc042008660), Addr:(*net.TCPAddr)(0xc042008690), Err:(*os.SyscallError)(0xc042264100)} ("write tcp [::1]:1088->[::1]:1087: wsasend: An existing connection was forcibly closed by the remote host.")
```

They aren't related to IPs (v4/v6). It seems that git for windows has issues with `git://` protocol as it said [here](https://github.com/git-for-windows/git/issues/907). I tried to set the workaround mentioned in the issue for each repository used in the tests but the fails kept there.

Other reason for the fails could be the configuration app veyor uses for its VM.

**Comment by mcuadros** [comment]
For the git protocol tests, for windows the read-only operations can be tested against GitHub.

**Comment by mcarmonaa** [comment]
@mcuadros read-only operations are already being [tested against GH](https://github.com/src-d/go-git/blob/master/plumbing/transport/git/upload_pack_test.go).

About write-operations tests, should they be just skipped in case of windows?

**Comment by mcuadros** [comment]
Yaup

**Comment by mcarmonaa** [comment]
Done in https://github.com/src-d/go-git/pull/540
