### ISSUE TITLE
Broken on submodules since .git is not a directory

### ISSUE THREAD

**Issue by mvdan** [src-d/go-git#348]
Happens with https://github.com/mvdan/git-picked, which does `git.PlainOpen(".")` and reads some info about the branches. This software works fine when the clone isn't a submodule.

But when it is...

```
 $ git-picked
open .git/objects/pack: not a directory
```

More info:

```
 $ ls -la .git
-rw-r--r-- 1 mvdan mvdan 34 Mar 27 16:58 .git
 $ cat .git
gitdir: ../.git/modules/webclient
```

**Comment by smola** [comment]
@mvdan Thanks for reporting this. We're looking into it.

**Comment by smola** [comment]
Work in progress: https://github.com/src-d/go-git/pull/363

**Comment by mvdan** [comment]
Thank you both!
