### ISSUE TITLE
go vet issues

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#349]
remote.go:44: wrong number of args for format in Sprintf call: 2 needed but 3 args
plumbing/format/packfile/scanner.go:304: method Seek(offset int64) (previous int64, err error) should have signature Seek(int64, int) (int64, error)
plumbing/format/pktline/scanner_test.go:221: Println call ends with newline
plumbing/object/change_adaptor.go:18: no formatting directive in Errorf call
plumbing/object/change_adaptor.go:22: no formatting directive in Errorf call
plumbing/object/change_adaptor.go:55: missing argument for Errorf("%s"): format reads arg 2, have only 1 args
plumbing/object/change_test.go:241: unreachable code
utils/merkletrie/difftree_test.go:123: arg c.Action in printf call is a function value, not a function call
utils/merkletrie/iter_test.go:84: arg t.operations[i] for printf verb %s of wrong type: byte
utils/merkletrie/internal/fsnoder/new.go:37: missing argument for Errorf("%c"): format reads arg 1, have only 0 args

**Comment by taralx** [comment]
(Line numbers reference v4.)

**Comment by smola** [comment]
Thanks @taralx. We're fixing this and adding go vet to CI: https://github.com/src-d/go-git/pull/360
