### ISSUE TITLE
Support Pushing Tags

### ISSUE THREAD

**Issue by ekyoung** [src-d/go-git#354]
I found a comment `// TODO: Support pushing tags.` in `remote.Push`. Any ETA on that? I might be able to help but would require some guidance on how you plan to implement that.

**Comment by smola** [comment]
I have added a test and it seems it already works: https://github.com/src-d/go-git/pull/367

**Comment by ekyoung** [comment]
So it does. Your test showed me how to use PushOptions to make it work. Thanks.
