### ISSUE TITLE
Return structs from ssh auth helpers

### ISSUE THREAD

**Issue by ekyoung** [src-d/go-git#357]
There's a type mismatch when trying to use code like the following for using the ssh auth helper functions to create `git.PushOptions`. The helpers return `ssh.AuthMethod` and PushOptions wants `transport.AuthMethod`. Is this not the way you intended to use the methods?

```go
auth, _ := ssh.NewPublicKeysFromFile("git", keyFilePath)
_ = r.Push(&git.PushOptions{Auth: auth})
```

I think the helpers should return the struct they create, not `ssh.AuthMethod` to fix this.

```go
func NewPublicKeys(user string, pemBytes []byte) (*PublicKeys, error) {
...
}

func NewPublicKeysFromFile(user string, pemFile string) (*PublicKeys, error) {
...
}

func NewSSHAgentAuth(user string) (*PublicKeysCallback, error) {
...
}
```

**Comment by mcuadros** [comment]
Now is fixed, thanks
