### ISSUE TITLE
Symlinks are checked out as regular files.

### ISSUE THREAD

**Issue by jmalloc** [src-d/go-git#358]
When attempting to clone a repository containing symlinks, the links are created as regular files directly from the object blobs - i.e, the file contents is the symlink target.

I started an attempt to implement the correct behaviour in `Worktree.checkoutEntry()` but it looks like the filesystem abstraction does not support symlink creation.

The following snippet clones a repo that demonstrates the issue.

```go
package main

import (
	"fmt"
	"os"
	"path"

	git "gopkg.in/src-d/go-git.v4"
)

func main() {
	dir := path.Join(os.TempDir(), "symlink-test")
	fmt.Println(dir)

	_, err := git.PlainClone(
		dir,
		false, // bare
		&git.CloneOptions{
			URL:      "git@github.com:recoilphp/dev.git",
			Progress: os.Stdout,
		},
	)

	if err != nil {
		panic(err)
	}
}
```

**Comment by smola** [comment]
@jmalloc Thanks for reporting this. We first have to figure out how do we want symlinks to be handled by billy, then fixing this should be easy.

**Comment by jmalloc** [comment]
:+1: I'm happy to contribute towards this with some guidance. I expect the `os` based implementation will be straight forward, but I wasn't sure how to tackle the memory implementation.

**Comment by smola** [comment]
@jmalloc Are you working on this? Feel free to create a partial PR to get further feedback, we can also help completing it.
