### ISSUE TITLE
Current master references github.com/src-d/crypto which is not publicly available

### ISSUE THREAD

**Issue by osklyar** [src-d/go-git#359]
The only change in 649de29be54e62ed40a2bc6466f2eac2884fc8f9 was to change the import from golang crypto to src-d crypto and the latter is not available in public domain. So the current master is not usable with ssh:

```
plumbing/transport/ssh/auth_method.go:12:2: cannot find package "github.com/src-d/crypto/ssh/knownhosts
```

Changing the import back to `github.com/src-d/crypto/ssh/knownhosts` fixes the issue temporarily.

**Comment by mcuadros** [comment]
I just fixed, sorry for that

**Comment by osklyar** [comment]
Thanks!
