### ISSUE TITLE
assigment count mismatch error when go get

### ISSUE THREAD

**Issue by zchee** [src-d/go-git#36]
When `go get` in current HEAD, occured assigment count mismatch error.

```bash
> go get -t -v
github.com/src-d/go-git
# github.com/src-d/go-git
./commit.go:60: assignment count mismatch: 2 = 1
./objects.go:37: undefined: core.ObjectReader
./tag.go:39: assignment count mismatch: 2 = 1
./tree.go:144: assignment count mismatch: 2 = 1
```

each `.go` file error line.

- commit.go:60
  - https://github.com/src-d/go-git/blob/master/commit.go#L60
- objects.go:37
  - https://github.com/src-d/go-git/blob/master/objects.go#L37
- tag.go:39
  - https://github.com/src-d/go-git/blob/master/tag.go#L39
- tree.go:144
  - https://github.com/src-d/go-git/blob/master/tree.go#L144

```bash
> go version
go version devel +c8579e5 Fri Feb 26 03:58:58 2016 +0000 darwin/amd64
```

**Comment by mcuadros** [comment]
You cannot use go get with the github url, you must to use `go get -u gopkg.in/src-d/go-git.v2/...`

If you really need the head then make a `git clone` on `$GOPATH/src/gopkg.in/src-d/go-git.v3`

**Comment by zchee** [comment]
@mcuadros Thanks! got it.
