### ISSUE TITLE
Is there a way to checkout a new branch, aka `git co -b dev`

### ISSUE THREAD

**Issue by osklyar** [src-d/go-git#370]
Unfortunately I was not able to work out this bit myself nor could I find an example in the code. Is there a way to checkout a new local branch (and also how do I push this new branch)?

`worktree.Checkout` takes `git.CheckoutOptions` but if the reference does not exist there seems to be no way to create it first. Alternatively, what would be the way to create a new reference and then checkout normally?

**Comment by osklyar** [comment]
Ok, got it sorted. If you are interested in examples to include I could submit one.

**Comment by devonmoss** [comment]
@osklyar How did you get this working? I am having the same problem. I would love to see an example.

**Comment by osklyar** [comment]
@devonmoss See https://github.com/silvertern/xgit/blob/master/client/gitclient.go#L131 followed by https://github.com/silvertern/xgit/blob/master/client/gitclient.go#L195 -- essentially you first check if the branch is available in refs/heads, if yes, use it, if no, check if it exists in refs/remotes, if yes, link it to local one, if no create a new ref.

**Comment by devonmoss** [comment]
Thank you. This is excellent.

**Comment by kiefersmith** [comment]
> @devonmoss See https://github.com/silvertern/xgit/blob/master/client/gitclient.go#L131 followed by https://github.com/silvertern/xgit/blob/master/client/gitclient.go#L195 -- essentially you first check if the branch is available in refs/heads, if yes, use it, if no, check if it exists in refs/remotes, if yes, link it to local one, if no create a new ref. The code is currently WIP so I cannot guarantee line numbers remain unchanged :)

These links are now dead.
