### ISSUE TITLE
References() returns forward slashes on Windows

### ISSUE THREAD

**Issue by osklyar** [src-d/go-git#372]
The following snippet 

    it, _ := repo.References()
    it.ForEach(func(ref *plumbing.Reference) error {
        fmt.Println("found: " + string(ref.Name()))
        return nil
    })

will print the following result in windows

    found: refs\heads\master
    found: refs\remotes\origin\SKOL_542_gradle_overall
    found: refs\remotes\origin\master
    found: HEAD

Is this intentional behaviour provided ?

**Comment by osklyar** [comment]
Typo in the original title: it should read "backward slashes" on windows instead of "forward" as used by all git configs

**Comment by osklyar** [comment]
The problem is most likely in `readReferenceFile` in `dotgit.go` using `d.fs.Join`. Surely at this point this join is ok to validate the existence of the reference on the file system, but passing obtained name into `NewReferenceFromStrings` causes the issue. Possibly it would be better for the latter function to swap the slashes. At least such as solution worked for me as a temporary fix.

**Comment by smola** [comment]
Work in progress to fix this: https://github.com/src-d/go-git/pull/369
In particular, this commit: https://github.com/src-d/go-git/pull/369/commits/ac19b28777457a86d6e7abb6997fe9da7172cebb

**Comment by osklyar** [comment]
Thanks Santiago!
