### ISSUE TITLE
How to use custom private key to clone through ssh? 

### ISSUE THREAD

**Issue by Mehdzor** [src-d/go-git#377]
Hi. 

I'm trying to clone a private repository using my ssh key. 
But I can't get how to provide it to go-git. 

Could you help?

**Comment by osklyar** [comment]
Leaving out error handling use the following code to read in the private key and pass the resulting object into `CloneOptions.Auth`:

    import (
      ssh2 "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
      "golang.org/x/crypto/ssh"
    )

    pem, _ := ioutil.ReadFile(pkeyfile)
    signer, _ := ssh.ParsePrivateKey(pem)
    aith := &ssh2.PublicKeys{User: gituser, Signer: signer}

**Comment by smola** [comment]
Closing this since it's a question and it's already answered by @osklyar (thank you!).
