### ISSUE TITLE
Any remote operation where ssh is involved fails on the latest version of x/crypto/ssh

### ISSUE THREAD

**Issue by gigaroby** [src-d/go-git#379]
Due to [this breaking change](https://github.com/golang/go/issues/19767) any operation which uses ssh is destined to fail with this error `ssh: must specify HostKeyCallback`.

The fix to restore functionality as before is to add `HostKeyCallback: ssh.InsecureIgnoreHostKey(),` to all instances of `ssh.ClientConfig` in `plumbing/transport/ssh/auth_method.go`.
It would also be cool if there was a way to specify the callback directly, perhaps by providing a way to specify `ssh.ClientConfig` directly?
This affect all projects that aren't vendoring dependencies and download the latest version of `x/crypto/ssh`.

If you would like me to submit the fix as a PR just say the word.

**Comment by bronzdoc** [comment]
I think this is already fixed with https://github.com/src-d/go-git/pull/346 just not released.

I'm using glide, so i got around it by specifying a `ref` without the breaking change of crypto/ssh in my `glide.yml`

```
- package: golang.org/x/crypto
  ref: 459e26527287adbc2adcc5d0d49abff9a5f315a7
  subpackages:
  - ssh
```

**Comment by gigaroby** [comment]
Yeah, you're right, I forgot to look through closed issues and PR.
Thanks, will close this
