### ISSUE TITLE
Add support for ref storage

### ISSUE THREAD

**Issue by JoshuaSjoding** [src-d/go-git#38]
The current implementation of `Repository` doesn't provide a way to persist branch, remote, and tag references to storage. I've been thinking about the best way to do this, and here is my proposal:

1. Add a `core.RefStorage` interface with the necessary methods (the interface should be fairly simple)
2. Add a `core.Storage` struct that composes both `ObjectStorage` and `RefStorage`
3. Add a `memory.RefStorage` struct that implements `core.RefStorage`, along with a `memory.NewRefStorage` function
4. Add a `memory.NewStorage` function
5. Modify `Repository` to include a `core.Storage` interface instead of `core.ObjectStorage`

The definition of `core.Storage` would be something like this:

```
type Storage struct {
	Object ObjectStorage
	Ref    RefStorage
}
```

If this approach seems reasonable, I'll go ahead and put together a pull request.

**Comment by mcuadros** [comment]
The references are something relative to the remote so the tags and branches can be retrieved from the `Remote` object: https://godoc.org/gopkg.in/src-d/go-git.v2#Remote.Ref

Do you thing that this is not enough?

**Comment by JoshuaSjoding** [comment]
It's true that we can always ask the remote server for its refs via the fetch protocol, but right now we don't know what refs already exist locally because none of that information can be saved through the storage API.

For example, knowing what commit the local `refs/heads/master` was at the last time we pulled would let us ask the server for the diff later by specifying what we already have. As it is right now I think we have to pull the entire remote branch every time, even if we already have 95% of the remote's objects already in local storage.

Personally, I would like the `filesystem` storage implementation to read and write to `.git/refs`, with support at least for `heads` and probably `tags` too. This would let me use `go-git` to update existing repositories efficiently and drop lightweight tags with the pull date, for example.

The traditional `git` implementation also keeps track of the remote refs and stores them in `.git/refs/remotes`. I'm not entirely sure of the benefit and I agree that it's less important, but I'd be tempted to implement that as well just for feature parity.

**Comment by mcuadros** [comment]
I see, the problem. Then we need to implement a new `GitUploadPackService` base on FileSystem and adding it as remote (the local one), instead of create a new Type. What do you thing?

**Comment by mcuadros** [comment]
@JoshuaSjoding we ended implementing a `ReferenceStorage` you were right is the correct approach, my previous approach was a bad idea. We have a lot of work going on in the `v4` branch
