### ISSUE TITLE
Cannot clone using private key

### ISSUE THREAD

**Issue by GrimTheReaper** [src-d/go-git#385]
``` go
pem, _ := ioutil.ReadFile("...")
signer, err := ssh.ParsePrivateKey(pem)
if err != nil {
    panic(
}
auth := &ssh2.PublicKeys{User: "git", Signer: signer}
storage := memory.NewStorage()
repo, err := git.Clone(
	storage,
	nil,
	&git.CloneOptions{
		URL:  "git@github.com:...../......git",
		Auth: auth,
	},
)
```

I get `ssh: must specify HostKeyCallback`.    
Problem seems to be mentioned here: https://github.com/golang/go/issues/19767.
Mimicking https://github.com/pkg/sftp/pull/179 seems to resolve this for me, so I may open a PR unless someone has a better idea.

**Comment by osklyar** [comment]
Have you checked this with the latest master branch (how to see #380) as must have been fixed recently in #379?

**Comment by GrimTheReaper** [comment]
@osklyar I have not, let me go and try that.

**Comment by smola** [comment]
@GrimTheReaper I'm closing this. We'll release a new rc10 soon and freeze the API for backwards-compatibility changes.

**Comment by GrimTheReaper** [comment]
@smola whoops, I thought I did close it >_<
