### ISSUE TITLE
How to work with master branch

### ISSUE THREAD

**Issue by gonzaloserrano** [src-d/go-git#386]
Hi there,

I'm writing a little CLI tool to switch branches using go-git. I want to use the master version and use the `worktree.Checkout(opts)` feature, but I have some things I'm not understanding:

- why master import paths refer to `gopkg.in/src-d/go-git.v4` instead of `github.com/src-d/go-git`?
- then, in master, when trying to compile https://github.com/src-d/go-git/blob/master/_examples/checkout/main.go, it gives me a `./main.go:36: undefined: git.CheckoutOptions`.

Note that i `go get`ed both v4 and master versions and have both in my GOPATH.

Thanks a lot and congrats for this awesome lib.

**Comment by osklyar** [comment]
See #380, your problem is essentially the same. Clone `master` into `$GOPATH/gopgk.in/src-d/go-git.v4` and it will compile or use a dependency manager to pull sources for `gopgk.in/src-d/go-git.v4` from the master branch into `vendor`.
