### ISSUE TITLE
PlainClone not fully populating tree on Windows

### ISSUE THREAD

**Issue by SlowPokeInTexas** [src-d/go-git#389]
I acknowledge that it's entirely possible (highly likely even) that I'm doing something wrong, but it's not immediately obvious to me what it is.  I'm trying to use PlainClone and I'm getting the initial .git files for the repository but not the actual source.  I'm either getting a 'repository already exists' or a 'reference not found' error. I'd appreciate any feedback on what I'm doing wrong. 

I'm using go-git.V4 on Go 1.8

```
_, err := git.PlainClone("d:/localsrc", false, &git.CloneOptions{
		URL: "https://ourstash.scm.ourlibrary.git",
		RemoteName: "develop",  //tried commenting this out to no avial
		Depth : 9999999,
		SingleBranch: true,  //setting this to true results in 'repository already exists' error, setting this to false results in 'reference not found' error
		RecurseSubmodules: 9999999,
})

```

**Comment by smola** [comment]
@SlowPokeInTexas Does your repository contain symlinks or submodules? There are some known problems with file handling on Windows, see https://github.com/src-d/go-git/labels/windows

We'll look into this.

**Comment by mcuadros** [comment]
@SlowPokeInTexas any updated about this? Can you try with the last version?

**Comment by mcuadros** [comment]
If still happens please reopen the issue.
