### ISSUE TITLE
Pushing Tags Takes Many Minutes

### ISSUE THREAD

**Issue by ekyoung** [src-d/go-git#390]
Pushing tags to a remote takes about 15 minutes in one repository I'm working with. Using `git push --tags` on the same repo only takes a second or two.

The code I'm using is similar to the below.

```go
rs := config.RefSpec("/refs/tags/v1.0.0:/refs/tags/v1.0.0")
err := rmt.Push(&git.PushOptions{
	RefSpecs: []config.RefSpec{rs},
})
```

The time seems to be taken in lot of loops through `func (dw *deltaSelector) tryToDeltify(base, target *ObjectToPack) error` going over blobs.

**Comment by smola** [comment]
@ekyoung Thanks for the report. There are some performance problems when generating packfiles. We're looking into th is. For this case, we have to check if we're trying to send more objects than needed to the server, which would be aggravating the problem.

We'll look into this.

**Comment by ekyoung** [comment]
Now takes about 1 minute on the repo I'm working with instead of 15. A big improvement. Thank you.

**Comment by smola** [comment]
@ekyoung I'm glad it helped. There still some upcoming improvements that will make this faster.
