### ISSUE TITLE
Update v4?

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#391]
I'm waiting for my two PRs to get integrated into v4 -- any sign of a merge soon?

**Comment by jbcpollak** [comment]
I would really like to use the `Log` interface but it isn't available in the version retrieved with `go get gopkg.in/src-d/go-git.v4`, so an update would be great.

Is there a workaround in the meantime? When I try `go get github.com/src-d/go-git` I get an error that the code expects `go-git.v4` as the page name, so I'm not sure how to work with the source directly.

**Comment by smola** [comment]
We're releasing a new RC soon. If you want to use master, please, do a `git checkout` manually or use a vendoring tool.

**Comment by smola** [comment]
@taralx v4.0.0-rc10 is out: https://github.com/src-d/go-git/releases/tag/v4.0.0-rc10
