### ISSUE TITLE
Adding SSH ciphers when connecting

### ISSUE THREAD

**Issue by Urethramancer** [src-d/go-git#393]
Is there a built-in way to expand the range of ciphers used when connecting to a repository? I'm trying to clone Visual Studio Team Services repos via a tool I'm making (internal tool for private company repos(, and it turns out the SSH support from MS looks a bit fake.

When running PlainClone() after setting up auth via SSH key I get this error:
`ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc aes192-cbc aes128-cbc]`

It looks to me like the plumbing section reimplements a bit of the ssh package, and to expand it I have to re-reimplement part of it, but I was hoping there was a better way :)

**Comment by smola** [comment]
@Urethramancer Thanks for reporting this! We'll look into it.

Note that even if this bug is fixed, it is unlikely that go-git currently works with VSTS, since they do not support the basic git protocol (_no multi-ack_) and we currently have support only for it. See this issue for more info: https://github.com/src-d/go-git/issues/335

**Comment by Urethramancer** [comment]
Thanks, I missed that issue in my search. Looks like I'll do a hacky workaround just for VSTS then in my little project :)

**Comment by smola** [comment]
I've created a PR to be able to pass options to the SSH transport: https://github.com/src-d/go-git/pull/423
This should make possible to enable `aes128-cbc` in `ClientConfig.Ciphers`. See: https://godoc.org/golang.org/x/crypto/ssh#Config

**Comment by mcuadros** [comment]
Fixed by #423
