### ISSUE TITLE
Export parents of commit

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#402]
There's a perfectly good `parents []plumbing.Hash` in the Commit object, but it can't be accessed. Instead, one has to force a storage lookup of each parent to get the hashes from the resulting objects.

Please can we just export the hashes? It's useful for topological sort, where you don't want to waste time looking up things you've already seen.

**Comment by mcuadros** [comment]
https://github.com/src-d/go-git/blob/master/plumbing/object/commit.go#L36

This already changed in the master
