### ISSUE TITLE
Traverse in Memory File System

### ISSUE THREAD

**Issue by vermapratyush** [src-d/go-git#403]
Hi,
I have cloned a git hub repo using memory storage. 
```
git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
	URL:         repoUrl,
	Progress: os.Stdout,
})
```
Within this in-memory storage, I want to traverse/iterate through all the files, and store the file contents along with file path (file path + file name) in a golang map.
```
golang map -> map[string]string

contents:
"file1": "content of file 1"
"file2": "content of file 2"
"dir1/file1": "content of file 1 within dir1"
"dir1/file2": "content of file 2 within dir1"
"dir3/file1": "content of file 1 within dir3"
```
I don't see a predictable way of extracting the the blobs (file + dir) from the memory file system.
If I use `BlobObjects()` or `TreeObjects()`, it returns a list of files and dir in no specific order, constructing a flat structure from this will be immensely difficult.

Also, Given a file at some random Tree, is it possible to get the complete file path?

Any suggestion on how can I generate the above mentioned map.

**Comment by ajnavarro** [comment]
Hi @vermapratyush

What do you want to do exactly, iterate all files in a specific commit, or all the files in a repository? If you want to iterate all the file versions into a repository, you cannot use the file+path as a key of your map, because you will have several versions of the same file.

If what you want is iterate all the files in a specific commit, you can do something like this:
```go
func main() {
	r, err := git.PlainClone("test", false, &git.CloneOptions{
		URL: "https://github.com/src-d/go-git.git",
	})

	CheckIfError(err)

	// ... retrieving the branch being pointed by HEAD
	ref, err := r.Head()
	CheckIfError(err)
	// ... retrieving the commit object
	commit, err := r.CommitObject(ref.Hash())
	CheckIfError(err)

	fIter, err := commit.Files()
	CheckIfError(err)

	fIter.ForEach(func(f *object.File) error {
		// TODO add to your map here
		fmt.Println(f.Name) // path + name
		c, err := f.Contents() // content
		CheckIfError(err)
		fmt.Println(strings.SplitAfter(c,"\n")[0])
		return nil
	})
}
```

**Comment by vermapratyush** [comment]
Ah, I thought a commit object will only contain the files which were modified in that particular commit.

Thanks a lot. :)
