### ISSUE TITLE
Build errors due to missing files in 4.0.0-X releases

### ISSUE THREAD

**Issue by ruediger-maass** [src-d/go-git#410]
Hi, I tried to use one of the 4.0.0-RCx releases (before go v1.8, since I am not yet there) with glide. Trying version v4.0.0-rc9 
```
- package: gopkg.in/src-d/go-git.v4
  version: v4.0.0-rc9
```
results in errors due to missing dirs/files:
- plumbing/filemode 
- plumbing/cache
- plumbing/format/diff

Looking at  https://github.com/src-d/go-git/tree/v4.0.0-rc9 seems to confirm this. What am I doing wrong - or are the releases incompletely tagged? 

@matthiaskubik: fyi

**Comment by smola** [comment]
@ruediger-maass is it possible that, somehow, you have a mixed checkout of v4.0.0-rc9 and v4.0.0-rc10 on your `vendor` directory? Both v4.0.0-rc9 and v4.0.0-rc10 are full releases, no missing files.

All packages you meantion are new from v4.0.0-rc10 and did not exist in v4.0.0-rc10.

**Comment by smola** [comment]
Closing issue, since this seems an external problem related to how vendor/imports were setup in your project.
@ruediger-maass Please, reopen if that is not the case.

**Comment by ruediger-maass** [comment]
@smola - thanks your response! Have you checked your own link https://github.com/src-d/go-git/tree/v4.0.0-rc9? These are the files I get when I clone rc9, for example, and this file set is not complete and causes build errors, as mentioned above. Btw, cloning releases from your earlier gopkg.in/src-d/go-git.v3 works without problems, using the same environment (just for info, I cannot respond during the next 10 days due to vacation). Thanks for your help!

**Comment by ruediger-maass** [comment]
@smola : FYI, your comment about the dir's helped me to find the problem I ran into (see rc8 and rc9 below) - here's a list of the rc's - especially rc8 and rc9, explain the problem I ran into:
```
rc10: builds (with go v1.8) ok for me - you switched back to gopkg.in/src-d/go-git.v4 import path
rc9: you switched to srcd.works/go-git.v4 import path - I still used gopkg.in/src-d/go-git.v4 
     in the code and with glide - this broke my neck and caused the symptoms I reported above,
     changing glide and code imports to srcd.works/go-git.v4 also did not work for me (couldn't set 
     the version for this repo path)
rc8: same as rc9 
- older rc's use gopkg.in/src-d/go-git.v4 (I know it's history, but I wanted to know :-)
rc7: I get [ERROR]	Error scanning srcd.works/go-billy.v1/os: open /home/vagrant/.glide/cache/src/https-srcd.works-go-billy.v1/os
rc6: same as rc7
rc5: ok, no build errors
rc4: ok, no build errors
...ok, stop now...
```
