### ISSUE TITLE
ForEach operations should allow passing a context object

### ISSUE THREAD

**Issue by ivucica** [src-d/go-git#416]
I'm using go-git to match commits in two disparate Git repositories based on `git-svn-id`.

To do this, I'm opening a repo, iterating over commits on its master branch, and generating a `map[SubversionRevision]*GitMatch` in variable `matches`. Individual match in this map contains the old hash, the new hash and the Subversion revision.

After invoking the function to store the current commit `matchOld` (or `matchNew`), I perform a `.ForEach` over the `commit.Parents()` and thus recursively invoke the store function for the parent commits. At this point I would like to also pass in the `matches` structure to the `matchOld` function.

Since passing a context argument (whether `*context.Context` or `interface{}`) is not possible, I have two options:

- have a global variable, making it impossible to invoke the matcher code concurrently
- abuse closures and nest `matchOld` and `matchNew` (this is what I went with)

While I should rework the code to use channels for queues and worker goroutines in place of recursion, there can be other legitimate uses for passing a context argument to functions passed into `.ForEach`. Please consider allowing this. Use of `*context.Context` would, of course, be excellent: it would also allow simple early cancellation of lengthy operations.

**Comment by smola** [comment]
@ivucica Note that calling Repository/Storer methods concurrently might not be safe. Git does implement a repository lock, we don't do that yet, but it is likely that we will in the future.

Passing a context to `ForEach`, which is just a convenience wraper of `Next` seems overcomplicating the API. You should be able to implement your use case either storing state outside the `ForEach` call (as we do in the go-git code base itself).

As you indicate, if you want to parallelize some processing,  you should parallelize the processing and not reading from the repository (e.g. using a single producer to get the commits and multiple consumers for your processing).

 @mcuadros Do you have any opinion on this?

**Comment by ivucica** [comment]
Since opening this issue, I've published my code so [I can now reference it](https://github.com/ivucica/gitsvn-scripts/blob/0895dffd8bbc539690cb10ecd64f623c6740b2e2/cmd/gs-svn-import/matcher.go). It's very hacky, but as it's intended to allow one-time svn->git conversion, that's fine by me.

Further reflecting on this, I think you are right; the need for passing extra context variables is minimal. This can probably be closed.

**Comment by smola** [comment]
@ivucica Thanks for the reference code.
Closing the issue.
