### ISSUE TITLE
use v2 and determine file mode

### ISSUE THREAD

**Issue by vtolstov** [src-d/go-git#42]
I'm use tree = commit.Tree()  ; tree.Files() to get files, but how can i get file mode for each file from Files?

**Comment by mcuadros** [comment]
Uh! Oh... we don't recover the file mode, we lack of this feature. We will try to make it in a near future. Or if you want to contribute you are more than welcome to make a PR

**Comment by vtolstov** [comment]
Can you share me info - what files i need to read, to understand what i need to know to write this feature ?=) I'm rely need it, because i have execute files and need to run it, but not all.

**Comment by mcuadros** [comment]
@vtolstov in the v2 the filemode can only be retrieved from the [TreeEntry](https://godoc.org/gopkg.in/src-d/go-git.v2#TreeEntry) object, but in the new v3 (stable, now) you can retrieve it from the [File](https://godoc.org/gopkg.in/src-d/go-git.v3#File) object.

**Comment by vtolstov** [comment]
Thanks!
