### ISSUE TITLE
Refs not updated when NoErrAlreadyUpToDate

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#425]
When fetching, if the remote ref is already available, the local ref is not updated per the refspec.

**Comment by smola** [comment]
@taralx Could you elaborate more about the issue? If `NoErrAlreadyUpToDate` is returned it's because there is no reference to update.
Could you add which version of go-git are you using?

**Comment by taralx** [comment]
Version: v4.0.0rc10

Basically, do a Fetch("+refs/heads/*:refs/heads/*") and then change one of the refs to its parent. If you do Fetch again, it will not update the ref because getWants returns nothing because the object is already present.
