### ISSUE TITLE
Split network and local parts of Fetch()

### ISSUE THREAD

**Issue by taralx** [src-d/go-git#426]
So the current version of fetch is very much concerned with replicating ordinary "git fetch" with refspecs, etc. However, this doesn't support other useful cases like unadvertised refs or retrieving to FETCH_HEAD.

I think it would be helpful to split fetch into two parts -- one that is exclusively about accessing a remote (e.g. git fetch $REMOTE $REF and git ls-remote $REMOTE) and the other that is about updating the local repo using the first part.

I'm tinkering with some solutions, so maybe I'll have something in a few weeks.

**Comment by smola** [comment]
* If you want to fetch all refs, you can use the following refspec `refs/*:refs/*`. This will fetch GitHub PullRequests (`refs/pull/<pr#>`) in GitHub for example.
* If you want to fetch `master` to `FETCH_HEAD`, you can use the following refspec `refs/heads/master:FETCH_HEAD`. Although we could replicate git behaviour with FETCH_HEAD here.
* A ls-remote equivalent would definitely be useful. It is currently possible to do it using the `plumbing/transport` low-level API at the moment, but exposing higher-level API woulld be nice.

**Comment by taralx** [comment]
That's helpful. Although I'd prefer an API that allowed me to retrieve a ref without recording it, or allowed me to select a set of refs to retrieve using a function.

I also have use for unadvertised refs, which I believe cannot be done with the current API.

**Comment by smola** [comment]
@taralx What's an unadvertised reference? Those not in `refs/heads` and `refs/tags`? If that's the case you can retrieve all of them with what I said in point one.

If you want to replicate `ls-remote`, you can use the following:

```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/src-d/go-git.v4/plumbing"
	"gopkg.in/src-d/go-git.v4/plumbing/transport"
	"gopkg.in/src-d/go-git.v4/plumbing/transport/client"
)

func main() {
	repoUrl := os.Args[1]
	ep, err := transport.NewEndpoint(repoUrl)
	checkError(err)

	client := client.Protocols[ep.Protocol()]
	session, err := client.NewUploadPackSession(ep, nil)
	checkError(err)

	ar, err := session.AdvertisedReferences()
	checkError(err)

	refs, err := ar.AllReferences()
	checkError(err)

	iter, err := refs.IterReferences()
	checkError(err)

	err = iter.ForEach(func(ref *plumbing.Reference) error {
		fmt.Println(ref.String())
		return nil
	})
	checkError(err)

	err = session.Close()
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}
```

Example run:

```
$ go run test.go https://github.com/src-d/go-git.git
17eeef0f3dbd24d26a36810b8dc39222445fbf0a refs/pull/148/head
65416cf6c0e8264cc7938fe0611998d52780e089 refs/pull/388/head
9e8f1cfde0e4fd6e4893ca53dea3145fe0182800 refs/pull/361/head
643f3fc0da3aea1047617d68fe232c6b8ec4756e refs/pull/146/head
e03a5503cc012b4f737a8215c2da1a5c39b4b9a8 refs/pull/383/merge
[...]
```

It's definitely not the best thing, but it can probably solve your problem at the moment.

**Comment by taralx** [comment]
Unadvertised references are usually an explicit SHA1. Usually used with a depth limit to avoid retrieving the entire repository, so refs/* won't satisfy.

Thanks for the example code, it looks a lot like what I've been writing.

**Comment by smola** [comment]
@taralx Could you add an example of the equivalent functionality in git itself? It would be helpful if it can be expressed as a sequence of git commands. Thanks!

**Comment by taralx** [comment]
```shell
git clone --depth=1 -b nougat-dev https://android.googlesource.com/platform/build
cd build
git fetch --depth=1 origin 3ce06ee405f5b37841f8d9f841e5f25621c84a4f
git cat-file -p 3ce06ee405f5b37841f8d9f841e5f25621c84a4f
```

**Comment by taralx** [comment]
Worth noting that that is not an advertised ref:

```shell
git ls-remote origin | grep 3ce06ee
```

**Comment by mcuadros** [comment]
This kind operations can be done using plumbing, I don't thing worth to having in the main package. But I am open suggestions about this posible interface.
