### ISSUE TITLE
checkout symlink

### ISSUE THREAD

**Issue by vtolstov** [src-d/go-git#43]
How can i checkout symlink? Does it target name can be get via objectreader (blob contents)?

**Comment by mcuadros** [comment]
Just check the L flag in the [os.Mode](https://golang.org/pkg/os/?m=all#FileMode), the target of link is the content of the file.

**Comment by vtolstov** [comment]
But how can I create link to not exiting file? I'm try but OS.symlink says
that DST not exists, in Linux I can create link to any DST,how to create
such link in go?
Thanks
23 Апр 2016 г. 17:01 пользователь "Máximo Cuadros" <notifications@github.com>
написал:
