### ISSUE TITLE
work with branch?

### ISSUE THREAD

**Issue by snail007** [src-d/go-git#431]
I search all of api,can not find how to delete and create a branch?

**Comment by smola** [comment]
@snail007 go-git currently favors using branches as references directly (e.g. `master` branch is `refs/heads/master` reference).
* You can list them with `Repository.References(): https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.References
* You can add and delete them with `Repository.Storer.SetReference` and `Repository.Storer.RemoveReference`.

**Comment by snail007** [comment]
thx！
