### ISSUE TITLE
get last commit from remote repo

### ISSUE THREAD

**Issue by vtolstov** [src-d/go-git#44]
How can i get last commit from remote repo? as i see repository commitIter does not sort commits....

**Comment by mcuadros** [comment]
You must to start reading from the commit from the branch you want, you can get the references calling:
https://godoc.org/gopkg.in/src-d/go-git.v3#Remote.Refs.

I am keeping this issue open with the goal of create an example.

**Comment by mcuadros** [comment]
Here you can find a example:
https://github.com/src-d/go-git/blob/master/examples/latest/latest.go

I just added a few methods to make the life easier to the user:
https://godoc.org/gopkg.in/src-d/go-git.v3#Repository.PullDefault
https://godoc.org/gopkg.in/src-d/go-git.v3#Remote.Head

**Comment by vtolstov** [comment]
Thanks!
