### ISSUE TITLE
capabilities parsing fails when non-standard capability is found (was: Cloning from github broken?)

### ISSUE THREAD

**Issue by chrisdostert** [src-d/go-git#450]
cloning any github repo just started erroring out with the following message:
`pkt-line 3: invalid capabilities: unknown capability (multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed early-capabilities no-done symref=HEAD:refs/heads/master agent=git/github-g3daa19f21)`

**Comment by smola** [comment]
@chrisdostert Yes, I've just spotted it too. They deployed a new custom version of the server advertising a non-standard capability. I'm currently working on a fix, I hope I can push it ASAP.

**Comment by smola** [comment]
I created a PR with a fix https://github.com/src-d/go-git/pull/451

Anyway, it seems they have updated their server again (to version `agent=git/github-g4cf2b3a18`) and they are not using this `early-capabilities` anymore. So it should be working now without any change on our side.

**Comment by chrisdostert** [comment]
@smola that's great to hear; confirmed it's working again w/out code changes. 

Now that it's not urgent, do you still recommend pulling in the updated behavior? I'm concerned they may again introduce the breaking behavior at some point.

**Comment by smola** [comment]
@chrisdostert Yes. I think we should be prepared for anyone using non-standard capabilitiues, or even new standard capabilities that are not supported by go-git yet. So we'll fix this. However, since it's currently working with GitHub, I will not rush this and follow the usual code review cycle on the PR.
