### ISSUE TITLE
git push new branch with depth=1

### ISSUE THREAD

**Issue by joshbetz** [src-d/go-git#455]
Pushing a new branch after cloning with depth=1 doesn't seem to work. I get `object not found`. The problem seems to be in `revlist.Object()` -- at least that's where the error happens. As best I can tell, I think it's trying to verify too much of the tree. This same thing works with git:

```
git clone --depth 1 <repo>
git checkout -b new-branch
touch file
git add file
git commit -m "add test file"
git push
```

**Comment by jucardi** [comment]
How are you doing the `checkout -b` ?

**Comment by smola** [comment]
@joshbetz Thank you for reporting this. We'll look into it.

**Comment by joshbetz** [comment]
@smola Thank you! Let me know if you have any questions about reproducing the issue I'm having. I tried debugging it for a while, but couldn't quite follow the logic in `remote.Push()`.

**Comment by dirkaholic** [comment]
Hi there, 

experiencing the same issue. When going into the respective directory and doing the git push manually using the normal Linux git client afterwards it works. It's the same with another depth used during the clone (tried 2 or 3). So I removed Depth option from the clone command but now the clone command needs a lot more time (which is expected) but also the push after just changing a single file is running veeery long.

**Comment by mcuadros** [comment]
@joshbetz how are you doing the `git checkout -b`?

**Comment by joshbetz** [comment]
```
	// local is a *git.Repository
	// Create tmp branch
	ref, err := local.Head()
	new := plumbing.NewReferenceFromStrings("refs/heads/branch-name", ref.Hash().String())
	err = local.Storer.SetReference(new)
	if err != nil {
		return err
	}

	err = w.Checkout(&git.CheckoutOptions{Branch: plumbing.ReferenceName("refs/heads/branch-name")})
	if err != nil {
		return err
	}
```

**Comment by dirkaholic** [comment]
Thanks for fixing the issue. What do you think when it can be pushed to the v4 branch ?

**Comment by mvpmvh** [comment]
was this actually fixed? i'm getting the same issue when doing a shallow fetch, followed by a push.
The push fails with the same `unpack error: error Missing unknown <commit_sha>` 

go-git version `gopkg.in/src-d/go-git.v4 v4.13.1`
