### ISSUE TITLE
add support for directories on git add (was: git add . doesn't seem to work)

### ISSUE THREAD

**Issue by jucardi** [src-d/go-git#456]
I'm trying to add all contents in a cloned repo. Normally I would do this with the command line by doing a
```
git add .
```

I'm trying to do it by running

```go
if _,err = workTree.Add("."); err != nil {
```

But that actually returns an error saying

```
read [path]: is a directory
```

Do I need to add file by file by hand?

**Comment by mcuadros** [comment]
[Worktree.Add](https://godoc.org/gopkg.in/src-d/go-git.v4#Worktree.Add) only works with files, directories are not handled, but PRs are welcome.

**Comment by jucardi** [comment]
@mcuadros sounds good, thanks for your help, I'll submit directory a PR with directory support sometime next week.

**Comment by halfcrazy** [comment]
@jucardi What's the current status of your PR?

**Comment by joshbetz** [comment]
I've been doing this, but it's pretty slow.

```
	status, err := worktree.Status()
	if err != nil {
		return err
	}

	if status.IsClean() {
		return nil
	}

	for path, _ := range status {
		w.Add(path)
	}
```

**Comment by Labutin** [comment]
Yes, it really TOO slow.
I need to commit about 500 updated files and calling worktree.Add(path) for all files takes more than 3 minutes :(
Using CommitOptions.All doing the same loop over all modified files and works the same slow.
Any ideas how to commit 500 updated files faster?

**Comment by mcuadros** [comment]
The complexity of the `Add` is almost trivial, the time consumed is on doing the hashing. How big are the files? How many time takes on git command, @Labutin?

**Comment by Labutin** [comment]
I have about 500 modified files. Each file about 22KB size. Not so big.
```
dlabutin@dlabutin-mbp $ git status| wc
     529    1085   26114
dlabutin@dlabutin-mbp $ time git add .
real	0m0.092s
user	0m0.041s
sys	0m0.046s
```

Console `git add .` takes less than 0.1 sec.
But
```
	if _, err := w.Commit("Commin message", &git.CommitOptions{
		All: true,
		Author: &object.Signature{
			Name: "octopus",
			Email: "octopus@server",
			When: time.Now(),
		},
	}); err != nil {
		return err
	}

```
works about 3 minutes.
I am testing on Macbook Pro (SSD drive).

**Comment by Labutin** [comment]
Looks like problem is here: https://github.com/src-d/go-git/blob/master/worktree_status.go#L248

Calling `s, err := w.Status()` for every added file takes many time :(

**Comment by Labutin** [comment]
I tried to use dirty hack and cache Worktree status inside Add. No adding 500 files take about 20 seconds. Not so fast as console command. But much better than 3 minutes.

**Comment by mcuadros** [comment]
git client is always multi-threads go-git, itsn't it.

**Comment by Labutin** [comment]
Even is git client is multi-threaded I don't think it reread working tree status for every added file.

**Comment by joshbetz** [comment]
@Labutin Maybe you can send a PR with your changes? A 9x performance improvement sounds pretty good to me :)
