### ISSUE TITLE
Git status silently fails in a repository with no commits.

### ISSUE THREAD

**Issue by JarrahGos** [src-d/go-git#459]
When running the following code on a repository with no commits but staged or untracked content status.IsClean() return true and status.String() returns an empty string. (error checking done, but excluded from example)
```golang
status, err := wt.Status()
fmt.Println(status.IsClean())
```
Normal git functionality is to return the following:
```ShellSession
user@work(master|●1…)> git status                                                          
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   name.tex

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	file
	mothen
	name.pdf
	name.txt
	one.tex
	second
	tags
	three.tex
	two.tex
	unclean

user@work(master|●1…)> git l 
fatal: your current branch 'master' does not have any commits yet
user@work(master|●1…)>
```

**Comment by smola** [comment]
@JarrahGos Thank you for reporting this. We will look into the issue.

**Comment by ganesh-sadanala** [comment]
I am facing the same issue with Git Bash

Today i have initialized git using `git init`
and checked status using `git status`

It is showing No commits yet instead of Initial commit

**Comment by smola** [comment]
@ganesh-sadanala That's git expected behavior. `git init` does not create any commit. Anyway, this repository is about `go-git`, not `git` itself.

**Comment by surabhi24** [comment]
> I am facing the same issue with Git Bash
> 
> Today i have initialized git using `git init`
> and checked status using `git status`
> 
> It is showing No commits yet instead of Initial commit

I am facing this issue too.

**Comment by aimei26** [comment]
after add comment I face some issue just now 
do the following:
1. git commit -m"First commit"
2. git log

**Comment by shravari** [comment]
even i am facing this issue what is to be done?
