### ISSUE TITLE
Reference not found when trying to clone not default branch

### ISSUE THREAD

**Issue by se0wtf** [src-d/go-git#460]
Hello,
Everything is OK when i clone the default "master" branch but not working with another branch.

This is the code i'm using : 
```
r, err := git.PlainClone(tmpGitDir, false, &git.CloneOptions{
	URL:           url,
	Progress:      os.Stdout,
	Auth:          httpAuth,
	ReferenceName: "recsep",
	SingleBranch:  true,
})
```
I'm trying to clone the "recsep" branch (which exists on git).

The result i get : 
```
Counting objects: 26, done.
Compressing objects: 100% (17/17), done.
Total 26 (delta 6), reused 22 (delta 5)
error: reference not found
```

If i try it directly with git, it's working well : 
```
$ git clone -b recsep --single-branch https://user@gitlab/test.git
Clonage dans 'test'...
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 25 (delta 5), reused 25 (delta 5)
Dépaquetage des objets: 100% (25/25), fait.
Vérification de la connectivité... fait.
```

Am I doing something wrong ?
Let me know if you want more test.

Thanks,

**Comment by smola** [comment]
@se0wtf The reference for the `recsep` branch is actually `refs/heads/recsep`. You can read more about references here: https://git-scm.com/book/en/v2/Git-Internals-Git-References

You can check them in a local repository with `git show-ref`.

**Comment by se0wtf** [comment]
Thanks ;)
