### ISSUE TITLE
Getting log for specific file (question)

### ISSUE THREAD

**Issue by dorsha** [src-d/go-git#468]
Is there a way to get log for specific file?
I managed to get log for the entire repo and from specific hash, but didn't find a way to do this for a file.

The use case is to get and display the history of a file.
If not supported, workarounds are welcome :)

**Comment by ajnavarro** [comment]
You can do this using [git blame](https://git-scm.com/docs/git-blame)

Here is the implementation into go-git: [Blame](http://godoc.org/gopkg.in/src-d/go-git.v4#Blame)

**Comment by dorsha** [comment]
Thanks, I managed to achieve this with the following (will check blame as well):

```go

gr, err := git.PlainOpen(repoPath)
if err != nil {
    log.WithError(err).Errorf("Version Control - Failed to open repo: %s", path)
    return err
}

res, err := gr.CommitObjects()
if err != nil {
    log.WithError(err).Error("Version Control - failed getting all commit objects")
    return err
}

history := []*object.Commit{}

res.ForEach(func(c *object.Commit) error {
    if _, err := c.File(filename); err == nil {
        history = append(history, c)
    }
    return nil
})

```

**Comment by ajnavarro** [comment]
Yep, I misunderstood your question, the actual way to do this is: 
```go
package main

import (
	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/plumbing/object"
)

func main() {
	// Opens an already existant repository.
	r, err := git.PlainOpen("/path/to/your/repository")
	filename := "status.go"
	CheckIfError(err)

	cIter, err := r.CommitObjects()
	CheckIfError(err)

	var commits []*object.Commit
	err = cIter.ForEach(func(c *object.Commit) error {
		cTree, err := c.Tree()
		if err != nil {
			return err
		}
		err = c.Parents().ForEach(func(p *object.Commit) error {
			pTree, err := p.Tree()
			if err != nil {
				return err
			}

			changes, err := pTree.Diff(cTree)
			if err != nil {
				return err
			}

			for _, change := range changes {
				if change.From.Name == filename ||
					change.To.Name == filename {
					commits = append(commits, c)
					return nil
				}
			}

			return nil
		})

		return nil
	})

	Info("status.go history")
	for _, c := range commits {
		Info(c.Message)
		Info("------------------------")
	}
}

```

**Comment by dorsha** [comment]
Thanks!

**Comment by dorsha** [comment]
@ajnavarro / @robfig is there a better and efficient way to achieve the above? (get log for specific file)

Going over the entire repo history is a navie way...

With the above solutions getting history of one specific file takes: 22.812467096 seconds
While with any other git tool it takes: ~1 second

This is a critical path in our product.

Thanks

**Comment by ajnavarro** [comment]
You can improve the above example code using iterators (doing this, the commit history will be walked on demand) instead of get all the commits and then print them, but basically is the way to do it. we are improving continually go-git performance, so I suggest you to use the last version.

**Comment by dorsha** [comment]
It is still pretty slow..
