### ISSUE TITLE
clone remote repo via provided commit hash

### ISSUE THREAD

**Issue by vtolstov** [src-d/go-git#48]
Can you explain me how to clone repo if i kow sha commit hash?
In case of branches - i need to pull repo... but what in case of commit hash?

Also what is the best way to detect what user specify - branch, tag or commit ?

**Comment by mcuadros** [comment]
You need to know in witch branch you can find this commit, if you don't know you will need to go though all the branches look for use. You can retrieve the commit know the hash using the [`Commit`](https://godoc.org/gopkg.in/src-d/go-git.v3#Repository.Commit) function.

About the third question sorry I don't understand it. But a Tag and a Branch are the same, you can ['Pull'](https://godoc.org/gopkg.in/src-d/go-git.v3#Repository.Pull) both with the same method
