### ISSUE TITLE
retrieving the stats on a commit

### ISSUE THREAD

**Issue by maleck13** [src-d/go-git#482]
Hey guys, thanks for a great library. I was curious if there is a way of get the stats from a commit. Something equivalent to ```git show --stat <hash>``` If not could I be pointed in roughly the right direction to add it?

**Comment by mcuadros** [comment]
Sounds a nice to have, having a method `func (c *Commit) Stats() (*CommitStats, error)` for extract the required info you can do it from: https://github.com/src-d/go-git/blob/v4/plumbing/object/commit.go#L68
