### ISSUE TITLE
AWS CodeCommit

### ISSUE THREAD

**Issue by troyronda** [src-d/go-git#49]
Hi,

For checking out from AWS CodeCommit, I had to:
* Remove lines 45-47 from clients/common/common.go (that adds the .git suffix)
* Modify DefaultBranch in remote.go to return branch = "refs/heads/master" when SymbolicReference("HEAD") returns the empty string.

**Comment by mcuadros** [comment]
We never tried with AWS CodeCommit, interesting... I will take a look.

**Comment by mcuadros** [comment]
https://github.com/src-d/go-git/commit/b024ef7713008e5be1f865df2b9563af2f005712

Solve!
