### ISSUE TITLE
Very slow for large repos

### ISSUE THREAD

**Issue by strin** [src-d/go-git#505]
```
options := git.PushOptions{
		RemoteName: remoteName,
		Auth:       auth,
		RefSpecs: []config.RefSpec{
			config.RefSpec(fmt.Sprintf("refs/heads/%s:refs/heads/%s", hash, hash)),
		},
	}

err = repo.GitRepo.Push(&options)
```

The time for second push should be significantly less than the first push. But it seems `go-git` is pushing everything again.

**Comment by strin** [comment]
To test, use this repo: https://github.com/dummy-ai/models

**Comment by smola** [comment]
@strin Thank you for reporting this. Indeed, a lot of objects were being pushed when they shouldn't. This should be fixed by PR https://github.com/src-d/go-git/pull/516
