### ISSUE TITLE
transport: file, race condition in Session.Close after context canceled 

### ISSUE THREAD

**Issue by mcuadros** [src-d/go-git#508]
A race is detected on test of transport/file, when the session is Close, and the context is canceled. 

This happens due to a goroutine still reading from the stderr.

Introduced by https://github.com/src-d/go-git/pull/507

**Comment by jfontan** [comment]
I'm not able to reproduce the race in current version or the errors in tests from fbf2a4a: https://travis-ci.org/src-d/go-git/jobs/257287484#L1142-L1146.
