### ISSUE TITLE
Support to open local repository or file transport protocol.

### ISSUE THREAD

**Issue by sona-tar** [src-d/go-git#51]
Hello
I have some questions.

How can I open local repository or file transport protocol? 
If not supported now, do you have a plan to support it?

I'd like to use go-git instead of https://github.com/gogits/git.
See https://github.com/gogits/git/issues/17

Thanks.

**Comment by oplibs** [comment]
Hello. Can I init a local repositories by this library? I need implement some functions for multi-users. Init their repositories would be needed for me. If not, any plans?

**Comment by sona-tar** [comment]
Thanks to support local repository!! 

But I want to open repository from HEAD.

```
hash, _ := repo.Head("")

for commit := range repo.Commits(hash) {
 fmt.Println(commit)
}
```

Now you supported to packfile but not supported non packed object `.git/objects/HASH[0:2]/HASH[2:64]`.
Do you have a plan to support non packed object ?

**Comment by mcuadros** [comment]
we don't support spare objects right now, you can save this issues running `git gc` before open it with go-git

**Comment by mcuadros** [comment]
@oplibs we are working on this right now, this is on the branch v4
