### ISSUE TITLE
No way to specify Auth for SubmoduleUpdateOptions

### ISSUE THREAD

**Issue by devonbarrett** [src-d/go-git#520]
After encountering:
>error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"

while trying to `PlainClone` a private repo using SSH, the issue was solved by specifying an `SSHAgent` as part of the `CloneOptions` options.

However, this option option is not available inside `SubmoduleUpdateOptions` so attempting to call errors out in the same way:
```
w, _ := repository.Worktree();
s, _ := w.Submodules();
if err := s.Update(&git.SubmoduleUpdateOptions{
  Init: true,
}); err != nil 
  //err = error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
}
```

**Comment by mcuadros** [comment]
Yep, looks like a bug, we are fixing this ASAP

**Comment by devonbarrett** [comment]
Thanks for the quick fix - works well!
