### ISSUE TITLE
CloneOptions should reuse Auth method when recursing submodules

### ISSUE THREAD

**Issue by devonbarrett** [src-d/go-git#521]
```
_, err := git.PlainClone(pathToService, false, &git.CloneOptions{
	URL:               "ssh://git@host:repo.git",
	Auth:              sshAuth,
	RecurseSubmodules: 10,
})
// err = error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

# Observed
The `PlainClone` of the initial repository succeeds, however recursing submodules fail as they require use of the same `transport.AuthMethod`

# Expected
The `Auth` method set in the `CloneOptions` is also used as a part of the `SubmoduleUpdateOptions.Auth`

Happy to make a PR if that is desirable?

**Comment by mcuadros** [comment]
sure
