### ISSUE TITLE
Unable to push when there are a lot of merged merge requests history in ref

### ISSUE THREAD

**Issue by cindy52** [src-d/go-git#530]
Func hashListToSet got stuck when there are a lots of values in hashes list
func hashListToSet(hashes []plumbing.Hash) map[plumbing.Hash]bool {
	result := make(map[plumbing.Hash]bool)
	for _, hash := range hashes {
		result[hash] = true
	}
	return result
}

**Comment by orirawlings** [comment]
Hi @cindy52,

Do you have more information to help us reproduce the issue? Maybe an example git repository that exhibits the problem and some go code that triggers the problem in the go-git library? Perhaps some output that you used to help narrow down the problem to the hashListToSet function in particular?

**Comment by cindy52** [comment]
I try to push to a repository that has 1000+ merged merge requests simply using following code:
err = r.Push(&git.PushOptions{Auth: auth}), then it got stuck at hashListToSet and the result of debugger saying that connected to loacalhost without no other variables. But it works fine with other repositories with little merged request history.

**Comment by cindy52** [comment]
It's been fixed here [revlist: ignore all objects reachable from ignored objects #516](https://github.com/src-d/go-git/pull/516) I will close the issue. Sorry for confusion.
