### ISSUE TITLE
v4 branch includes changes not in master or v4.0.0-rc* tags

### ISSUE THREAD

**Issue by orirawlings** [src-d/go-git#535]
@mcuadros @smola,

It looks like #504 was merged directly in the `v4` branch, rather than `master`. As such these changes are not in `master` as far as I can tell.

This also means that the branch installed during a `go get gopkg.in/src-d/go-git.v4` no longer matches any of the `v4.0.0-rc*` tags.

Was this intentional?

**Comment by mcuadros** [comment]
wow this was a huge error, I don't how was merged!. Fixed thanks a lot. 

PD I need to answer your email, sorry
