### ISSUE TITLE
Are all calls on storage.Storage and billy.Filesystem synchronous?

### ISSUE THREAD

**Issue by boljen** [src-d/go-git#539]
First of all thank you all for your great work on this library.

I'd like to store my data inside a key/value database and have the application manage all of the versioning for the end-user. To ensure data consistency I would have to do all the changes within a single transaction. I'm considering the following approach (give or take);

```go

type ExecOpFn func(repo *git.Repository, fs billy.Filesystem, tx *db.Transaction) error

func (s Server) ExecOperation(execOp ExecOpFn) error {
    tx := s.db.CreateTransaction()

    s.filesystem.setTransaction(tx)
    defer s.filesystem.clearTransaction()

    // All calls to the underlying filesystem must be done synchronously
    // within the operation because that's the only time that the underlying
    // filesystem actually has access to the transaction before it's committed.
    if err := execOp(s.repo, s.filesystem, tx); err != nil {
        tx.Cancel()
        return err
    }
    return tx.Commit()
}
```

Are all calls on storage.Storage and billy.Filesystem synchronous? Or is there anything within this package's API that performs asynchronous calls?

Also, could anyone perhaps confirm my suspicion that Filesystem.Chroot is only used for submodules and when opening a dotgit-style workspace/repository?

Thanks!

**Comment by mcuadros** [comment]
go-git doesn't contains long running multi-threading operations, just in one special, a goroutine is used when the packfile is being fetched and the index is generated in a goroutine.

You want to implement a filesystem backed by a key/value databases for the Worktree or for the object storage?

**Comment by boljen** [comment]
Thanks!

> go-git doesn't contains long running multi-threading operations, just in one special, a goroutine is used when the packfile is being fetched and the index is generated in a goroutine.

Does this happen synchronously from the perspective of the public API?

>  You want to implement a filesystem backed by a key/value databases for the Worktree or for the object storage?

Both should be backed by the same transaction. The application can reliably manage the transaction as long as there are no asynchronous calls, from the perspective of the public git api, to the underlying worktree Filesystem and the underlying object storage.Storage (and hopefully the FIlesystem underneath the object storage.Storage)

> The Filesystem.Chroot is used in several scenarios, but yes mainly for the .git folder and the submodule, but is not guaranteed that is not used or maybe used in the future in other components.

After consulting the billy.osfs implementation I realized that Chroot is supposed to be path-based and not inode-based. This greatly simplifies things. My apologies.

**Comment by mcuadros** [comment]
Having the internal object store in a key/value is extremely slow, unless that you have a heavy cache. The objects are retrieved without doing any optimization, this means that the same object can be retrieved several times during the same operation. 

From the API is synchronously.
