### ISSUE TITLE
Example of creating a branch

### ISSUE THREAD

**Issue by wstrange** [src-d/go-git#551]
This is a newbie question, but I am little unclear on how to do the equivalent of:

```
git branch new-branch
git checkout new-branch
```

**Comment by wstrange** [comment]
This is what I came up with. Not sure if it is 100% correct, but it seems to work:

```
       branch := fmt.Sprintf("refs/heads/%s", config.GitBranch)
       b := plumbing.ReferenceName(branch)

	// First try to checkout branch
	err = worktree.Checkout(&git.CheckoutOptions{Create: false, Force: false, Branch: b} )

	if err != nil {
		// got an error  - try to create it
		err := worktree.Checkout(&git.CheckoutOptions{Create: true, Force: false, Branch: b} )
		CheckIfError(err)
	}
```

**Comment by FLavalliere** [comment]
Does this change the local branch?

I've tried it and when i do a "git branch" in my local directory it hasn't been changed.. it is still pointing to master.... but at least it has created the foo branch -> "refs/heads/foo"

**Comment by DeKugelschieber** [comment]
I tried the solution provided by wstrange and it worked. But I would like to know if it's possible to do this concurrently for multiple users without conflicts. My scenario:

1. user A creates a new branch
2. meanwhile user B commits a new file (master)
3. user A commits a new file (branch)

The result should be a new commit on branch by user A and a new commit on master by user B. Do I need to make sure that step 1 and 3 are executed atomicly or is this feature provided by the worktree? This process is accessed through a webservice.

**Comment by FLavalliere** [comment]
Agreed, the solution did work up to a certain level..

The issue I had is that i had to use "Force: true", in my case.

The other issue, i have right now is that 

the  .git/config file on the local filesystem doesn't get the branch added back after a "Create Branch"

In short, a git pull afterward doesn't work.

**Comment by mcuadros** [comment]
@FLavalliere  A `git pull` with the cgit or with go-git? Why the force was required? Are you using the latest code? We did a few days ago some important changes in the `Worktree.Reset` witch is used by the checkout.

**Comment by FLavalliere** [comment]
a "git pull" using the linux git client and also from the go-git.

I manually added in my own code, after the git create branch had been done to edit the .git/config file if the branch name wasn't in it. This seems to resolve my issue.

I used "go get gopkg.in/src-d/go-git.v4"  yesterday.

**Comment by FLavalliere** [comment]
So here what I've done. and the Force is not needed.

```
       branch := fmt.Sprintf("refs/heads/%s", config.GitBranch)
       b := plumbing.ReferenceName(branch)

	// First try to checkout branch
	err = worktree.Checkout(&git.CheckoutOptions{Create: false, Force: false, Branch: b} )

	if err != nil {
		// got an error  - try to create it
		err := worktree.Checkout(&git.CheckoutOptions{Create: true, Force: false, Branch: b} )
		CheckIfError(err)
	}
     
        err = ioutil.WriteFile(folderpath, "foo"),  []byte (fmt.Sprintf("%s", "foo")), 0755)
        hash, err := wgit.Add("foo")
       hash1, err := wgit.Commit("foo", &git.CommitOptions{Author: &object.Signature{
                                                Name:  "Test Create Branchh",
                                                Email: "createBranch@gogit-test.com",
                                                When:  time.Now(),
       },
       })
      err = gitresp.Push(&git.PushOptions{Auth: a.getAuth()})
      fmt.Println("Does file ", gitConfigFile, " contains ", branch)
      fmt.Println(strings.Contains(s, branch))
                                        if (! strings.Contains(s, branch) ) {
                                            // If the file doesn't exist, create it, or append to the file
                                            f, err := os.OpenFile(gitConfigFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
                                            if err != nil {
                                                CheckIfError(err)
                                            }
                                            if _, err := f.Write([]byte(fmt.Sprintf("[branch \"%s\"]\n\tremote = origin\n\tmerge = %s\n\n", branchTitle, b))); err != nil {
                                                CheckIfError(err)
                                            }
                                            if err := f.Close(); err != nil {
                                                CheckIfError(err)
                                            }
          }
`````

At this point, when I am doing using a unix "Git" client, a "git status", "git pull" everything seems to work.

I've updated a file in the Git Repo (on another machine). When I do the git.Pull from the go-git, it says that it is "non-fast-forward update", but when i do a "git status" in the git branch it says 

"Your branch is behind 'origin/OK99' by 1 commit, and can be fast-forwarded."

**Comment by FLavalliere** [comment]
I think this issue can be closed.

Creating a branch works, it will only be visible to the Git Server the "Remote" only if you commit a change and push it though.
