### ISSUE TITLE
git server errors

### ISSUE THREAD

**Issue by nhooyr** [src-d/go-git#556]
I'm writing a git SSH server with this package but I'm having quite a bit of trouble with getting it to work. I'm working on a private repository that I cannot share but I extracted out a minimal example into https://github.com/nhooyr/go-git-server with an example test that fails.

I've basically copied the receive_pack and upload_pack from https://github.com/src-d/go-git/tree/6f3b2d878d2f84f513c9dc08b000f653ea83f690/cli/go-git

My copied version is [here](https://github.com/nhooyr/go-git-server/blob/4a34fedce6175b14c410b6805f8f31755a3ed366/server.go#L88-L169).

Here is an example of the output from the test script:

```bash
Initialized empty Git repository in /private/var/folders/7b/218sfv615xxf_w9ttnpjt0_r0000gn/T/tmp.DyzqkAEA/foobar/

CLONING EMPTY REPOSITORY
Cloning into 'foobar'...
2017/08/23 12:50:40 /var/folders/7b/218sfv615xxf_w9ttnpjt0_r0000gn/T/tmp.DyzqkAEA/foobar
warning: You appear to have cloned an empty repository.
2017/08/23 12:50:40 failed to decode upload pack request: pkt-line 1: missing 'want ' prefix
CLONED EMPTY REPOSITORY

[master (root-commit) d08242a] initial
 1 file changed, 1 insertion(+)
 create mode 100644 somefile
/var/folders/7b/218sfv615xxf_w9ttnpjt0_r0000gn/T/tmp.Tfcs2xMU/foobar
PUSHING REPOSITORY
fatal: The remote end hung up unexpectedly
2017/08/23 12:50:50 error in encoding report status: EOF
	Error Trace:	server_test.go:55
	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4203b4060), Stderr:[]uint8(nil)}

Process finished with exit code 1
```

The first error about failing to decode a upload pack request seems to happen because the client is fetching a empty repository. I tested the same server on a repository with commits and it works fine. If I'm not doing anything wrong, that error message is very unclear and should probably not be an error at all.

The second error I have no idea why its happening but I have not gotten pushes to work at all with the server and this library. In fact, when pushing a commit, I've managed to make the library panic. Unfortunately, it doesn't panic in my minimal example but I have an example that I cannot share because its intertwined with my private repository that does make the library panic 100%. It's the exact same server code, just a different repository being pushed/pulled. I can extract it out as well, but I'd like to get the above repository working first.

I feel like I'm doing something horribly wrong but I have no idea what. Would really appreciate some assistance in debugging this.

**Comment by nhooyr** [comment]
Hmm, definitely not an issue with my code above. I tested using the upload-pack and receive-pack commands provided in this library and I get similar errors. If I substitute those commands for the standard git upload-pack and receive-pack commands, everything works fine.

**Comment by orirawlings** [comment]
@mcuadros I noticed the `gopkg.in/src-d/go-git.v4/cli/go-git` doesn't seem to have much love, and really only seems to contain implementations for `upload-pack` and `receive-pack`.

Can you elaborate on the status of the package in question and level of support? Are these implementations even complete?

**Comment by mcuadros** [comment]
This package is close to be deleted, the `cli` is something out of the scope, this two command were created for testing purposes.

**Comment by nhooyr** [comment]
Does that mean the upload-pack and receive-pack implementations part of the library will also be deleted?

**Comment by mcuadros** [comment]
Maybe, will be better to move they to `_examples` folder.

**Comment by nhooyr** [comment]
The entire implementation?

**Comment by mcuadros** [comment]
Errr.. this files are few lines less than a hundred, and are don't thing that someone is using this programs.

**Comment by nhooyr** [comment]
I'm talking about the implementation of upload-pack and receive-pack in the library, not in the cli packages.

**Comment by mcuadros** [comment]
Hahaha, not this is being use by use in production. I was talking about the
cli package.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
