### ISSUE TITLE
Can't clone annotated tags with `ReferenceName` in Clone

### ISSUE THREAD

**Issue by mitchellh** [src-d/go-git#557]
Hi! Great library. 

The problem is that given an annotated tag ref, I get an "object not found" error:

```go
repo, err := git.PlainClone(dir, false, &git.CloneOptions{
	URL: "...",
	ReferenceName: plumbing.ReferenceName("refs/tags/v1.0.0"),
})
```

Where `v1.0.0` is an **annotated tag** (not a lightweight one). 

I'm not sure if this is working as intended or not, but I'd expect the library to recognize the commit the annotated tag is pointing to and load that.

Reproducing this is extremely easy:

  1. Create a new git repo
  2. Commit a single file so its not empty
  3. `git tag -a "v1.0.0" -m "1.0.0"`
  4. Push
  5. Run the code above using that repo's address. It will fail.

Thanks!

**Comment by orirawlings** [comment]
This appears to be because we are trying to reset the working directory to `head.Hash()`, which in this case is not a commit object, but the tag object.

https://github.com/src-d/go-git/blob/master/repository.go#L434

**Comment by mitchellh** [comment]
Thank you!

**Comment by mcuadros** [comment]
@mitchellh just playing or any plan for use it in something relevant?

**Comment by mitchellh** [comment]
Something quite major! It is relevant to an existing product. I'll comment back here once we announce it. Its still not released. :)
