### ISSUE TITLE
git commit -a should not refer to the storage but to the filesystem

### ISSUE THREAD

**Issue by grunenwflorian** [src-d/go-git#571]
Hi,

[x] feature request

**How would the same operation be performed using git from the command line terminal?**
\# bar.txt is tracked by git
rm -f bar.txt
git commit -am "Delete that file"

**Current behavior:**
Currently, removing a file in a repository without using go-git will break the git commit All functionalities.  error = Lstat error no such file or directory

**Expected behavior:**
worktree_commit.go, Commit.
```go
if opts.All {
		if err := w.autoAddModifiedAndDeleted(); err != nil {
			return plumbing.ZeroHash, err
		}
}
```

```go
func (w *Worktree) autoAddModifiedAndDeleted() error {
	s, err := w.Status()
	if err != nil {
		return err
	}

	for path, fs := range s {
		if fs.Worktree != Modified && fs.Worktree != Deleted {
			continue
		}

		if _, err := w.Add(path); err != nil {
			return err
		}

	}

	return nil
}
```

If the file does not exist anymore Add will return an Lstat error, which is expected because a deletion can be considered a modification. Hence it should be covered by a Commit.  

So my guess is, if not found the StatusCode of the FileStatus should be modified to  Deleted.

**go-git version:**
~4.0.0-rc9

I'll be happy to submit a PR if you want. 

If you have a better idea,I will be happy to read it !

**Comment by mcuadros** [comment]
Yep ,this is correct, we should avoid return a err when a file is deleted. Happy to accept a PR with the solution.

**Comment by grunenwflorian** [comment]
Hi,

I'm ready to submit a PR, could you give me the right ?

Thanks.

**Comment by orirawlings** [comment]
Hey @grunenwflorian,

Feel free to open the PR. You should have permissions to fork the src-d/go-git repository and file a PR from your fork to the main project. 

Thanks!

**Comment by grunenwflorian** [comment]
Thanks @orirawlings.

My bad, I'm so used to create branch that I forgot the fork option.
