### ISSUE TITLE
writing trees?

### ISSUE THREAD

**Issue by hanwen** [src-d/go-git#589]
Is there support for writing Tree objects into EncodedObjects? I couldn't find any.

**Comment by mcuadros** [comment]
Yep, just use the method [`Tree.Encode`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/object#Tree.Encode).

**Comment by hanwen** [comment]
that could do with some documentation. Since the object has unexported fields, it's not obvious that you can construct one yourself from scratch and have it work automatically.

**Comment by mcuadros** [comment]
go-git is intended to be a high level library, so covering plumbing stuff in the documentation is not our main goal right now. But PRs improving this are more than welcome. 

Here you can see an example of how the `plumbing.Tree` struct is build:

https://github.com/src-d/go-git/blob/c2561364e33763d3356a23c5850424a334de30e9/worktree_commit.go#L103-L189
