### ISSUE TITLE
Git log --all

### ISSUE THREAD

**Issue by shanedasilva** [src-d/go-git#595]
I'm trying to implement a git log --all call and it doesn't seem that the library directly supports this.

Are there plans to add this feature or could it be done using rev-list?

**Comment by mcuadros** [comment]
`git log --all` is not implemented but using the [`revlist`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/revlist) package is the way to implement something like this.

**Comment by shanedasilva** [comment]
@mcuadros `revlist` did the trick. Thanks for responding.
