### ISSUE TITLE
feat(receive-pack) read-only

### ISSUE THREAD

**Issue by themihai** [src-d/go-git#60]
This is a feature request to support receive-pack and basically a git server in read-only mode. The implementation could be used to "mirror" an existing repository(and perhaps apply a different ACL)  or create and serve in-memory repositories on the fly.

**Comment by smola** [comment]
We have work in progress for this.

**Comment by smola** [comment]
The low level work is done (https://github.com/src-d/go-git/pull/190), including a clone of the "git-receive-pack" command, see: https://github.com/src-d/go-git/blob/master/cli/go-git/receive_pack.go

Further work will include full git:// and ssh:// servers.
