### ISSUE TITLE
I would like to request `git-verify-commit` support please

### ISSUE THREAD

**Issue by blacktop** [src-d/go-git#605]
great library btw! 😁

**Comment by blacktop** [comment]
Or at the very least the ability to extract the signature, sign from a commit?

**Comment by blacktop** [comment]
Is this done now? @darkowlzz If so many much thanks! 👍

**Comment by blacktop** [comment]
Is this actually done?  It seems like support for signatures to be included in commits has been added, but not the ability to verify them?

**Comment by mcuadros** [comment]
True, is not implemented, thanks!
