### ISSUE TITLE
Determining what branch a commit belongs to

### ISSUE THREAD

**Issue by rstat1** [src-d/go-git#611]
Firstly, this isn't a bug or any sort of problem, though it may be a feature request (if what I'm asking isn't doable)..how would I, given the hash of any commit in a repo managed with this library, determine what branch that commit belongs to?

**Comment by sscmd** [comment]
There's no one line solution for this. You'll have to check the parent hashes of your commit and follow that chain up and determine which commit is at the head of a reference.

**Comment by rstat1** [comment]
Well yea, I figured there wasn't...

Basically my thought here is, you would take the tip commit of w/e branch you were looking at and walk backwards until you find the commit you were looking at. Does that sounds right?

The only problem I'd have then is determining when I've reached the last commit on that branch...

**Comment by orirawlings** [comment]
Hey @rstat1,

If you interested in reachability from a pure DAG standpoint, I think the following code would do what you want. Basically this code will print each branch name that can reach the given commit by walking the commit graph (because, of course, there could be multiple branches that can reach a commit).

```
package main

import (
	"fmt"
	"os"

	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/plumbing"
)

// Prints out the name of each branch from which given commit can be reached.
func main() {
	CheckArgs("<path>", "<commit>")
	path := os.Args[1]
	commit := plumbing.NewHash(os.Args[2])

	r, err := git.PlainOpen(path)
	CheckIfError(err)

	memo := make(map[plumbing.Hash]bool)

	rs, err := r.References()
	CheckIfError(err)

	CheckIfError(rs.ForEach(func(ref *plumbing.Reference) error {
		n := ref.Name()
		if n.IsBranch() {
			b, err := r.Reference(n, true)
			if err != nil {
				return err
			}
			v, err := reaches(r, b.Hash(), commit, memo)
			if err != nil {
				return err
			}
			if v {
				fmt.Println(n)
			}
		}
		return nil
	}))
}

// reaches returns true if commit, c, can be reached from commit, start. Results are memoized in memo.
func reaches(r *git.Repository, start, c plumbing.Hash, memo map[plumbing.Hash]bool) (bool, error) {
	if v, ok := memo[start]; ok {
		return v, nil
	}
	if start == c {
		memo[start] = true
		return true, nil
	}
	co, err := r.CommitObject(start)
	if err != nil {
		return false, err
	}
	for _, p := range co.ParentHashes {
		v, err := reaches(r, p, c, memo)
		if err != nil {
			return false, err
		}
		if v {
			memo[start] = true
			return true, nil
		}
	}
	memo[start] = false
	return false, nil
}
```

**Comment by rstat1** [comment]
@orirawlings Has anyone told you how awesome you are, today? If not let me be the first :D That was exactly what I was looking for, Thank you.

@sscmd Thanks for your help as well.
