### ISSUE TITLE
git --no-pager log -1 pretty=format my_file

### ISSUE THREAD

**Issue by posito** [src-d/go-git#612]
Hello, 

I am trying to find the way to get the last commit on a file. I am doing it this way today...
```go
exec.Command("git","--no-pager", "log", "-1", `--pretty=format:"%ad"`, file).Output()
```

Is there a better way ?

**Comment by posito** [comment]
@mcuadros any pointers ?  git-blame doesn't work becuase i need to get the latest change

**Comment by mcuadros** [comment]
This functionality is not implemented, you will need to all the commits to find witch tree makes references to it, I suggest read the original implementation at cgit.

**Comment by mcuadros** [comment]
Duplicate https://github.com/src-d/go-git/issues/562
