### ISSUE TITLE
Clone Repository to S3

### ISSUE THREAD

**Issue by ghost** [src-d/go-git#614]
I'm trying to figure out how to use an S3 bucket as my working directory. Is it possible with the library?

**Comment by mcuadros** [comment]
You will need to extend go-git, implementing a `go-billy` Filsystem, at source{d} we storage repositories at HDFS, so is a similar approach. 

You will need to package all the repository files in one unique file, we use our own format call [siva](https://github.com/src-d/go-siva). If you use [`go-billy-siva`](https://github.com/src-d/go-billy-siva) you will be able to save a repository to a unique .siva file, after it you can upload it.

**Comment by shanedasilva** [comment]
Sounds good, thanks @mcuadros

**Comment by shanedasilva** [comment]
@mcuadros I've been struggling to figure out how exactly to implement this with go-git. Would you be able to provide a few more instructions? I would really appreciate it.
