### ISSUE TITLE
Commit Modified Lines

### ISSUE THREAD

**Issue by shanedasilva** [src-d/go-git#622]
Is there any way to get access to modified lines vs deleted lines. I've asked about --word-diff in the past which isn't on the roadmap but hoping there is a way to handle this case.

**Comment by ajnavarro** [comment]
Hi,

The diff output only support 3 kind of lines in a diff by now: added, deleted and unmodified.

To know if a line is a modified version of another previous line, you should obtain a "similarity ratio" or something like that using modified lines on the new file version, and non-deleted lines from the previous version.
