### ISSUE TITLE
How to create a new branch

### ISSUE THREAD

**Issue by kairen** [src-d/go-git#625]
Can I use this library to create a new branch? because I can't find example in the project.

**Comment by orirawlings** [comment]
Hey @kairen,

If you are looking to create a new branch and check it out at the same time, you can use the `Create` flag on [`CheckoutOptions`](https://godoc.org/gopkg.in/src-d/go-git.v4#CheckoutOptions) in a call to [`(*git.Worktree).Checkout`](https://godoc.org/gopkg.in/src-d/go-git.v4#Worktree.Checkout).

If you just want to create a branch without checking it out (or if you want to create a branch in a bare repository that doesn't have a Worktree), you can do something like:

```
import "gopkg.in/src-d/go-git.v4/plumbing"
...
r, _ := git.PlainOpen("/path/to/repo")
r.Storer.SetReference(plumbing.NewHashReference("refs/heads/"+branchName, desiredHash))
```

**Comment by kairen** [comment]
Hi @orirawlings, thanks you for your help!! I will try this.
