### ISSUE TITLE
Usage with a host alias set ssh config

### ISSUE THREAD

**Issue by artushin** [src-d/go-git#629]
I'm getting a DNS resolution error to github when I have an alias for a particular remote origin url.

For example, let's say I have two git configs:
```
remote.origin.url=git@git1:user1/foo
remote.origin.url=git@git2:user2/bar
```

These have corresponding ssh configs:
```
Host git1
Hostname github.com
IdentityFile ~/.ssh/foo
User user1

Host git2
Hostname github.com
IdentityFile ~/.ssh/bar
User user2
```

Operations using go-git (I've only tried Pull but I assume others too), don't respect the ssh configs and fail with `dial tcp: lookup git1 on 169.254.169.254:53: no such host`. I'm not passing an Auth into the PullOptions. Am I doing something wrong or is this expected?

**Comment by mcuadros** [comment]
Currently this feature of config is not supported, sorry

**Comment by artushin** [comment]
Good to know, I'll try and get a PR in when I have some free time.
