### ISSUE TITLE
CommitObject with short hash value?

### ISSUE THREAD

**Issue by sergeyhush** [src-d/go-git#634]
I am trying to get a commit object using a short hash value, the code below does not work:
`repo.CommitObject(plumbing.NewHash("abc123"))`
This assumes that there is a full hash that starts with abc123.....
Is there a way, short of iterating repo.CommitObjects(), to do what I wanted?

**Comment by mcuadros** [comment]
Short hash are kind of porcelain operations, for the users, since this is a library to be used programmatically, the use of short hashes is not very useful.

But will be great having a function to search this, if someone requires to resolve short hashes.

**Comment by orirawlings** [comment]
#599 includes a request to add behavior for parsing short hashes. Closing this as duplicate.
