### ISSUE TITLE
request: semver / dep compatible release tags

### ISSUE THREAD

**Issue by sjansen** [src-d/go-git#662]
I see several issues related to release tags causing confusion, but not with the actual solution.

Unfortunately, according to semver `v4.0.0-rc5` is newer than `v4.0.0-rc15`. As a result, `dep` installs the wrong version. The easiest solution is to add a dot after the `rc`. In other words: `v4.0.0-rc.16`.

Please consider tagging the next release with a version that plays nicely with semver / dep.

**Comment by mcuadros** [comment]
The next version being release soon will be the final `v4`, for the next rc will use the dor format. Thanks
