### ISSUE TITLE
get file names (or may be more) via Commit

### ISSUE THREAD

**Issue by vtolstov** [src-d/go-git#67]
How can i get modified files via Commit?
My use case - i have repo and commit sha and need to know what files has been changed via this commit?

**Comment by mcuadros** [comment]
This feature is planned to be on v4, now under heavy development. 
With the v3, you need calc the diff tree for the commits and after make the diff of the files by yourself.

**Comment by mcuadros** [comment]
https://github.com/src-d/go-git/issues/57
