### ISSUE TITLE
unquoted '\' must be followed by new line

### ISSUE THREAD

**Issue by fredcarle** [src-d/go-git#681]
Has anyone seen this before? I get this `unquoted '\' must be followed by new line` error on some of the repo I try to open with `git.PlainOpen()`.

**Comment by orirawlings** [comment]
Hey @fredcarle,

Can you share any code or links to the repository you are trying to open so we can try and reproduce the issue?

**Comment by fredcarle** [comment]
Unfortunately I can share the link to the repo since it's a private one. But here is the simple code I was using for testing.

```
        r, err := git.PlainOpen("/link/to/my/local/repo")
	if err != nil {
		log.Panic(err)
	}
	remotes, err := r.Remotes()
	if err != nil {
		log.Panic(err)
	}
	for _, r := range remotes {
		fmt.Println("remote", r.String())
	}
```

**Comment by strib** [comment]
I've seen this before.  In one instance, it was caused by trying to read a config written by Git tower: keybase/client#8812

The parser used to read the git config files really doesn't like backslashes.

**Comment by fredcarle** [comment]
That would makes sense since I'm using Tower

**Comment by orirawlings** [comment]
Seems like there is some benefit in extending the git config parser to handle backslashes more gracefully.

**Comment by japanoise** [comment]
This is especially problematic on Windows, because the likelihood of having slashes is much higher (Paths, for example)

**Comment by scbizu** [comment]
Resolved this by removing all cols contain `\` in `.git/config`, which seems like generated by Git Tower.

**Comment by filipnavara** [comment]
It bails out on the following `.git/config`:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = E:\\Git\\emclient\\emclient.git
```

This is perfectly valid and parsable by the original Git parser (https://github.com/git/git/blob/master/config.c#L537-L560).
