### ISSUE TITLE
when iterate between commits exists any way to know what this is merge and skip ? 

### ISSUE THREAD

**Issue by StanislavKH** [src-d/go-git#701]
Please, when iterate between commits exists any way to know, this is exactly commit or merge  and skip ? Like git log --no-merges, or not supported ? Thanks

**Comment by PaluMacil** [comment]
I could be wrong but I don't think git itself indicates that a commit is a merge. I think you should indicate in the commit message but a commit is simply a collection of diffs.

**Comment by orirawlings** [comment]
You actually can tell if a commit is a merge or not. In git, a merge commit is any commit with more than one parent.

If you want to replicate something like `git log --no-merges` you could do something like the following:

```
package main

import (
	"fmt"
	"os"

	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/plumbing/object"
)

func main() {
	CheckArgs("<path>")
	path := os.Args[1]

	r, err := git.PlainOpen(path)
	CheckIfError(err)

	ref, err := r.Head()
	CheckIfError(err)

	c, err := r.CommitObject(ref.Hash())
	CheckIfError(err)

	cIter := object.NewCommitPostorderIter(c, nil)
	err = cIter.ForEach(func(c *object.Commit) error {
		if c.NumParents() <= 1 {
			fmt.Println(c)
		}
		return nil
	})
	CheckIfError(err)
}
```

**Comment by StanislavKH** [comment]
yep, thanks, looks like really what needed
