### ISSUE TITLE
How thread safe is the library (file system/transport)

### ISSUE THREAD

**Issue by vermapratyush** [src-d/go-git#702]
Hi,

I wanted to know how thread-safe is the library. 
I understand `FileSystem` isn't a thread-safe implementation. But what about concurrent read access? What about thread safety in the transport library (two goroutines doing a git.Push or one doing git.Push and other git.Pull)?

**Comment by orirawlings** [comment]
Unfortunately it is not thread safe. Very few data structures which mutate during the course of operations have been protected with locks or other synchronization mechanisms. 

One way to introduce concurrency in an application that uses `go-git` is to instantiate multiple Repository and Storer instances for use from different go-routines. However, please note that leveraging file system locking was only recently introduced on the master branch and it is not always used when performing updates to git references, so you many still experience some racy behavior when using file-backed Repositories pointed at the same `.git` directory.

**Comment by vermapratyush** [comment]
Thanks for the quick reply.
Closing the ticket.
