### ISSUE TITLE
git clone -n 

### ISSUE THREAD

**Issue by Nhoya** [src-d/go-git#705]
Hi, i was wondering if was possible to reproduce the -n option of git clone

**Comment by mcuadros** [comment]
Should be that easy as skip this line: https://github.com/src-d/go-git/blob/v4.0.0/worktree.go#L181

**Comment by rykov** [comment]
@mcuadros I didn't find where Repository's `clone` func calls `Checkout` on the worktree that you've linked. 

Do you think that it could by implemented by adding a flag to `CloneOptions` that would disable this section of Repository's `clone` even if `r.wt != nil`?

https://github.com/src-d/go-git/blob/v4.0.0/repository.go#L452-L478

**Comment by rykov** [comment]
Something like this: https://github.com/src-d/go-git/compare/master...rykov:master

**Comment by mcuadros** [comment]
Sorry is not the Checkout is the Reset, https://github.com/src-d/go-git/blob/v4.0.0/repository.go#L463

**Comment by rykov** [comment]
@mcuadros I've taken another look at the documentation for `git-clone` and I think the [changes that I've made on my fork](https://github.com/src-d/go-git/compare/master...rykov:master) follow the functionality closer than putting a condition just around `Reset`.

Here's what the docs say for `--recurse-submodules`:

> This option is ignored if the cloned repository does not have a worktree/checkout (i.e. if any of --no-checkout/-n, --bare, or --mirror is given)

https://git-scm.com/docs/git-clone#git-clone---recurse-submodulesltpathspec

I'll add some tests and submit [this](https://github.com/src-d/go-git/compare/master...rykov:master) as a PR

**Comment by Nhoya** [comment]
Pretty interesting, can you please provide an example usage?

**Comment by rykov** [comment]
@Nhoya So the behavior is similar to `git clone --bare`, in that the worktree is not created.  However, with `-n` option, the metadata is still placed under the `.git` subdirectory, rather than in root.

Here's a modification of the basic example from the README with this flag enabled:

```go
Info("git clone -n https://github.com/src-d/go-git")

_, err := git.PlainClone("/tmp/foo", false, &git.CloneOptions{
    URL:        "https://github.com/src-d/go-git",
    Progress:   os.Stdout,
    NoCheckout: true,
})

CheckIfError(err)
```

**Comment by Nhoya** [comment]
So retriving commits with

```
r, _ := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
    URL:        "https://github.com/src-d/go-git",
    Progress:   os.Stdout,
    NoCheckout: true,
})
ref, _ := r.Head()
        cIter, _ := r.Log(&git.LogOptions{From: ref.Hash()})

        commits := ""
        _ = cIter.ForEach(func(c *object.Commit) error {
                commits += fmt.Sprintf("%s", c.Author)
                return nil
        })
```
is still possible?
