### ISSUE TITLE
Question: System-wide limitation to signed commits?

### ISSUE THREAD

**Issue by fubarhouse** [src-d/go-git#709]
I'm looking into a way I can completely cut off the ability to create unsigned commits.

Would anybody know if this is currently supported by this project?

**Comment by orirawlings** [comment]
Hey @fubarhouse,

Speaking abstractly, `git` is a distributed database. This means anyone who has a copy of this database is free to create unsigned commits. What you can do, of course, is avoid accepting commits and/or tags into your copy of the database which are not signed.

`go-git` does support reading and verification of signatures of commits and tags. The following parts of the API are relevant:

- `PGPSignature` field on [`object.Commit`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/object#Commit)
- [`(*object.Commit).Verify`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/object#Commit.Verify)
- `PGPSignature` field on [`object.Tag`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/object#Tag)
- [`(*object.Tag).Verify`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/object#Tag.Verify)

Feel free to elaborate further on your use case if you are looking for something additional.


Cheers
