### ISSUE TITLE
how to replace native git?

### ISSUE THREAD

**Issue by ddatsh** [src-d/go-git#711]
how to use go-git to clone/push/pull ?

go-git  clone https://github/xxx

**Comment by orirawlings** [comment]
Hey @ddatsh,

To clarify, are you looking for a command line tool which is implemented with `go-git`?

`go-git` is currently designed to be used as a library within other programs.

To perform clone, push, and pull operations with the library feel free to refer to these functions:

- [`git.PlainClone`](https://godoc.org/gopkg.in/src-d/go-git.v4#PlainClone)
- [`(*git.Repository).Push`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.Push)
- [`(*git.Worktree).Pull`](https://godoc.org/gopkg.in/src-d/go-git.v4#Worktree.Pull)


Cheers
