### ISSUE TITLE
How to: git show

### ISSUE THREAD

**Issue by Attanon** [src-d/go-git#718]
Hi, 

i need use `git show` command.. like this `git show origin/master:.deploy.yml > f.txt`

is it possible?

I want to get content of file of another branch without checkouting into other branch

**Comment by mcuadros** [comment]
We don't have any function to archive this directly for doing this you need to walk the HEAD and use the methods [`Commit.Patch`](https://github.com/src-d/go-git/blob/v4.0.0/plumbing/object/commit.go#L78) and `Commit.String`]

**Comment by orirawlings** [comment]
Hey @Attanon,

If you want to replicate the behavior of `git show` you can do something like the following:
```
package main

import (
	"fmt"
	"io"
	"os"

	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/plumbing"
	"gopkg.in/src-d/go-git.v4/plumbing/object"
)

// resolve blob at given path from obj. obj can be a commit, tag, tree, or blob.
func resolve(obj object.Object, path string) (*object.Blob, error) {
	switch o := obj.(type) {
	case *object.Commit:
		t, err := o.Tree()
		if err != nil {
			return nil, err
		}
		return resolve(t, path)
	case *object.Tag:
		target, err := o.Object()
		if err != nil {
			return nil, err
		}
		return resolve(target, path)
	case *object.Tree:
		file, err := o.File(path)
		if err != nil {
			return nil, err
		}
		return &file.Blob, nil
	case *object.Blob:
		return o, nil
	default:
		return nil, object.ErrUnsupportedObject
	}
}

func main() {
	CheckArgs("<repoPath> <rev> <path>")
	repoPath := os.Args[1]
	rev := os.Args[2]
	path := os.Args[3]

	repo, err := git.PlainOpen(repoPath)
	CheckIfError(err)

	h, err := repo.ResolveRevision(plumbing.Revision(rev))
	CheckIfError(err)
	if h == nil {
		CheckIfError(fmt.Errorf("resolved nil hash: %s", rev))
	}

	obj, err := repo.Object(plumbing.AnyObject, *h)
	CheckIfError(err)

	blob, err := resolve(obj, path)
	CheckIfError(err)

	r, err := blob.Reader()
	CheckIfError(err)
	defer func() {
		CheckIfError(r.Close())
	}()

	_, err = io.Copy(os.Stdout, r)
	CheckIfError(err)
}
```

**Comment by orirawlings** [comment]
@mcuadros, a small thing I noticed while writing the example above was an oddity in the API for [(*git.Repository).ResolveRevision](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.ResolveRevision).

It is the only function in the API which uses a `*plumbing.Hash` rather than a `plumbing.Hash`. I don't think this oddity is motivated by anything in particular, and we might want to consider smoothing this out the next time we do a major (i.e. backward incompatible) release of the library.
