### ISSUE TITLE
go-billy-siva S3 Backend

### ISSUE THREAD

**Issue by shanedasilva** [src-d/go-git#728]
I need to use S3 as a back-end for my repositories and it has been suggested that I clone the repository, create a siva file, and upload to S3. I'm having some trouble implementing this, has anyone done anything similar in that past?

**Comment by mcuadros** [comment]
What kind of problems are you having, currently we are using this with HDFS, but  It should be the same  You can take a look to the project here: https://github.com/src-d/borges

**Comment by bzz** [comment]
Indeed, as @mcuadros noted - in Borges, there is an example of [transactional updates](https://github.com/src-d/borges/blob/master/archiver.go#L303) of repositories stored as .siva files in [HDFS](https://github.com/src-d/core-retrieval/blob/master/container.go#L135) that are implemented by [copying .siva files locally](https://github.com/src-d/core-retrieval/blob/master/repository/copier.go#L34) changing them and uploading back.

You could do something very similar with S3, but may be simpler, in case you do not need to support concurrent writes to the same repository in S3.

**Comment by shanedasilva** [comment]
The borges example was actually really helpful, thanks.
