### ISSUE TITLE
Personal Access Token authentication isn't supported

### ISSUE THREAD

**Issue by bddenhartog** [src-d/go-git#730]
It looks like #504 should have added this to v4, yet grabbing that version of the library from `gopkg.in/src-d/go-git.v4` doesn't seem to contain the merge commit, c17627c5ee10ed6e9ef92dafb8d5b46160484e0d. What's going on here? Do we need to have the changes made in the pull request re-submitted?

**Comment by orirawlings** [comment]
@bddenhartog I think this was noticed some time back in #535. Although I'm having trouble verifying now that changes was reintegrated to the proper branch.

@mcuadros, do you remember how the changes for #504 were finally integrated?

**Comment by bddenhartog** [comment]
@orirawlings It doesn't look like token based authentication is supported in the current source, as far as I can tell. If it _is_ supported, it's certainly not clear - perhaps this issue should be updated to reflect that and instead posit the addition of documentation detailing how to utilize token-based authentication (which should be a **much** better choice for someone using the library in an automated fashion...)

**Comment by bddenhartog** [comment]
And thanks - I should have referenced #535 as I found it before posting this issue; I just happened to be in a rush at the moment.

**Comment by mcuadros** [comment]
@bddenhartog far as I know to use GitHub token you can use BasicAuth with now user (or any string) and the token as the password.
