### ISSUE TITLE
How to git fetch and git reset --hard origin/master

### ISSUE THREAD

**Issue by mumblez** [src-d/go-git#734]
effectively

`git fetch origin`
`git reset --hard origin/master`

any help is much appreciated, thanks

**Comment by mumblez** [comment]
nvm, figured it out!

**Comment by jacksgt** [comment]
Thanks for sharing your insights!

https://xkcd.com/979/

**Comment by mumblez** [comment]
@jacksgt https://github.com/mumblez/gwg/blob/master/main.go#L99
Hope this helps :)

**Comment by jacksgt** [comment]
@mumblez Thank you!
