### ISSUE TITLE
After failing PlainClone .git directory nevertheless exists

### ISSUE THREAD

**Issue by jkblume** [src-d/go-git#741]
### What version of Go are you using (`go version`)?
go version go1.9.3 darwin/amd64

### What did you do?

```go
package main

import (
	"log"
	"os"
	"gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing"
)

func main() {
	_, err := git.PlainClone("repository", false, &git.CloneOptions{
		URL:           "https://github.com/git-fixtures/basic.git",
		ReferenceName: plumbing.ReferenceName("notexistingbranch"),
	})
	if err != nil {
		if _, err := os.Stat("repository/.git"); err != nil {
			if os.IsNotExist(err) {
				log.Print("Not Exists")
			} else {
			}
		}
		log.Print("Exists")
	}
}
```

### What did you expect to see?
I expexted to see, that the .git directory does not exist after a failing pull

### What did you see instead?
I saw that the directory exist, when the error is not nil.

**Comment by chrisdostert** [comment]
we have downstream code to handle this; would be nice to no longer need it. If it helps whoever takes this issue, here's our current implementation: https://github.com/opspec-io/sdk-golang/blob/59be62cca3ade0a121630d60e5dd160cff35a6c5/pkg/puller.go#L80
