### ISSUE TITLE
How do i get the staged changes?

### ISSUE THREAD

**Issue by nseps** [src-d/go-git#746]
I have tried getting the index from the storer but the entries do not have the staged changes.

How do i get them?

**Comment by jacksgt** [comment]
`Worktree.Status` has changes to the working tree, but not specifically only staged changes:

https://godoc.org/gopkg.in/src-d/go-git.v4#Worktree.Status

https://godoc.org/gopkg.in/src-d/go-git.v4#Status

**Comment by nseps** [comment]
Looks like what i'm looking for. Thanks!

I'll give it a try and maybe post a code snippet for reference.
