### ISSUE TITLE
Request to allow the use of other package management options

### ISSUE THREAD

**Issue by alimoeeny** [src-d/go-git#747]
Hi there, 
Great work, thank you.
May I ask if you can not enforce use of `gopkg.in`
We use `gvt` for vendoring and we'd rather manually pin things to the versions we test, the way we want them and not to trust an additional source of potential compromises and security issues and outage etc. 

I am sure people who manage `gopkg.in` are the best, (I don't know them), but if you can just make it optional to use your versioning, that would be very much appreciated.

**Comment by mcuadros** [comment]
Can't you change the source from a repository using `gvt`?

Maybe you should consider a change to [`dep`](https://golang.github.io/dep/), that allows it:

```
[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
```

Allowing non `gopkg.in` URLs, may introduce confusion into the community since the people trends to use the GitHub URL as package import.

**Comment by alimoeeny** [comment]
Thanks @mcuadros 
Yes you can do that in `gvt` too. But unless I am mistaken, the library (go-git that is) and various releated libraries will still complain that they need to be imported from the correct gopkg.in path and not directly from their github path. 
I really am not in a place to push this, just find the whole gopkg.in thing , a solution to a problem that does not exist any more. 
Keep up the good work. and feel free to close this.

**Comment by mcuadros** [comment]
Using the method I explained, is going to clone the repository from GitHub and place it at gopkg.in path. And at least `dep` is not going to complain about this.
 
Which problem doesn't exist anymore?

**Comment by alimoeeny** [comment]
Thanks @mcuadros 
There used to be a time, that the only package management tool available for go was `go get` and that make things like `gopkg.in` and similar solutions very appealing. They allowed you to pin your dependencies to a specific version.
These days you do that by using one of the many package management tools, like `gvt` or `dep` ...
Which makes using a man in the middle, that makes things opaque and adds another point of failure to the mix and a potential for security issues rather unnecessary.
That's all I am saying. 
Thanks again.

**Comment by alimoeeny** [comment]
Looks like I need to learn more about `gopkg.in` and how it works.
Thanks for your time.
