### ISSUE TITLE
Proposal: File.Contents should return []byte instead of string

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/go-git#752]
The current implementation of [File.Contents()](https://github.com/src-d/go-git/blob/master/plumbing/object/file.go#L31) returns a string instead of byte array. This is inconvenient in many cases, and I personally suffer in multiple projects, having to copy-paste the whole method and change `buf.String()` to `buf.Bytes()`. Thus I propose to do one of the two things:

1. Change `string` to `[]byte` - it breaks backward compatibility.
2. Add another method which is identical but returns `[]byte`.

**Comment by mcuadros** [comment]
`Contents` is a sugar syntax mainly for printing, if you need to write a file to the storage or any other stream-oriented process you should use the `Reader` method. Since a file potentially can contain any size of file, it's not recommended put in memory the blob, as string neither as bytes.

If you want the bytes is that easy as:

```go
r, _ := f.Reader()
bytes, _ := ioutil.ReadAll(r)
```

**Comment by vmarkovtsev** [comment]
I put all the blobs in a single commit to memory because they are read several times, also I send them to Babelfish and Enry and their APIs accept only `[]byte`. Your example also needs `defer r.Close()` and error handling. The actual code for `String()` is:

```
reader, err := f.Reader()
if err != nil {
	return "", err
}
defer ioutil.CheckClose(reader, &err)

buf := new(bytes.Buffer)
if _, err := buf.ReadFrom(reader); err != nil {
	return "", err
}

return buf.String(), nil
```

You must agree that it is far from being trivial. Currently, every project of mine reinvents this method with `return buf.Bytes(), nil` in the end which I don't think is good after all. This is my suggestion to reduce the amount of boilerplate code in downstream code.
