### ISSUE TITLE
src-d/go-git refers to its own packages through the gopkg.in indirection

### ISSUE THREAD

**Issue by heavenlyhash** [src-d/go-git#76]
I'm pretty sure a repo shouldn't refer to its own packages through gopkg.in?  It's really weird that I clone this, then try to build, then have to let `go get` fetch the *same* repo through the interweb again...

**Comment by mcuadros** [comment]
Sorry but is the only way and the common usage of gopkg.in, the correct way to install the package is:
`go get -u gopkg.in/src-d/go-git.v3/...`

if you want clone your fork or something should be cloned to `$GOPATH/src/src-d/go-git.v3`

Here you can see a example of the usage by the author of `gopkg.in` -> https://github.com/go-mgo/mgo/blob/v2-unstable/txn/debug.go

**Comment by heavenlyhash** [comment]
Oh, I see.  I must've misunderstood gopkg.in.  I thought it did the import rewrites for you when it proxied things so the source didn't need to change.  thanks, sorry for the dumb question.
