### ISSUE TITLE
How to get the list of all remote branches?

### ISSUE THREAD

**Issue by Labutin** [src-d/go-git#767]
Repository.Branches() returns the list of local branches.
How to get the list of all remote branches like `git branch -a` or `git branch -r` command?

**Comment by mcuadros** [comment]
Can you provide a git command, as an example?

**Comment by Labutin** [comment]
I have provided in the first post.
`git branch -a` shows all branches includes remote
`git branch -r` shows only remote branches

**Comment by ilius** [comment]
Right now, you need to get the remote, and then use `remote.List` that gives the list of references in that remote which may also contain non-branch references, so you need to filter non-branch references out.

	remote, err := r.Remote("origin")
	if err != nil {
		return nil, err
	}
	refList, err := remote.List(&git.ListOptions{})
	if err != nil {
		return nil, err
	}
	refPrefix := "refs/heads/"
	for _, ref := range refList {
		refName := ref.Name().String()
		if !strings.HasPrefix(refName, refPrefix) {
			continue
		}
		branchName := refName[len(refPrefix):]
		fmt.Println(branchName)
	}
