### ISSUE TITLE
Is it possible to clone / checkout a repo

### ISSUE THREAD

**Issue by odewahn** [src-d/go-git#77]
Hi, and thanks for this great project.  Is there an example of how to do the equivalent of a `git clone`? Or, is this even possible?

**Comment by mcuadros** [comment]
Hi there we are finishing the [v4](https://github.com/src-d/go-git/tree/v4) this days, on this version we have a example exactly with want you want:

https://github.com/src-d/go-git/blob/v4/examples/clone/main.go

**Comment by odewahn** [comment]
That's so exciting -- thanks, @mcuadros!

**Comment by odewahn** [comment]
Hi, @mcuadros.  I was trying this clone feature -- it's really cool.  

One question: maybe I'm missing something, but this doesn't seem to great the .git directory with the history.  So, suppose I want to use this to clone a repo, make some changes,commit them, and then remerge that back into the original project.

That doesn't seem to be supported yet, or I'm just missing something.

Is that something that will be possible in v4?

**Comment by mcuadros** [comment]
Currently the only features supported by go-git are Clone and Pull, you can't make Push, this is a feature that isn't on our current roadmap 

but any contribution is more than welcome
