### ISSUE TITLE
ResolveRevision doesn't resolve annotated tags

### ISSUE THREAD

**Issue by rykov** [src-d/go-git#772]
Looking through the `revision.Ref` case for the switch statement in `ResolveRevision`, the tag is resolved, however, calling `r.CommitObject` fails with "object not found" error because the resolved commit is not a commit Hash. Seems like one needs to call `r.resolveToCommitHash` either before `CommitObject` or inside of it (depending on the intended API)

https://github.com/src-d/go-git/blob/ecda5c1512bcb19e1802d629b18872ec995e23cf/repository.go#L914-L930

**Comment by mcuadros** [comment]
Can you provide an example repository? Thanks

**Comment by rykov** [comment]
Here's a quick way to reproduce this:

```sh
$ git init 
$ git commit --allow-empty -m "Initial commit"
$ git tag -a ann-tag -m "Annotated!"
$ git tag reg-tag
```

And then run:

```go
package main

import(
  "gopkg.in/src-d/go-git.v4"
  "gopkg.in/src-d/go-git.v4/plumbing"
  "fmt"
)

func main() {
  r, _ := git.PlainOpen(".")
  rev1, err := r.ResolveRevision(plumbing.Revision("reg-tag"))
  fmt.Println("Regular tag: ", rev1, err)
  rev2, err := r.ResolveRevision(plumbing.Revision("ann-tag"))
  fmt.Println("Annotated tag: ", rev2, err)
}
```

The output that I see with v4.1.1 is:

```
Regular tag:  7e454763ed760efa060937a9fd603a60b9fd2879 <nil>
Annotated tag:  0000000000000000000000000000000000000000 object not found
```

**Comment by orirawlings** [comment]
It seems like `git rev-parse` would resolve to the hash of the `tag` object in this case. So we probably want to mimic that behavior as well.

**Comment by rykov** [comment]
If you mean the hash of the annotated tag object, then it makes sense, but we also then need a public method to unpeel that to a commit hash.  Something similar to `r.resolveToCommitHash`

**Comment by pinoniq** [comment]
In the meantime, is there another way to resolve annotated tags using go-git?

**Comment by pinoniq** [comment]
I did some digging and I managed to get it working "kind of".

repository.ResolveRevision expects the resolved reference to be a commit. This is the case for lightweight tags. But not at all for annotated tags.

replacing
```
			if ref != nil {
				refCommit, rErr = r.CommitObject(ref.Hash())
			} else {
				rErr = plumbing.ErrReferenceNotFound
			}
```
with
```
			if ref != nil {
				if ref.Name().IsTag() {
					refTagObject, rErr = r.TagObject(ref.Hash())
					refCommit, rErr = refTagObject.Commit()
				} else {
					refCommit, rErr = r.CommitObject(ref.Hash())
				}
			} else {
				rErr = plumbing.ErrReferenceNotFound
			}
```

seems to do the job.

**Comment by mcuadros** [comment]
Solved
