### ISSUE TITLE
The current library cannot implement HTTP. Proxy?

### ISSUE THREAD

**Issue by barnettZQG** [src-d/go-git#774]
```
git config --global https.proxy http://127.0.0.1:1080
```
Typically, git supports HTTP. Proxy is very useful and I don't see any support for the current library. If yes, please let me know how to use it. Thank you.

**Comment by mcuadros** [comment]
You have two options as explained at https://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client

If the option of the environment variable is not enough, or simply you want  don't to use it, you can the `http.Transport` option too, take a look to https://github.com/src-d/go-git/blob/master/_examples/custom_http/main.go

**Comment by barnettZQG** [comment]
thank you!
