### ISSUE TITLE
about log

### ISSUE THREAD

**Issue by hugcoday** [src-d/go-git#775]
use this lib to get git log, 
	cIter, err := r.Log(&git.LogOptions{From: ref.Hash()})
        for { 
              nextIter, err := cIter.Next()
        }

this get the log not all, some log not get , use cmd  git log --date=iso --pretty=format:'"%h","%an","%ad","%s"' >log.csv

you will find the different.

**Comment by ilius** [comment]
The default commit order is different than `go git`.

If you want to have the same order as `go git`, pass the Order option, like this:

	cIter, err := b.r.Log(&git.LogOptions{
		From:  ref.Hash(),
		Order: git.LogOrderCommitterTime,
	})

**Comment by ilius** [comment]
I just realized that I typed `go git` instead of `git log` in my comment :)))
