### ISSUE TITLE
Tests in the root package are too slow

### ISSUE THREAD

**Issue by mvdan** [src-d/go-git#780]
They should either be made faster (parallel tests, or other fixes), or the slowest should be skipped on `testing.Short()`.

At the moment, this is far from ideal:

```
$ go test -short
OK: 197 passed
PASS
ok      gopkg.in/src-d/go-git.v4        58.933s
```

I would have expected 10 seconds at most. Ideally, 2-3 seconds or less.

**Comment by mvdan** [comment]
Here's another - the tests aren't standard Go, so I can't use out of the box features like test's `-v` and `-run`. Is there a reason for that?

**Comment by mcuadros** [comment]
We want to change it to use asserty, as any other modern development at source{d}. But the current test suite is built on top of [gocheck](https://labix.org/gocheck), this decision was made 3yrs ago, when was the default test framework for us, now we have a bunch of tests to change it, so its a lot of work for a little benefit.

**Comment by mvdan** [comment]
I honestly don't mind whatever test framework is used. But in my opinion, the end result is that regular Go tests are run, so that `go test` flags like `-v` and `-run` are useful. Otherwise, `go test` is little other than running some arbitrary Go program that fails or succeeds.

**Comment by mcuadros** [comment]
Yep, but sadly this, flags are "ignored" by gocheck. Since the whole testsuite runs under the same `T`
