### ISSUE TITLE
use of closed network connection during clone - need help

### ISSUE THREAD

**Issue by StanislavKH** [src-d/go-git#781]
when trying to simply clone repository get next message: 

```
Counting objects: 338816, done.
Compressing objects: 100% (92030/92030), done.
Total 338816 (delta 252833), reused 325149 (delta 239214)
2018/03/14 15:49:10 close tcp xxx.xxx.xxx.xx:44238->xxx.xxx.xxx.x:22: use of closed network connection
```

after this I have .git folder with partial data, around 210-211Mb,
complete repository folder size 980Mb 

not a constantly, I have another 2 repositories and they work very good...

anyone can help to understand how to fix this problem ? with console default git all work without any problems

**Comment by StanislavKH** [comment]
looks like my mistake, sorry, issues closed

**Comment by dirkaholic** [comment]
@StanislavKH I'm having the same issue now. Could you elaborate on what was the mistake ?

**Comment by jmcarbo** [comment]
Yes, I am also getting this error with large repositories, any insight?

**Comment by kainlite** [comment]
Same here, I have a big repo (1.5Gbs), I believe it's timing out and I get the exact same error, any recommendation? or workaround?
