### ISSUE TITLE
How to implement git describe command?

### ISSUE THREAD

**Issue by tamalsaha** [src-d/go-git#788]
Hi,
I would like to find the descendant tags for a commit on a branch. I use tags to mark release for my project. I want to find out in which release(s) a particular commit was included. Is there any example how to do this? If not example, can you give me some idea on how to implement this?

Thanks.

**Comment by hairyhenderson** [comment]
See also #736 (maybe this is a duplicate?)

**Comment by tamalsaha** [comment]
Thanks @hairyhenderson ! Looks like a duplicate.
