### ISSUE TITLE
Fetch: object not found

### ISSUE THREAD

**Issue by jacksgt** [src-d/go-git#802]
Hi there,

I'm having an issue fetching updates from Github.

The repository was previously cloned like so:
```
	r, err := git.PlainClone(dir, false, &git.CloneOptions{
		URL:   url,
		Depth: 1,
	})
```

then, after modifications have been made to the remote repository, I want to fetch updates:
```
	err = r.Fetch(&git.FetchOptions{})
```
But this results in a `object not found` error (`ErrObjNotFound`).

`git fetch` (`--all`) works just fine.

Any suggestions how I can debug this issue?

**Comment by mcuadros** [comment]
Can you provide a repository where this fails? Thanks

**Comment by jacksgt** [comment]
E.g. https://github.com/jacksgt/test-2

**Comment by barnettZQG** [comment]
same issues.
clone single branch.
Clone config:
```
opts := &git.CloneOptions{
		URL:               csi.RepositoryURL,
		Progress:          progress,
		SingleBranch:      true,
		RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
		Depth:             1,
	}
```
if I commit 2 times or more. pull will result `ErrObjNotFound `
```
opts := &git.PullOptions{
		Progress:     progress,
		SingleBranch: true,
}
```

**Comment by barnettZQG** [comment]
There's how I analyzed it.

Becaues clone options set depth is 1. after clone, local store have one commit info that it have parent commit hash, but local store don't have parent commit info.
gopkg.in/src-d/go-git.v4/plumbing/storer/object.go 
```
func (iter *EncodedObjectLookupIter) Next() (plumbing.EncodedObject, error) {
	fmt.Println("(iter *EncodedObjectLookupIter) Next()", len(iter.series))
	if iter.pos >= len(iter.series) {
		return nil, io.EOF
	}

	hash := iter.series[iter.pos]
	fmt.Println("(iter *EncodedObjectLookupIter) Hash", hash)
	obj, err := iter.storage.EncodedObject(iter.t, hash)
	if err == nil {
		iter.pos++
	}
	return obj, err
}
# output
# (iter *EncodedObjectLookupIter) Next() 1
# (iter *EncodedObjectLookupIter) Hash 00135cb9d1a16fe910404efa7024c8e7f67851f7
# iter.EncodedObjectIter.Next() object not found
```
when pull code, it could loop local store commits. Error in the appeal code. then why need to loop local store commits or whether need to ignore this error in the pull.

**Comment by jacksgt** [comment]
So this only happens when the initial clone was done with depth = 1?

**Comment by barnettZQG** [comment]
@jacksgt I think so

**Comment by jfontan** [comment]
Can you check if #810 fixes your problems?

**Comment by mcuadros** [comment]
@jacksgt can you check if is now fixed at version: v4.3.1?
https://github.com/src-d/go-git/releases/tag/v4.3.1

**Comment by mcuadros** [comment]
Closing, if it isn't fixed please re-open

**Comment by cmbernard333** [comment]
I am seeing this issue with v4.11.1. Clone is done like this 
```
	r, err := git.PlainClone(path, false, &git.CloneOptions{
		Auth:          authmethod,
		ReferenceName: plumbing.NewBranchReferenceName(branchName),
		Depth:         depth,
		SingleBranch:  singleBranchOnly,
		URL:           gitURL,
	})
```

Followed by a pull later on
```
	w, err := g.Repository.Worktree()
	if err != nil {
		return err
	}
	return w.Pull(&git.PullOptions{
		Auth:         authMethod,
		Depth:        depth,
		RemoteName:   "origin",
		SingleBranch: singleBranch})
```

Is this still an issue in the latest code?
