### ISSUE TITLE
Determining merged references?

### ISSUE THREAD

**Issue by sudoforge** [src-d/go-git#812]
I have a need to determine branches that are merged into the currently checked out reference. Right now, I'm doing something that I consider a little hacky:

```
//determine current ref name
fullRef, err := r.Head()
checkIfError(err, removePath)

// determine which branches are merged
os.Chdir(path)
p := pipe.Line(
    pipe.Exec("git", "branch", "--all", "--merged"),
    pipe.Exec("grep", "-v", fmt.Sprintf("master|develop|%s", fullRef.Name().Short())),
    pipe.Exec("sed", "-E", "s/^\\s*\\*?\\s*//"),
)

output, err := pipe.CombinedOutput(p)
checkIfError(err, removePath)

mergedBranches := strings.Fields(fmt.Sprintf("%s", output))
fmt.Print(mergedBranches, "\n")
```

As far as I can tell, there's not really a cleaner way to do this using your package. Is there a recommended approach for this?

**Comment by sudoforge** [comment]
Thanks for the pointers!

**Comment by smola** [comment]
@sudoforge If you happen to implement this in an open source project, we'll be glad to hear about it ;-)

**Comment by sudoforge** [comment]
If I end up implementing a solution for this in your library (and I will, eventually), it will _definitely_ end back upstream. Currently, however, I'm just using a similar solution to the semi-psuedo code in my original comment, and implementing this natively is not a priority for that particular project.

**Comment by petems** [comment]
I wrote some logic to do this: https://github.com/petems/git-merged-master

In fact it was for basically the same usecase: a gitsweeper for deleting old branhces 😄

**Comment by petems** [comment]
The logic is basically iterate through every head of remote branches, compare with the commits from the master branch, if they match then it's been merged:

```golang
err = masterCommits.ForEach(func(commit *object.Commit) error {
		for branchName, branchHead := range remoteBranchHeads {
			if branchHead.String() == commit.Hash.String() {
				log.Infof("Branch %s head (%s) was found in master, so has been merged!\n", branchName, branchHead)
				mergedBranches = append(mergedBranches, branchName)
			}
		}
		return nil
	})
```
