### ISSUE TITLE
use time.IsZero

### ISSUE THREAD

**Issue by GeorgeErickson** [src-d/go-git#813]
Was looking over the code and noticed a tiny code review nit:

Probably want to use [`Time.IsZero`](https://golang.org/pkg/time/#Time.IsZero) here

https://github.com/src-d/go-git/blob/a042efacfd3a278a9423008948022728555dcee1/prune.go#L52

**Comment by smola** [comment]
@GeorgeErickson Thanks! Feel free to make a PR.
