### ISSUE TITLE
increase performance of DiffTree, applying the same algorithm being use at git

### ISSUE THREAD

**Issue by mcuadros** [src-d/go-git#82]

**Comment by alcortesm** [comment]
See https://github.com/alcortesm/git-diff-tree-benchmarks for a description of why our old implementation needs improvements.

**Comment by alcortesm** [comment]
The fix involves taking advantage of the fact that git trees are merkle trees so you don't really need to check all the files in a directory to know if they have change, as the hash of the directory can already tell you if they have change or not.

These patches introduce a generic merkle trie (it is also a n-trie) implementation and an efficient comparator that can be used to quickly compare git trees.
