### ISSUE TITLE
Windows without got, bash or ming64

### ISSUE THREAD

**Issue by gedw99** [src-d/go-git#829]
Can I use this to do standard git things and push and pull from GitHub etc ?

For example will go get use go-got to pull down GitHub repos ? I can always just git clone of course into the correct place in my gopth. But am curious if anyone has gotten this to work

I am a Mac user and run windows in virtbox.
I want to have windows 10 without bash, git , ming64 and all that crap.
Then I just use mage ( a make equivalent) in 100% golang to make any porcelain I need to do repeditive stuff like git operations.

https://github.com/magefile/mage
I love mage.

Sorry about such a user group style question on the issues list.

Thanks for making this btw ! It's needed by me at least for my sanity :)

**Comment by smola** [comment]
@gedw99 Indeed, go-git will work standalone.
