### ISSUE TITLE
Config doesn't contain all the local branches, but only master. 

### ISSUE THREAD

**Issue by erleene** [src-d/go-git#842]
Hi. I'm currently experiencing an issue with a small project I'm working on. 

I have found an interesting case when I try to delete local branches of a git repository. 

Below is the code I've been testing out.

*Current Scenario:*
- I have a repository with a local branch ( that has a remote branch too)
- I currently have two branches: `master` and `local1`
- However, when I print out the Branches, it only prints out master, therefore the delete function will not run as the local branch I want to delete isn't being loaded in the Config. It seemingly only loads the `master` branch

*Problem:*
- I expected the config to print out `master` and `local1`, but only `master gets printed. any help around this? 

```
repo, err := git.PlainOpen(dir) // *Repository
if err != nil {
  return err
}

config, _ := repo.Config()
for key, value := range config.Branches {
  fmt.Printf("key: %s, value: %s\n", key, value.Name) //only printing master, it's not printing local1. sad. 
}

if branch, exists := config.Branches["local1"]; exists {
   fmt.Printf("branch %s exists", "local1")

   if err := repo.DeleteBranch(branch.Name); err != nil {
	fmt.Println(err.Error())
   }

  if err := repo.DeleteRemote(branch.Name); err != nil {
        fmt.Println(err.Error())
  }
}
```

**Comment by erleene** [comment]
any help?

**Comment by erleene** [comment]
looks like....it's dead.

**Comment by jdortiz** [comment]
The config package works for me. The Branches map contains all the branches of all the repos I have tried. :-/

**Comment by smola** [comment]
@erleene Is `local1` present in your `.git/config`?

**Comment by smola** [comment]
I cannot reproduce it. Your code seems to work.

`Config.Branches` contains branches that are defined in `.git/config`, not all branches that are actually in the repository, use `Repository.Branches` for that.
