### ISSUE TITLE
Compilation fails on OpenBSD

### ISSUE THREAD

**Issue by oytunistrator** [src-d/go-git#843]
An arrangement may be made for these operating systems. Some definitions are missing.
```
2 errors occurred:
--> openbsd/386 error: exit status 2
Stderr: # gopkg.in/src-d/go-git.v4
../../../../gopkg.in/src-d/go-git.v4/worktree_bsd.go:15:36: os.Atimespec undefined (type *syscall.Stat_t has no field or method Atimespec)

--> openbsd/amd64 error: exit status 2
Stderr: # gopkg.in/src-d/go-git.v4
../../../../gopkg.in/src-d/go-git.v4/worktree_bsd.go:15:36: os.Atimespec undefined (type *syscall.Stat_t has no field or method Atimespec)

```

**Comment by smola** [comment]
It might be `Atim` instead `Atimespec` for OpenBSD.

**Comment by mschoenlaub** [comment]
Is there a reason why atime is used in BSD but ctime on linux?

**Comment by mschoenlaub** [comment]
> It might be `Atim` instead `Atimespec` for OpenBSD.

In fact, it differs between different BSD flavours apparently. See https://github.com/djherbis/times

**Comment by smola** [comment]
Added hacktoberfest label, note that beyond fixing this build problem, tests should pass.
