### ISSUE TITLE
Why we can commit even no file added

### ISSUE THREAD

**Issue by kamontat** [src-d/go-git#871]

**Comment by Zeymo** [comment]
@kamontat  maybe you should check status first , such as
```
wt, _ := r.Worktree()
s, _ := wt.Status()
if s.IsClean() {
	// do somgthing
	return
}
```

**Comment by smola** [comment]
Having a commit with the same tree as its parent (that is, a commit with no file changes) is valid in git. In fact, some projects use this kind of commit. You can see an example here: https://github.com/apache/spark/commit/085f510ae554e2739a38ee0bc7210c4ece902f3f

**Comment by kamontat** [comment]
@Zeymo  IsClean is not work. Since it check only `Unmodified` files
