### ISSUE TITLE
Get git information

### ISSUE THREAD

**Issue by justinosbaldiston** [src-d/go-git#884]
Hi there,

First of all, thanks for making this awesome library! Just wondering if there is a way to get the git details eg name and email that get sent with commits from this library?

EDIT:
For example, in the git client I can run git config --get user.name and git config --get user.email

**Comment by noxora** [comment]
I'll start off by saying I'm not a contributor, but I have been working with this library a good bit recently.

As far as I can tell, there is not currently supported in the current "Config" struct which looks like 
(Please note, I have stripped comments for brevity)
```
type Config struct {
	Core struct {
		IsBare bool
		Worktree string
	}

	Pack struct {
		Window uint
	}

	Remotes map[string]*RemoteConfig
	Submodules map[string]*Submodule
	Branches map[string]*Branch
	Raw *format.Config
}
```

While in my <repo>/.git/config file, I have 
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = ...
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "hook-support"]
	remote = origin
	merge = refs/heads/hook-support
[user]
	name = noxora
```

What I am guessing is that there is no field in the `Config` struct to accommodate  a locally set user.

A possible alternative would be to see what has been previously set in that repo, which might give you an insight. But I don't know your use case

So something to the effect of 
```
repo, err := git.PlainOpen("...")
commits := getCommits(repo.CommitObjects()) //pretend this returns []Object.Commit
fmt.Println("commits[0].Author.Email")
fmt.Println("commits[0].Author.Name")
```
I hope it helps!

**Comment by smola** [comment]
As @noxora, it is currently not exposed in the high-level config representation. However, you can still access everything in config with the `Raw` field, which contains the whole thing.

To access the user name field you would do:

```go
name := cfg.Raw.Section("user").Option("name")
```
