### ISSUE TITLE
how to create a new tag?

### ISSUE THREAD

**Issue by ycyxuehan** [src-d/go-git#911]
hi, how to create a new tag? i kown how to create a branch, and now, i want to create a tag, how cant i do it? thanks.

**Comment by loafoe** [comment]
@ycyxuehan the repo contains an example for creating new references:

https://github.com/src-d/go-git/blob/1fdd36c814746efdf199392135696cfde7287b44/_examples/branch/main.go#L29-L38

**Comment by ycyxuehan** [comment]
> @ycyxuehan the repo contains an example for creating new references:
> 
> [go-git/_examples/branch/main.go](https://github.com/src-d/go-git/blob/1fdd36c814746efdf199392135696cfde7287b44/_examples/branch/main.go#L29-L38)
> 
> Lines 29 to 38 in [1fdd36c](/src-d/go-git/commit/1fdd36c814746efdf199392135696cfde7287b44)
> 
>  // Create a new plumbing.HashReference object with the name of the branch 
>  // and the hash from the HEAD. The reference name should be a full reference 
>  // name and not an abbreviated one, as is used on the git cli. 
>  // 
>  // For tags we should use `refs/tags/%s` instead of `refs/heads/%s` used 
>  // for branches. 
>  ref := plumbing.NewHashReference("refs/heads/my-branch", headRef.Hash()) 
>   
>  // The created reference is saved in the storage. 
>  err = r.Storer.SetReference(ref)

thanks ,i will try
