### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by ParticleDecay** [src-d/go-git#914]
After importing go-git into my project, I can no longer build successfully. I get the following error:
```
➜ go build
../go/pkg/mod/github.com/src-d/go-git@v4.5.0+incompatible/repository.go:14:2: use of internal package gopkg.in/src-d/go-git.v4/internal/revision not allowed in github.com/src-d/go-git
```
I'm using go-1.11beta3 and this is a project outside of `$GOPATH`. I'm using go modules for this project.

**Comment by kuba--** [comment]
@ParticleDecay how did you import `go-git` (what import path did you use)?
You cannot import as `github.com/src-d/go-git`. It has to go via `gopkg.in`, so for go-git 4.X it will be: `gopkg.in/src-d/go-git.v4`

**Comment by smola** [comment]
Closing. Please, reopen if there is any doubt about the resolution.
