### ISSUE TITLE
Delete Remote Branch

### ISSUE THREAD

**Issue by austin127001** [src-d/go-git#917]
I'm attempting to write a utility that deletes branches in which the last commit date is beyond some threshold. I'm able to determine what needs to be deleted but I cannot quite seem to delete the remote branch from the server.

What is the equivalent of:

`git push --delete <remote_name> <branch_name>`

**Comment by glibsm** [comment]
Remote branches can be deleted through refspec.

Something like the following:

```go
Info("git push")
err = r.Push(&git.PushOptions{
    RefSpecs: []config.RefSpec{
        config.RefSpec(":master"),
    },
})
```

https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

**Comment by austin127001** [comment]
Hey glibsm,

First, thanks for responding.

This is what I've been attempting:
```
r.Push(&git.PushOptions{
	Auth:       getAuth(), 
	RefSpecs:   []config.RefSpec{config.RefSpec(":branch_to_delete")},
	Progress: os.Stdout,
})
```
However this doesn't seem to reflect any change on the server :/. Additionally, I get no output (shouldn't i?) Is there a way to dig into what exactly is going wrong? Do I need to have a worktree and checkout each specific branch?

Currently I'm just doing a clone to memory, requesting remotes that are branches, and trying to delete them (I don't really care about anything that's in the branches, just that they haven't been contributed to.

Thanks again for the assistance.

**Comment by austin127001** [comment]
I was able to determine a solution to my issues:
- I was attempting to use repository.Push vs remote.push
- I had the refspec incorrect

In case anyone else ever needs this:
```
func deleteBranch(r *git.Remote, branchShortName string) {
    r.Push(&git.PushOptions{
	    Auth:     getAuth(), // However you handle that
	    RefSpecs: []config.RefSpec{config.RefSpec(":refs/heads/" + branchShortName)},
	    Progress: os.Stdout,
    })
}
```
