### ISSUE TITLE
Patches for files without newline at the end are not appliable by `git apply`

### ISSUE THREAD

**Issue by distorhead** [src-d/go-git#936]
Go-git generates broken diff-s for files without newline at the end. These patches cannot be applied by `git apply` command.

Original `git diff` command will generate patch with special line `\ No newline at end of file` marker.

Here is repo with example program in main.go: https://github.com/flant/go-git-test-2.

```
git clone https://github.com/flant/go-git-test-2 /tmp/go-git-test-2
cd /tmp/go-git-test-2
go build ./main.go
./main > bad.patch
git checkout c73fd0c6d5669affde76a78c60e4cc372d39abc1
git apply bad.patch
```

Gives:

```
error: patch failed: README.md:1
error: README.md: patch does not apply
```

**Comment by distorhead** [comment]
Found possible workaround: use `git apply --inaccurate-eof`.

**Comment by nclandrei** [comment]
Hi @distorhead! Can I start work on this? 🙂

**Comment by distorhead** [comment]
Hi! Sure, I does not have any code contributions for this, unfortunately.

**Comment by ZerooCool** [comment]
With PHP, JavaScript and CSS file, i use PHP-CodeSniffer
Work good to format with the PSR-2 standard + 1 end line
Then, i don't have this message : "No newline at end of file"

PHP-CodeSniffer :
https://wiki.visionduweb.fr/index.php?title=Sommaire_des_tutoriels_pour_developpeur#Php-codeSniffer
