### ISSUE TITLE
all: convert into a Go module

### ISSUE THREAD

**Issue by mvdan** [src-d/go-git#943]
Should be straightforward enough. Go modules support `gopkg.in` without any changes, so we don't have to break backwards compatibility. For example, this worked for me:

```
cd go-git
go mod init
go mod tidy
```

Also note that the `// import "gopkg.in/src-d/go-git.v4"` comment in `doc.go` should be removed once the commands above have been run, as Go modules make this enforcement of import paths obsolete.

Once we reach v5, it may make sense to transition to another module path, like `sourced.tech/go-git/v5`.

I've been helping a bit with modules, and have converted most of my repos to them - so I'm happy to help if there are any questions or issues.

cc @mcuadros @smola @campoy

**Comment by mcuadros** [comment]
https://github.com/src-d/go-git/commit/83649a1c08e0dcc103de54652ed5b9c33d301326

We will remove gopkg.in for v5, meanwhile, we keep the gopkg.in comment.

**Comment by mvdan** [comment]
> meanwhile, we keep the gopkg.in comment.

That's fine that you want to keep `gopkg.in` for v4 - but the vanity import comment should still be removed. It's now the `go.mod` file that enforces import paths. In particular, see `module gopkg.in/src-d/go-git.v4`.
