### ISSUE TITLE
Error when pushing to an AWS CodeCommit repo (offset deltas are not supported)

### ISSUE THREAD

**Issue by bashims** [src-d/go-git#945]
We are trying to use go-git to interact with AWS' CodeCommit over HTTPS.  After figuring out the auth portion I ran into the following errors when pushing to the repo:

'unpack error: protocol error (offset deltas are not supported)'

and the push failed. I am working on a PR that addresses this issue by using RefDeltas instead of OFSDeltas on push.

**Comment by bashims** [comment]
Of note I am using v4.6.0

**Comment by smola** [comment]
Thanks for the report @bashims. We should definitely support ref-deltas on push. If you are doing a PR, keep in mind that switching to ref-deltas should only be done if the server has no ofs-delta capability.

**Comment by bashims** [comment]
Hi @smola,

I will definitely add the capability check to my patch.

Thanks,

-ben

**Comment by bashims** [comment]
I submitted https://github.com/src-d/go-git/pull/952 for this enhancement.

**Comment by smola** [comment]
Fixed in https://github.com/src-d/go-git/pull/987

**Comment by WhileLoop** [comment]
@smola 
I am getting 
```Counting objects: 18, done.
reference delta not found
```

When doing PlainClone on Code Commit.

**Comment by nthj** [comment]
@WhileLoop I'm seeing the same thing with PlainClone on Code Commit. It works a fair bit of the time. Possible that a force push to `master` triggered this error, for me?
I'm rm -rfing my tmp/ directory before I try to PlainClone, so I don't _think_ it's any kind of caching issue.

**Comment by nthj** [comment]
```func cloneRepository(reference events.CodeCommitReference) {
	os.RemoveAll("/tmp/repository")

	_, err := git.PlainClone("/tmp/repository", false, &git.CloneOptions{
		Auth: &githttp.BasicAuth{
			Username: os.Getenv("AWS_ACCESS_KEY_ID") + "%" + os.Getenv("AWS_SESSION_TOKEN"),
			Password: getRepositoryPassword(),
		},
		Depth:         1,
		Progress:      nil,
		ReferenceName: getReferenceName(reference), // returns "ref/heads/master" in the failing instance
		SingleBranch:  true,
		Tags:          git.NoTags,
		URL:           getRepositoryURL(),
	})

	// results in "reference delta not found", sometimes
	check(err)
}```

**Comment by smola** [comment]
Moving to https://github.com/src-d/go-git/issues/1032
Since this appears to be a different issue.
