### ISSUE TITLE
how to do "git checkout -b newbranch origin/development" with go-git equivalently

### ISSUE THREAD

**Issue by nodew** [src-d/go-git#948]
I am writing a application with go-git, I'd like to checkout a new branch from remote branch after fetching remote code.
Is there any good example?

**Comment by nodew** [comment]
Thanks @pawelprazak.  Here is how I did it, but not sure if there's any better way
```golang
w, _ := r.Worktree()

remoteRef, err := r.Reference("refs/remotes/origin/development", true)

newRef := plumbing.NewHashReference("refs/heads/newbranch", remoteRef.Hash())

r.Storer.SetReference(newRef)

w.Checkout(&git.CheckoutOptions{
	Branch: newRef.Name(),
	Create: false,
})
```

**Comment by pawelprazak** [comment]
looks better, thanks! :)

**Comment by ZhenShaw** [comment]
## how to do "git checkout -b newbranch origin/development" with go-git equivalently

**Comment by ZhenShaw** [comment]
> Thanks @pawelprazak. Here is how I did it, but not sure if there's any better way
> 
> ```go
> w, _ := r.Worktree()
> 
> remoteRef, err := r.Reference("refs/remotes/origin/development", true)
> 
> newRef := plumbing.NewHashReference("refs/heads/newbranch", remoteRef.Hash())
> 
> r.Storer.SetReference(newRef)
> 
> w.Checkout(&git.CheckoutOptions{
> 	Branch: newRef.Name(),
> 	Create: false,
> })
> ```

i found it not equivalently to `git checkout -b newbranch origin/development`
