### ISSUE TITLE
Is it possible to download or get the contents from a single file in a remote using go-git

### ISSUE THREAD

**Issue by spstratis** [src-d/go-git#953]
I have a situation where I need to get the contents of a single JSON file from my companies remote repo from within one of my Go programs. Does this package provide a method for doing that? From the CLI you can achieve similar functionality using a command similar to 

`git archive --remote=ssh://foo@bitbucket.org/foobar/fooscripts.git HEAD path/to/file.json | tar -x`

Just curious if it's possible to do something similar directly in Go.

**Comment by smola** [comment]
Not in a particularly efficient way. You can just clone the repository (you can clone just `HEAD` to save bandwidth and storage) and look up the file.
