### ISSUE TITLE
"worktree contains unstaged changes" while checkout on a clean repo

### ISSUE THREAD

**Issue by syslxg** [src-d/go-git#959]
We see this on `https://github.com/bmatcuk/doublestar.git`

```go
	repo, err := git.PlainClone("/tmp/gittest", false, &git.CloneOptions{
		URL: "https://github.com/bmatcuk/doublestar.git"})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	wt, _ := repo.Worktree()
	err = wt.Checkout(&git.CheckoutOptions{
		Hash: plumbing.NewHash("v1.1.1"),
	})
```

**Comment by thehowl** [comment]
is this on windows? might be related to filemode being disabled, feature currently not implemented in go-git, which would mean go-git detects a change which is deliberately ignored by standard git

**Comment by syslxg** [comment]
it happed on both Linux and Mac. did not try it on Windows.

**Comment by smola** [comment]
@syslxg `v1.1.1` is not a hash, so that's not a valid checkout. Anyway, could you post full results? What's the status result? Did `wt.Checkout` return an error?

**Comment by syslxg** [comment]
```
 → cat test_gogit.go
package main

import (
	"fmt"
	"os"

	git "gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing"
)

func main() {
	repo, err := git.PlainClone("/tmp/gittest", false, &git.CloneOptions{
		URL: "https://github.com/bmatcuk/doublestar.git"})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	wt, _ := repo.Worktree()
	err = wt.Checkout(&git.CheckoutOptions{
		Hash: plumbing.NewHash("v1.1.1"),
	})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

 → rm -rf /tmp/gittest; go run test_gogit.go
worktree contains unstaged changes
exit status 1
```

**Comment by smola** [comment]
@syslxg `plumbing.NewHash("v1.1.1")` this is not valid, `NewHash` requires a SHA1 hash of a commit, which `v1.1.1` is not. You need to retrieve the tag first and then get its hash.
