### ISSUE TITLE
ls-remote - is there an equivalent function? 

### ISSUE THREAD

**Issue by nwbt** [src-d/go-git#971]
does **go-git** have an equivalent operation to `ls-remote`? This would allow listing of remote branches without having do the heavy operation of cloning first. Any listing of remote branches without having to do a clone would be optimal. Could be mistaken but haven't seen anything in the API.

**Comment by smola** [comment]
A high level API is available for remotes, see `List` function `Remote` can be used for that purpose:
https://godoc.org/gopkg.in/src-d/go-git.v4#Remote.List
https://github.com/src-d/go-git/blob/master/remote.go#L925
