### ISSUE TITLE
Tags() returning an empty TagIter even when target repository has tags

### ISSUE THREAD

**Issue by sbenthall** [src-d/go-git#98]
This code:

```
package main

import (
	"fmt"
	"gopkg.in/src-d/go-git.v3"
)

func main() {

	r, _ := git.NewRepository("https://github.com/src-d/go-git", nil)
	tags, _ := r.Tags()
	tag, err := tags.Next()
	fmt.Println(tags)
	fmt.Println(err)
	fmt.Println(tag)
}

```

Prints:

```
&{0xc8201195a0 0xc820119500}
EOF
<nil>
```

This is an error, since the target repository has many tags. For example, this one:

https://github.com/src-d/go-git/tree/v3.1.1

**Comment by mcuadros** [comment]
We are working now in the version 4.0, is almost done, in one or two weeks we are releasing it. I just figure out, that in the new one, the Tags feature is not working either.

I am fixing this in the v4 today, if everything goes well. 
Thx

**Comment by mcuadros** [comment]
Now is working `Tags` properly, but maybe is not what you expect, `Repository.Tags` returns the Tag objects,  so only the annotated tags are returned there.

For example for this returns all the tags objects from a repo:
```go
r, _ := git.NewFilesystemRepository(".git")
_ = r.Clone(&git.CloneOptions{URL: "https://github.com/git-fixtures/tags"})

tags, _ := r.Tags()
tags.ForEach(func(t *git.Tag) error {
	fmt.Println(t.ID(), t.Name)
	return nil
})
// Output:
// ad7897c0fb8e7d9a9ba41fa66072cf06095a6cfc commit-tag
// b742a2a9fa0afcfa9a6fad080980fbc26b007c69 annotated-tag
// fe6cb94756faa81e5ed9240f9191b833db5f40ae blob-tag
// 152175bf7e5580299fa1f0ba41ef6474cc043b70 tree-tag
```

If what you want is the tag references you can use this method:
```go
r, _ := git.NewFilesystemRepository(".git")
_ = r.Clone(&git.CloneOptions{URL: "https://github.com/git-fixtures/tags"})

refs, _ := r.Refs()
refs.ForEach(func(ref *core.Reference) error {
	if !ref.IsTag() {
		return nil
	}

	fmt.Println("tags ->", ref)
	return nil
})
// Output:
// 152175bf7e5580299fa1f0ba41ef6474cc043b70 refs/tags/tree-tag
// b742a2a9fa0afcfa9a6fad080980fbc26b007c69 refs/tags/annotated-tag
// fe6cb94756faa81e5ed9240f9191b833db5f40ae refs/tags/blob-tag
// ad7897c0fb8e7d9a9ba41fa66072cf06095a6cfc refs/tags/commit-tag
// f7b877701fbf855b44c0a9e86f3fdce2c298b07f refs/tags/lightweight-tag
```

**Comment by sbenthall** [comment]
Thanks!

**Comment by sbenthall** [comment]
Hi: 

This is still not working for me. When I run this code, I get no printed output.
I think my cloned copy of that repository is not getting the tags.

https://gist.github.com/sbenthall/d56f95433dea614c40e593f685b1bcc8

**Comment by sbenthall** [comment]
This code, based on your second example, shows that the cloned repository is getting the heads/master and remotes/origin/master refs, but none of the tags:

https://gist.github.com/sbenthall/003d682114c08de1ddc8bbb9a7ab2c7c
