### ISSUE TITLE
git checkout of tag doesn't work in local area

### ISSUE THREAD

**Issue by akdj** [src-d/go-git#980]
I tried the command  git checkout $TAG

I notice it displayed taht  it'is done. Hovewer, when I verified with command line "git describe --tags"
It show me, not the commit with tag, but the last commit pushed

**Comment by akdj** [comment]
Hi @smola , 
With go-git, I made a git clone of one of my gitlab repositories, then I tried to check out a tag release. it seems to be a "sucess" (there is a ''nil' error). So I stop my app.  And in the local git repository that I just clone, I did a 'git describe --tags' for checking if it is really checking out. 
As a result, the HEAD is on master branch's last commit. like the go-git checkout command is never performed.

Unfortunately, I didn't make a backup of this block of code... It is very similar to the example provided [here](https://github.com/src-d/go-git/blob/master/_examples/checkout/main.go)  indeed I copy paste

**Comment by akdj** [comment]
> I tried the command git checkout $TAG
> 
> I notice it displayed taht it'is done. Hovewer, when I verified with command line "git describe --tags"
> It show me, not the commit with tag, but the last commit pushed

sorry for my bad english... :)

**Comment by smola** [comment]
@akdj Thank you, we'll look into it.

**Comment by smola** [comment]
@akdj You must checkout by commit hash. If you want to checkout a tag, you will have to get the commit that tag points to first. See https://github.com/src-d/go-git/pull/985
