### ISSUE TITLE
Git compliant storage

### ISSUE THREAD

**Issue by pjebs** [src-d/go-git#995]
I understand this project attempts to have the same commands as the official git project.

I was just wondering if the git file storage is 100% compatible with standard git. i.e. if we open the `.git` directory here, it would just work. 

Also if we use a feature that is part of standard git but not available in this project, how would that affect the opening of a standard `.git` directory.

Are the storage directories interchangeable between the 2 projects.

**Comment by mcuadros** [comment]
Yep, go-git should replicate the behavior of git, if we have any mismatch should be reported as a bug, since our goal is to match the specifications from git
