### ISSUE TITLE
Delete remote tag by name

### ISSUE THREAD

**Issue by sontags** [src-d/go-git#996]
I need to delete a tag on a remote of a repo (the use case would be to maintain a `latest` tag that points to a commit considered as the latest stable). The git command to achieve this would be `git push --delete [remote] [tagname]`, eg. `git push --delete origin latest`.

Is there a way to get this done via go-git?

**Comment by smola** [comment]
@sontags You can use `Push` with a custom refspec (`:refs/tags/latest`).
See this example:https://github.com/src-d/go-git/issues/917#issuecomment-417440348

Note that StackOverflow is preferred for user questions, see: https://stackoverflow.com/questions/tagged/go-git

**Comment by sontags** [comment]
@smola thanks for that! I haven't thought of package related tags on StackOverflow, thanks for pointing out.

**Comment by rezadhah** [comment]
hi @sontags , can you remove local tag by name ? if you can, can you give me example code
